force-app/main/default/objects/Case/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>OFlows</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OFlows</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Borrower_Record__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field will only be populated when the loan is added from Salesforce - Temporary field used to create Loan Contact Relationship records.</description>
    <label>Borrower</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans (Borrower)</relationshipLabel>
    <relationshipName>Loans_Borrower</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CoBorrower_Record__c.field-meta.xml
<CustomField>
    <fullName>CoBorrower_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field will only be populated when Loan is added from Salesforce - temporary field used to create the Loan Contact Relationship records</description>
    <label>CoBorrower</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans (CoBorrower)</relationshipLabel>
    <relationshipName>Loans_Coborrower</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subject_Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Property_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject Property Name</label>
    <referenceTo>Properties__c</referenceTo>
    <relationshipLabel>Related Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Properties__c/Properties__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Properties Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OFlowDeleteTest.cls
@isTest
public class OFlowDeleteTest {
    @isTest
    public static void onDelete() {
        Lead lead = new Lead(FirstName = 'Dom', LastName = 'Test');
        insert lead;
        Case oFlow1 = new Case(Status = 'New', Lead__c = lead.Id, Subject = 'Test');
        insert oFlow1;
        Contact con = new Contact(FirstName = 'Dom', LastName = 'Test');
        insert con;
        Account act = new Account(Name = 'Test Account');
        insert act;
        Properties__c  prop = new Properties__c (Name = 'Test Property');
        insert prop;
        Opportunity  loan = new Opportunity (Name = 'Test', Borrower_Record__c = con.Id, CoBorrower_Record__c = con.Id, 
                                   AccountId = act.Id, StageName = 'Prospect', CloseDate = Date.today(), Subject_Property_Name__c = prop.Id);
        insert loan;
        Case oFlow2 = new Case(Status = 'New', Lead__c = lead.Id, Subject = 'Test 2', Loan__c = loan.Id);
        insert oFlow2;
        Test.startTest();
        delete loan;
        delete lead;
        Test.stopTest();
        List<Case> caseList = [SELECT Id FROM Case WHERE Subject = 'Test' OR Subject = 'Test 2'];
        System.assertEquals(0, caseList.size());
    }
    public static void onConvert() {
        Lead lead = new Lead(FirstName = 'Dom', LastName = 'Test');
        insert lead;
        Case oFlow1 = new Case(Status = 'New', Lead__c = lead.Id, Subject = 'Test');
        insert oFlow1;
        Test.startTest();
        lead.IsConverted = TRUE;
        update lead;
        Test.stopTest();
        List<Case> caseList = [SELECT Id FROM Case WHERE Subject = 'Test'];
        System.assertEquals(0, caseList.size());
    }
    
}