force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>This record type is used for Company or Business accounts.</description>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Subject_Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Property_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject Property Name</label>
    <referenceTo>Properties__c</referenceTo>
    <relationshipLabel>Related Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Properties__c/Properties__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Properties Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Most_Recent_Loan__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Number</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>New_Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/customLookUpController_TestNew.cls
@isTest
public class customLookUpController_TestNew {
    @isTest 
    public static void testQueries(){
    
        String searchKeyWord = 'Test';
        Account acc = new Account(Name='Test Account');
        insert acc;
        
        Properties__c prop = new Properties__c(Name='Test Prop');
        insert prop;
        String propId = prop.Id;
        
        Contact con = new Contact(AccountId=acc.Id,LastName='Test Contact');
        insert con;
        String contactId = con.Id;
        
        Lead l = new Lead(LastName='Test Lead',Status='New',Company='Test Company');
        insert l;
        
        Opportunity opp = new Opportunity(Name='Test Opp',StageName='New',CloseDate=Date.today(),ContactId=contactId, Subject_Property_Name__c = prop.Id);
        insert opp;
        

        
        test.startTest();
            
            List<Opportunity> oppList = customLookUpControllerNew.getLoanList(propId);
            System.assertEquals(1, oppList.Size());
            
            List<sObject> borrowers = customLookUpControllerNew.getBorrowerList(searchKeyWord);
            System.assertEquals(2, borrowers.size());
            
            List<Properties__c> props = customLookupControllerNew.getPropList(con.Id);

            List<Properties__c> propsFromLoan = customLookupControllerNew.getPropListFromLoanOpp(opp.Id);

            List<String> selectedIds = new List<String>();
            selectedIds.add('123456');
            List<LookupSearchResult> r = customLookupControllerNew.searchUser2(searchKeyword, selectedIds );

            Proposal__c newProposal = new Proposal__c(Account__c = acc.id, Borrower__c = con.id, Most_Recent_Loan__c = opp.id );
            String proposalId = customLookupControllerNew.saveProposalRecord(newProposal);

            customLookupControllerNew.LoanWrapper lw = customLookupControllerNew.getLoanDetails(opp.id);

		test.stopTest();        
    }
}