force-app/main/default/objects/Account/fields/Estimated_Value__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Value__c</fullName>
    <label>Estimated Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <description>This record type is used for Household or Individual accounts.</description>
    <label>Household</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label>Number of Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Occupancy__c.field-meta.xml
<CustomField>
    <fullName>Occupancy__c</fullName>
    <label>Occupancy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Properties__c/Properties__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Properties Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Properties__c/fields/Appraised_Value_of_Most_Recent_Closing__c.field-meta.xml
<CustomField>
    <fullName>Appraised_Value_of_Most_Recent_Closing__c</fullName>
    <formula>Appraised_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Appraised Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Days_Since_Most_Recent_Closing__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Most_Recent_Closing__c</fullName>
    <formula>today () - Most_Recent_Closing__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Closed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Estimated_Value__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Value__c</fullName>
    <label>Estimated Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Lender_of_Most_Recent_Closing__c.field-meta.xml
<CustomField>
    <fullName>Lender_of_Most_Recent_Closing__c</fullName>
    <formula>TEXT( Most_Recent_Closed_Opportunity__r.Lender__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lender</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Loan_Amt_with_MIP_of_Most_Recent_Closing__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amt_with_MIP_of_Most_Recent_Closing__c</fullName>
    <formula>Most_Recent_Closed_Opportunity__r.Loan_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan Amt with MIP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Loan_Program_of_Most_Recent_Closing__c.field-meta.xml
<CustomField>
    <fullName>Loan_Program_of_Most_Recent_Closing__c</fullName>
    <formula>TEXT( Most_Recent_Closed_Opportunity__r.Loan_Program__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/LTV_of_Most_Recent_Closing__c.field-meta.xml
<CustomField>
    <fullName>LTV_of_Most_Recent_Closing__c</fullName>
    <formula>Most_Recent_Closed_Opportunity__r.LTV__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LTV</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Most_Recent_Closing__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Closing__c</fullName>
    <description>This field will pull the close date from the most recently closed opportunity.</description>
    <formula>Most_Recent_Closed_Opportunity__r.CloseDate</formula>
    <label>Closed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label>Units</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Occupancy__c.field-meta.xml
<CustomField>
    <fullName>Occupancy__c</fullName>
    <label>Occupancy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Second</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Occupancy_of_Most_Recent_Closing__c.field-meta.xml
<CustomField>
    <fullName>Occupancy_of_Most_Recent_Closing__c</fullName>
    <formula>TEXT( Most_Recent_Closed_Opportunity__r.Occupancy__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Occupancy</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/PaymentAmount__c.field-meta.xml
<CustomField>
    <fullName>PaymentAmount__c</fullName>
    <formula>Most_Recent_Closed_Opportunity__r.Payment_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Detached</fullName>
                <default>true</default>
                <label>Detached</label>
            </value>
            <value>
                <fullName>Condominium</fullName>
                <label>Condo</label>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Detached Condominium</fullName>
            </value>
            <value>
                <fullName>Manufactured Home</fullName>
            </value>
            <value>
                <fullName>High Rise Condominium</fullName>
            </value>
            <value>
                <fullName>Modular/Pre-Fab</fullName>
            </value>
            <value>
                <fullName>Cooperative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Purchase_Price_of_Most_Recent_Closing__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Price_of_Most_Recent_Closing__c</fullName>
    <formula>Most_Recent_Closed_Opportunity__r.Purchase_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Purchase Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Purpose_of_Most_Recent_Closing__c.field-meta.xml
<CustomField>
    <fullName>Purpose_of_Most_Recent_Closing__c</fullName>
    <formula>TEXT( Most_Recent_Closed_Opportunity__r.Purpose__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Purpose</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Rate_of_Most_Recent_Closing__c.field-meta.xml
<CustomField>
    <fullName>Rate_of_Most_Recent_Closing__c</fullName>
    <formula>Most_Recent_Closed_Opportunity__r.Interest_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Scheduled_Balance_of_Most_Recent_Closing__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Balance_of_Most_Recent_Closing__c</fullName>
    <formula>Most_Recent_Closed_Opportunity__r.Current_Schedule_Balance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Scheduled Bal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Estimated_Value__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Value__c</fullName>
    <label>Est Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label>No Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Occupancy__c.field-meta.xml
<CustomField>
    <fullName>Occupancy__c</fullName>
    <label>Occupancy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScenariosTabController.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 08-12-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   04-03-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class ScenariosTabController {
    @AuraEnabled(cacheable=true)
    public static List<Properties__c> getPropertyList(Id conId) {
        Contact con = [SELECT Id, AccountId FROM Contact WHERE Id =:conId LIMIT 1];
        Account household = [SELECT Id FROM Account WHERE Id = :con.AccountId];
        
        return [SELECT Id, Name, Estimated_Value__c, Property_Type__c, Occupancy__c, 
        Number_of_Units__c FROM Properties__c WHERE Household__c= :household.Id];
    }

    @AuraEnabled
    public static Properties__c getPropertyDetails(Id recordId) {
        return [SELECT Id, Name, Estimated_Value__c, Property_Type__c, Number_of_Units__c, 
        Occupancy_of_Most_Recent_Closing__c, Purpose_of_Most_Recent_Closing__c, 
        Purchase_Price_of_Most_Recent_Closing__c, Appraised_Value_of_Most_Recent_Closing__c, 
        Loan_Amt_with_MIP_of_Most_Recent_Closing__c, LTV_of_Most_Recent_Closing__c, Most_Recent_Closing__c, 
        Days_Since_Most_Recent_Closing__c, Lender_of_Most_Recent_Closing__c, Loan_Program_of_Most_Recent_Closing__c, 
        Rate_of_Most_Recent_Closing__c, Scheduled_Balance_of_Most_Recent_Closing__c, PaymentAmount__c FROM Properties__c WHERE Id= :recordId];
    }

    @AuraEnabled
    public static String createProposalButtonMethod(Id recordId) {
        System.debug('@@@ createProposalButton: ' + recordId);

        Map<String, Object> myMap = new Map<String, Object>();
        myMap.put('Recordid', recordId);
        
        Flow.Interview.Lead_Contact_create_Proposal createProposalFlow = new Flow.Interview.Lead_Contact_create_Proposal(myMap);
        createProposalFlow.start();

        List<Proposal__c> proposalList = [SELECT Id FROM Proposal__c ORDER BY CreatedDate DESC LIMIT 1];

        System.debug('@@@ proposalId: ' + proposalList.get(0).Id);

        return proposalList.get(0).Id;
    }
}