force-app/main/default/objects/Account/fields/Estimated_Value__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Value__c</fullName>
    <label>Estimated Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Current_Program__c.field-meta.xml
<CustomField>
    <fullName>Current_Program__c</fullName>
    <label>Current Program</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Current_Rate__c.field-meta.xml
<CustomField>
    <fullName>Current_Rate__c</fullName>
    <label>Current Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label>Number of Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Occupancy__c.field-meta.xml
<CustomField>
    <fullName>Occupancy__c</fullName>
    <label>Occupancy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomNewContactContTest.cls
@isTest
public class CustomNewContactContTest {
    @isTest static void testMethod1(){
        Account newAccount = new Account();
        newAccount.Name='Test Account';
        insert newAccount;

        Contact newContact = new Contact();
        newContact.FirstName = 'Test';
        newContact.LastName = 'Contact';
        newContact.AccountId = newAccount.Id;
        newContact.Number_of_Units__c = '2';
        newContact.Occupancy__c = 'Primary';
        newContact.Estimated_Value__c = 700000;
        newContact.Current_Program__c = 'Test Program';
        newContact.Current_Balance__c = 60000;
        newContact.Current_Rate__c = 3.15;
        newContact.Current_Payment__c = 1435;                 
        
        Contact newContact2 = new Contact();
        newContact2.FirstName = 'Test2';
        newContact2.LastName = 'Contact';
        newContact2.AccountId = newAccount.Id;
        newContact2.Number_of_Units__c = '2';
        newContact2.Occupancy__c = 'Primary';
        newContact2.Estimated_Value__c = 700000;
        newContact2.Current_Program__c = 'Test Program';
        newContact2.Current_Balance__c = 60000;
        newContact2.Current_Rate__c = 3.15;
        newContact2.Current_Payment__c = 1435;

        Contact newContact3 = new Contact();
        
        test.startTest();
        List<String> stringIds = new List<String>();
        CustomNewContactCont.searchAccount('Test', stringIds, '');
        CustomNewContactCont.searchUser2('Test', stringIds, '');
        CustomNewContactCont.loadExistingUser2();
        CustomNewContactCont.getRecentlyCreatedAccount();
        CustomNewContactCont.saveContactOtherHelper(newContact, newAccount.Id);
        CustomNewContactCont.saveContactClientHelper(newContact2, newContact3);

        newContact.Id = null;
        newContact.AccountId = null;
        newContact2.Id = null;
        newContact2.AccountId = null;
        CustomNewContactCont.saveContactClientHelper(newContact2, newContact3);
        test.stopTest();
    }

}