force-app/main/default/objects/Account/fields/Estimated_Value__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Value__c</fullName>
    <label>Estimated Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Current_Program__c.field-meta.xml
<CustomField>
    <fullName>Current_Program__c</fullName>
    <label>Current Program</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Current_Rate__c.field-meta.xml
<CustomField>
    <fullName>Current_Rate__c</fullName>
    <label>Current Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label>Number of Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Occupancy__c.field-meta.xml
<CustomField>
    <fullName>Occupancy__c</fullName>
    <label>Occupancy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Subject_Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Subject_Property_Type__c</fullName>
    <label>Subject Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Detached</fullName>
            </value>
            <value>
                <fullName>Multi-Family</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Detached Condominium</fullName>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Manufactured Home</fullName>
            </value>
            <value>
                <fullName>High Rise Condominium</fullName>
            </value>
            <value>
                <fullName>Modular/Pre-Fab</fullName>
            </value>
            <value>
                <fullName>Cooperative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Current_Schedule_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Schedule_Balance__c</fullName>
    <description>This field will calculate the projected remaining balance on a loan based on the loan amount, close date, interest rate, and loan program.</description>
    <formula>If( OR(IsWon, IsPickVal(StageName, &apos;Closed Elsewhere&apos;)), Loan_Amount__c+((Loan_Amount__c- Payment_Amount__c *12/  Interest_Rate_SF__c  )*EXP(( 

IF(ISBLANK(First_Payment__c), 
(YEAR(TODAY())-YEAR(CloseDate))*12+MONTH(TODAY())-MONTH(CloseDate), 
(YEAR(TODAY())-YEAR(First_Payment__c))*12+MONTH(TODAY())-MONTH(First_Payment__c)+1) 

)*LN(1+Interest_Rate_SF__c/12))+Payment_Amount__c*12/Interest_Rate_SF__c )-(( Loan_Amount__c-Payment_Amount__c*12/Interest_Rate_SF__c)*EXP((1-1)*LN(1+Interest_Rate_SF__c/12))+Payment_Amount__c*12/Interest_Rate_SF__c ), null)</formula>
    <label>Scheduled Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>Salesforce Interest Rate</description>
    <label>Legacy Interest Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Program__c.field-meta.xml
<CustomField>
    <fullName>Loan_Program__c</fullName>
    <label>Loan Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CF30</fullName>
            </value>
            <value>
                <fullName>CF25</fullName>
            </value>
            <value>
                <fullName>CF20</fullName>
            </value>
            <value>
                <fullName>CF15</fullName>
            </value>
            <value>
                <fullName>CF10</fullName>
            </value>
            <value>
                <fullName>HB30</fullName>
            </value>
            <value>
                <fullName>HB25</fullName>
            </value>
            <value>
                <fullName>HB20</fullName>
            </value>
            <value>
                <fullName>HB15</fullName>
            </value>
            <value>
                <fullName>HB10</fullName>
            </value>
            <value>
                <fullName>JF30</fullName>
            </value>
            <value>
                <fullName>JF15</fullName>
            </value>
            <value>
                <fullName>FHA 30</fullName>
            </value>
            <value>
                <fullName>FHA 15</fullName>
            </value>
            <value>
                <fullName>VA 30</fullName>
            </value>
            <value>
                <fullName>VA 15</fullName>
            </value>
            <value>
                <fullName>C 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>FHA 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>VA 5-1 ARM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>This field will hold the payment amount for the loan.</description>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Est_Value__c.field-meta.xml
<CustomField>
    <fullName>Price_Est_Value__c</fullName>
    <label>Price / Est Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subject_Prop_No_Units__c.field-meta.xml
<CustomField>
    <fullName>Subject_Prop_No_Units__c</fullName>
    <formula>TEXT(Subject_Property_Name__r.Number_of_Units__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Num Units</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subject_Prop_Type__c.field-meta.xml
<CustomField>
    <fullName>Subject_Prop_Type__c</fullName>
    <formula>TEXT(Subject_Property_Name__r.Property_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subject Prop Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subject_Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Property_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject Property Name</label>
    <referenceTo>Properties__c</referenceTo>
    <relationshipLabel>Related Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Properties__c/Properties__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Properties Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Properties__c/fields/Estimated_Value__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Value__c</fullName>
    <label>Estimated Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Most_Recent_Closed_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Closed_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Most Recent Closed Loan</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Most Recent Closed Loan</relationshipLabel>
    <relationshipName>Most_Recent_Closed_Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label>Units</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Occupancy__c.field-meta.xml
<CustomField>
    <fullName>Occupancy__c</fullName>
    <label>Occupancy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Second</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_Street__c.field-meta.xml
<CustomField>
    <fullName>Property_Street__c</fullName>
    <label>Street</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/contactScenarioController.cls
public class contactScenarioController {
	@AuraEnabled
    public static List<Properties__c> hasActiveLoans(String recordId){
		Contact con = [SELECT AccountId FROM Contact WHERE Id =:recordId LIMIT 1];
        Account acct = [SELECT Id FROM Account WHERE Id = :con.AccountId LIMIT 1];
        List<Properties__c> props = [SELECT Id, Property_Street__c FROM Properties__c WHERE Household__c  =:acct.Id AND Most_Recent_Closed_Opportunity__c != null];
        if(props.size() != 0){
            return props;
        }        
        else {
            return null;
        }       
    }

    @AuraEnabled
    public static void updateLoanDetails(String contactId, String propId){
        Contact con = [SELECT AccountId, Number_of_Units__c,Occupancy__c, Estimated_Value__c,Current_Program__c,Current_Balance__c,Current_Rate__c,Current_Payment__c 
                       FROM Contact 
                       WHERE Id =: contactId 
                       LIMIT 1];
        
        Account acct = [SELECT Id FROM Account WHERE Id =: con.AccountId LIMIT 1];
        Properties__c prop = [SELECT Id FROM Properties__c WHERE Household__c =: acct.Id LIMIT 1];
        
        Opportunity opp = [SELECT Occupancy__c,Subject_Prop_Type__c,Subject_Prop_No_Units__c,Loan_Program__c,Current_Schedule_Balance__c,Interest_Rate__c,Payment_Amount__c,Price_Est_Value__c
                          FROM Opportunity 
                          WHERE Subject_Property_Name__c = :prop.Id LIMIT 1];
        
        con.Number_of_Units__c = opp.Subject_Prop_No_Units__c;
        con.Subject_Property_Type__c = opp.Subject_Prop_Type__c;
        con.Occupancy__c = opp.Occupancy__c;
        con.Current_Program__c = opp.Loan_Program__c;
        con.Current_Balance__c = opp.Current_Schedule_Balance__c;
        con.Current_Rate__c = opp.Interest_Rate__c;
        con.Current_Payment__c = opp.Payment_Amount__c;
        con.Estimated_Value__c = opp.Price_Est_Value__c;
        update con;
    }  
}