force-app/main/default/objects/Account/fields/Household_Status__c.field-meta.xml
<CustomField>
    <fullName>Household_Status__c</fullName>
    <label>Household Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Fired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Preferred Partner</fullName>
            </value>
            <value>
                <fullName>Fired</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
                <isActive>false</isActive>
                <label>Lead</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateContactsStatusTest.cls
@isTest
public class UpdateContactsStatusTest 
{
    public static testmethod void SetupTestData(){
        Account acc = new Account();
        acc.Household_Status__c = 'Inactive';
        acc.Name = 'Test Account 1';
        insert acc;
        
        Contact con1 = new Contact();
        con1.FirstName = 'Michelle';
        con1.LastName = 'Murphy';
        con1.AccountId = acc.Id;
        con1.Contact_Status__c = 'Inactive';
        insert con1;
        
        Contact con2 = new Contact();
        con2.FirstName = 'Susan';
        con2.LastName = 'Davis';
        con2.AccountId = acc.Id;
        con2.Contact_Status__c = 'Inactive';
        insert con2;     
        
        Test.startTest();
        acc.Household_Status__c= 'Fired';
        update acc;
        Test.stopTest();
    }
}