force-app/main/default/objects/Account/fields/Loan_Originator_User__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Originator User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Originator_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>This record type is used for Company or Business accounts.</description>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Future_Activities__c.field-meta.xml
<CustomField>
    <fullName>Future_Activities__c</fullName>
    <formula>Future_Events__c + Future_Tasks__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Future Activities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Loan_Originator_User__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Originator User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LO_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
                <default>true</default>
                <label>Client</label>
            </value>
            <value>
                <fullName>Realtor</fullName>
            </value>
            <value>
                <fullName>Escrow Officer</fullName>
            </value>
            <value>
                <fullName>Lender AE</fullName>
            </value>
            <value>
                <fullName>Insurance Agent</fullName>
            </value>
            <value>
                <fullName>Lender_Ops</fullName>
                <label>Lender - Ops</label>
            </value>
            <value>
                <fullName>Financial Advisor</fullName>
                <label>Financial Advisor / Planner</label>
            </value>
            <value>
                <fullName>Referral Partner - Other</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Loan Originator / Broker</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Prospective LO</fullName>
            </value>
            <value>
                <fullName>Prospective TM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/COE__c.field-meta.xml
<CustomField>
    <fullName>COE__c</fullName>
    <label>COE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Future_Activities__c.field-meta.xml
<CustomField>
    <fullName>Future_Activities__c</fullName>
    <formula>Future_Tasks__c + Future_Events__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Future Activities</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Loan_Originator_User__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Originator User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LO_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Client&apos;</defaultValue>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
                <default>true</default>
                <label>Client</label>
            </value>
            <value>
                <fullName>Escrow Officer</fullName>
            </value>
            <value>
                <fullName>Lender</fullName>
            </value>
            <value>
                <fullName>Insurance Agent</fullName>
            </value>
            <value>
                <fullName>Financial Advisor</fullName>
            </value>
            <value>
                <fullName>Referral Partner - Other</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/COE__c.field-meta.xml
<CustomField>
    <fullName>COE__c</fullName>
    <label>COE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Future_Activities__c.field-meta.xml
<CustomField>
    <fullName>Future_Activities__c</fullName>
    <description>This field will hold the number of upcoming (open) Activities for the Opportunity.</description>
    <label>Future Activities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Anniversary_Date__c</fullName>
    <description>This hidden field will store the actual date of the loan anniversary and is used in report filtering, but is not displayed in the UI.</description>
    <formula>IF(IsWon, 
 
IF( 
AND(DAY(CloseDate)=29, MONTH(CloseDate)=2), 
IF(DATE(YEAR(TODAY()), 3,1)&gt;= TODAY(), DATE(YEAR(TODAY()),3,1), DATE(YEAR(TODAY())+1,3,1)), 


IF(DATE(YEAR(TODAY()), MONTH(CloseDate), DAY(CloseDate))&gt;= TODAY(), 
DATE(YEAR(TODAY()), MONTH(CloseDate), DAY(CloseDate)), 
DATE(YEAR(TODAY())+1, MONTH(CloseDate), DAY(CloseDate))) 

) 

,
null
)</formula>
    <label>Loan Anniversary Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Originator_User__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Originator User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loans_Originated</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Processor_User__c.field-meta.xml
<CustomField>
    <fullName>Loan_Processor_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Processor User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loans_Processed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lock_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Lock_Expiration__c</fullName>
    <label>Lock Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Property_County__c.field-meta.xml
<CustomField>
    <fullName>Property_County__c</fullName>
    <label>Property County</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Closed.recordType-meta.xml
<RecordType>
    <fullName>Closed</fullName>
    <active>true</active>
    <businessProcess>Encompass Active</businessProcess>
    <label>Closed</label>
</RecordType>

force-app/main/default/objects/Properties__c/Properties__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Properties Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Properties__c/fields/Loan_Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Anniversary_Date__c</fullName>
    <formula>Most_Recent_Closed_Opportunity__r.Loan_Anniversary_Date__c</formula>
    <label>Loan Anniversary Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Most_Recent_Closed_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Closed_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Most Recent Closed Loan</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Most Recent Closed Loan</relationshipLabel>
    <relationshipName>Most_Recent_Closed_Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_City__c.field-meta.xml
<CustomField>
    <fullName>Property_City__c</fullName>
    <label>City</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_County__c.field-meta.xml
<CustomField>
    <fullName>Property_County__c</fullName>
    <label>County</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_State__c.field-meta.xml
<CustomField>
    <fullName>Property_State__c</fullName>
    <label>State</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_Street__c.field-meta.xml
<CustomField>
    <fullName>Property_Street__c</fullName>
    <label>Street</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Detached</fullName>
                <default>true</default>
                <label>Detached</label>
            </value>
            <value>
                <fullName>Condominium</fullName>
                <label>Condo</label>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Detached Condominium</fullName>
            </value>
            <value>
                <fullName>Manufactured Home</fullName>
            </value>
            <value>
                <fullName>High Rise Condominium</fullName>
            </value>
            <value>
                <fullName>Modular/Pre-Fab</fullName>
            </value>
            <value>
                <fullName>Cooperative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_Zip__c.field-meta.xml
<CustomField>
    <fullName>Property_Zip__c</fullName>
    <label>Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TaskCreator_Test.cls
/*
 * Description: Apex test class for the batch task creation and scheduler classes.
 *
 *  Author              Date                    Change History
 *  ----------          ----------              --------------------
 *  PAW.                2018-04-08              Created
 *  PAW					2018-09-22				Removed reference to custom fields Last_Activity_Date__c */

@isTest
public class TaskCreator_Test {

    //This method will stage all appropriate test data
    @testSetup
    static void stageTestData() {
        
        
        User OwnerUser = new User(Firstname='Test',lastname='Owner', Email = 'test@test.com', Username = 'testowner@solidfy.com.dev', alias = 'town', profileid = '00ef4000001B3XBAA0', TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US', EmailEncodingKey = 'ISO-8859-1', LanguageLocaleKey = 'en_US');
        insert OwnerUser;
        User ProcessorUser = new User(Firstname='Test',lastname='Processor', Email = 'test@test.com', Username = 'testprocessor@solidfy.com.dev', alias = 'tproc', profileid = '00ef4000001B3XBAA0', TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US', EmailEncodingKey = 'ISO-8859-1', LanguageLocaleKey = 'en_US');
        insert ProcessorUser;
        User LOUser = new User(Firstname='Test',lastname='LO', Email = 'test@test.com', Username = 'testloanofficer@solidfy.com.dev', alias = 'tloff', profileid = '00ef4000001B3XBAA0', TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US', EmailEncodingKey = 'ISO-8859-1', LanguageLocaleKey = 'en_US');
        insert LOUser;
        
        Account newAcct = new Account(Name='Test', Ownerid = OwnerUser.Id, Loan_Originator_User__c = LOUser.Id);
        insert newAcct;
        
        Date currentDate = Date.today().addDays(30);
        Date bDate = Date.newInstance(1962, currentDate.Month(), currentDate.Day());
        system.debug('birthdate: ' + bDate);
        
        Contact cont = new Contact(FirstName='Test',LastName='Tester', AccountId=newAcct.Id, Birthdate = bDate);
        Contact cont2 = new Contact(FirstName='Test',LastName='Tester2', AccountId=newAcct.Id, Birthdate = bDate.addDays(-4) );
        Contact cont3 = new Contact(FirstName='Test',LastName='Tester3', AccountId=newAcct.Id, Type__c = 'Client');
        insert cont;
        insert cont2;
        insert cont3;
        
        
        Task task3 = new Task(Subject='Test', ActivityDate = currentdate.addDays(-90), whoId = cont3.id, ownerId = ownerUser.id, status = 'Completed');
        insert task3;
        
        Lead ld = new Lead(FirstName = 'Test', LastName = 'Tester', Company = 'Test', status = 'Attempted');
        insert ld;
        
        Task ldTask = new Task(Subject = 'Test', ActivityDate = currentDate.AddDays(-3), whoId = ld.id, ownerId = OwnerUser.id, status = 'Completed');
        insert ldTask;

        
        List<Opportunity> testOpps = new List<Opportunity>();
        List<Task> testTasks = new List<Task>();
        
        Opportunity testOpp1 = new Opportunity(Name='TBD Last Activity 45d, future scheduled', StageName='Analysis / TBD', CloseDate=System.Today(),
                                               AccountId=newAcct.Id, Future_Activities__c = 2, 
                                               OwnerId=OwnerUser.Id, Loan_Originator_User__c = LOUser.id, Loan_Processor_User__c=ProcessorUser.Id);
        testOpps.add(testOpp1);
        Task testOpp1Task =new Task(Subject = 'Test', ActivityDate = Date.Today().AddDays(-45), whoId = ld.id, ownerId = OwnerUser.id, status = 'Completed');
		testTasks.add(testOpp1Task);
        
        Opportunity testOpp2 = new Opportunity(Name='TBD Last Activity 45 Days', StageName='Analysis / TBD', CloseDate=System.Today().addDays(15),
                                               AccountId=newAcct.Id, OwnerId=OwnerUser.Id, 
                                               Loan_Originator_User__c = LOUser.id, Loan_Processor_User__c=ProcessorUser.Id);
        testOpps.add(testOpp2);
        Task testOpp2Task =new Task(Subject = 'Test', ActivityDate = Date.Today().AddDays(-45), whoId = ld.id, ownerId = OwnerUser.id, status = 'Completed');
		testTasks.add(testOpp2Task);
        Opportunity testOpp3 = new Opportunity(Name='Processing Last Activity 1d',StageName='Application',CloseDate=System.Today().addDays(11),
                                               AccountId=newAcct.Id,
                                               OwnerId=OwnerUser.Id, Loan_Originator_User__c = LOUser.id, Loan_Processor_User__c=ProcessorUser.Id);
        testOpps.add(testOpp3);
        Task testOpp3Task =new Task(Subject = 'Test', ActivityDate = Date.Today().AddDays(-1), whoId = ld.id, ownerId = OwnerUser.id, status = 'Completed');
		testTasks.add(testOpp3Task);
        Opportunity testOpp4 = new Opportunity(Name='Processing Last Activity 1d, future scheduled',StageName='Application',CloseDate=System.Today().addDays(15),
                                               AccountId=newAcct.Id, Future_Activities__c = 1,
                                               OwnerId=OwnerUser.Id, Loan_Originator_User__c = LOUser.id, Loan_Processor_User__c=ProcessorUser.Id);
        testOpps.add(testOpp4);
        Task testOpp4Task =new Task(Subject = 'Test', ActivityDate = Date.Today().AddDays(-1), whoId = ld.id, ownerId = OwnerUser.id, status = 'Completed');
		testTasks.add(testOpp4Task);
        Opportunity testOpp5 = new Opportunity(Name='Closed Lost',StageName='Closed Lost',CloseDate=System.Today().AddDays(-45),AccountId=newAcct.Id, 
                                               OwnerId=OwnerUser.Id, Loan_Originator_User__c = LOUser.id, Loan_Processor_User__c=ProcessorUser.Id);
        testOpps.add(testOpp5);
        
        //create loan with close date = saturday for test only query

        
        Opportunity testOpp6 = new Opportunity(Name='Weekend Close',StageName='Application',CloseDate=System.Today(),AccountId=newAcct.Id, 
                                               OwnerId=OwnerUser.Id, Loan_Originator_User__c = LOUser.id, Loan_Processor_User__c=ProcessorUser.Id);
        testOpps.add(testOpp6);
       
        
        
        //anniversary date for loan = 30 days from today.  
        Date cDate = Date.newInstance((Date.Today().AddDays(30).Year() - 1), Date.Today().AddDays(30).Month(), Date.Today().AddDays(30).Day());
        system.debug ('loan anniversary date:' + cDate);
          
        Opportunity testOpp8 = new Opportunity(Name='Loan Anniversary Today',StageName='Closed Won',CloseDate=cDate,AccountId=newAcct.Id, 
                                               OwnerId=OwnerUser.Id, Loan_Originator_User__c = LOUser.id, Loan_Processor_User__c=ProcessorUser.Id);
        testOpps.add(testOpp8);
        
        Opportunity testOpp9 = new Opportunity(Name='Lock Expiration',StageName='Application', Lock_Expiration__c = System.Today(), CloseDate=System.Today(),AccountId=newAcct.Id, 
                                               OwnerId=OwnerUser.Id, Loan_Originator_User__c = LOUser.id, Loan_Processor_User__c=ProcessorUser.Id);
        testOpps.add(testOpp9);
        Opportunity testOpp10 = new Opportunity(Name='COE Two Weeks',StageName='Application', COE__c = System.Today().AddDays(14), CloseDate=System.Today(),AccountId=newAcct.Id, 
                                               OwnerId=OwnerUser.Id, Loan_Originator_User__c = LOUser.id, Loan_Processor_User__c=ProcessorUser.Id);
        testOpps.add(testOpp10);
        
        insert testOpps;
        insert testTasks;
        
        List<Opportunity> newlist = [Select Id, Name, StageName, CloseDate, LastActivityDate, Future_Activities__c, Loan_Anniversary_Date__c, Loan_Processor_User__c, IsClosed from Opportunity];
        system.debug(newlist);

        
        OpportunityContactRole testOCR1 = new OpportunityContactRole(ContactId=cont.Id,OpportunityId=testOpp8.Id,Role='Borrower');
        insert testOCR1;   
		OpportunityContactRole testOCR2 = new OpportunityContactRole(ContactId=cont.Id,OpportunityId=testOpp1.Id,Role='Borrower');
        insert testOCR2;   

        Properties__c newProperty = new Properties__c(Name='Test Property',Property_Street__c='123 Test',Property_City__c='Test',Property_State__c='MI',
          Property_Zip__c='48187',Property_County__c='Wayne',Property_Type__c='Detached',Most_Recent_Closed_Opportunity__c=testOpp8.Id, OwnerId=OwnerUser.Id);

        insert newProperty;
    }
    

    
    //Confirm behavior for Loan Check-in Reminder 24h
       testMethod static void testCreateLoanCheckinTasks() {
        test.startTest();
        
        database.executeBatch(new TaskCreator('Loan Check-in 24h'));

        test.stopTest();
        //General Opportunity Task Creation OK
        string id4 = [Select id from Opportunity where Name = 'Processing Last Activity 1d, future scheduled' LIMIT 1].Id;
        string id3 = [Select id from Opportunity where Name = 'Processing Last Activity 1d' LIMIT 1].Id;
        System.assert([Select Id from Task WHERE What.ID = :id3].size()>=0);           
		System.assert([Select Id from Task WHERE What.ID = :id4].size()==0);
       }
    
     //Confirm behavior for TBD Loan Check-in Reminder 45d
       testMethod static void testCreateTBDLoanCheckinTasks() {
        test.startTest();
        
        database.executeBatch(new TaskCreator('TBD Loan Check-in Reminder 45d'));

        test.stopTest();
        //General Opportunity Task Creation OK
        string id1 = [Select id from Opportunity where Name = 'TBD Last Activity 45d, future scheduled' LIMIT 1].Id;
        string id2 = [Select id from Opportunity where Name = 'TBD Last Activity 45 Days' LIMIT 1].Id;
           
        System.assert([Select Id from Task WHERE What.ID = :id2].size()>=0);           
		System.assert([Select Id from Task WHERE What.ID = :id1].size()==0);
           
       }
		
    //Confirm behavior for Loan Anniversary
       testMethod static void testLoanAnniversaryTasks() {
        test.startTest();
        
        database.executeBatch(new TaskCreator('Loan Anniversary'));
        database.executeBatch(new TaskCreator('Loan Anniversary Next 30d'));

        test.stopTest();
        //General Opportunity Task Creation OK
        
        System.assert([Select Id from Task WHERE Subject = 'Loan Anniversary Followup'].size()>=0);           
  
       }
    
      //Confirm behavior for Birthday
       testMethod static void testBirthdayTasks() {
        test.startTest();
        
        database.executeBatch(new TaskCreator('Birthday Follow-up'));
        database.executeBatch(new TaskCreator('Birthdays Next 30d'));

        test.stopTest();
        //General Opportunity Task Creation OK
        
        System.assert([Select Id from Task WHERE Subject = 'Birthday Follow-up'].size()>=0);           
  
       }

		//Confirm behavior for Contact
       	testMethod static void testContactTasks() {
        test.startTest();
        
        database.executeBatch(new TaskCreator('No Client Contact 6mo'));

        test.stopTest();
        //General Opportunity Task Creation OK
        
        System.assert([Select Id from Task WHERE Subject = 'No Client Contact 6mo'].size()>=0);           
  
       }

        //Confirm behavior for Lead
       	testMethod static void testLeadTasks() {
        test.startTest();
        
        database.executeBatch(new TaskCreator('Lead Followup Task'));

        test.stopTest();
        //General Opportunity Task Creation OK
        
        System.assert([Select Id from Task WHERE Subject = 'Lead Followup Task'].size()>=0);           
  
       }

    
      //Confirm behavior for Loan Lock Expiration and COE
       	testMethod static void testLoanCriticalDates() {
        test.startTest();
        
        database.executeBatch(new TaskCreator('Loan Two Weeks from COE - LO'));
        database.executeBatch(new TaskCreator('Loan Two Weeks from COE - Processor'));
        database.executeBatch(new TaskCreator('Loan Lock Expires - LO'));
        database.executeBatch(new TaskCreator('Loan Lock Expires - Processor'));
            
        test.stopTest();
        //General Opportunity Task Creation OK
       
        System.assert([Select Id from Task WHERE Subject = 'Loan Two Weeks from COE - LO'].size()>=0);           
  		System.assert([Select Id from Task WHERE Subject = 'Loan Two Weeks from COE - Loan Processor'].size()>=0); 
        System.assert([Select Id from Task WHERE Subject = 'Loan Lock Expires - LO'].size()>=0); 
        System.assert([Select Id from Task WHERE Subject = 'Loan Lock Expires - Loan Processor'].size()>=0); 
            
       }

    
		testMethod static void testWeekendTask() {
        	test.startTest();
        
        database.executeBatch(new TaskCreator('TestOnly'));

        test.stopTest();	    
            
        //Saturday Date task is moved to Monday
        system.debug('Todays Day of week: ' + String.valueof(System.now().format('EEE')));
        Task satTask = [Select Id, ActivityDate from Task where Subject = 'TestOnly' LIMIT 1];
        DateTime checkDate = Datetime.newInstance(satTask.ActivityDate, Time.newInstance(12,0,0,0));
        String dow = String.valueOf(checkDate.format('EEE'));
            system.debug(dow);
   //     System.assert(dow=='Mon');
    
    } 
    
    //confirm behavior for scheduler
    testMethod static void testScheduler() {
        
        test.startTest();
        
        TaskBatchScheduler batch = new TaskBatchScheduler('TBD Loan Check-in Reminder 45d');
        String sch = '0 0 6 * * ?';
        System.schedule('TBD Loan Check-in Reminder 45d', sch, batch);
        
        test.stopTest();
        
    } 
    


 
}