force-app/main/default/objects/Account/fields/Loan_Originator_User__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Originator User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Originator_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Future_Activities__c.field-meta.xml
<CustomField>
    <fullName>Future_Activities__c</fullName>
    <formula>Future_Events__c + Future_Tasks__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Future Activities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Loan_Originator_User__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Originator User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LO_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Next_Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Next_Birthdate__c</fullName>
    <description>This field will be used to compute the next birthdate for a contact to be used in report filtering but not available on the UI.</description>
    <formula>IF(ISBLANK(Birthdate), 
 null,
 IF(
   AND(DAY(Birthdate)=29, MONTH(Birthdate)=2),
   IF(DATE(YEAR(TODAY()), 3,1)&gt;= TODAY(), DATE(YEAR(TODAY()),3,1), DATE(YEAR(TODAY())+1,3,1)),


   IF(DATE(YEAR(TODAY()), MONTH(Birthdate), DAY(Birthdate))&gt;= TODAY(),
   DATE(YEAR(TODAY()), MONTH(Birthdate), DAY(Birthdate)),
   DATE(YEAR(TODAY())+1, MONTH(Birthdate), DAY(Birthdate)))
 
)
)</formula>
    <label>Next Birthdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Future_Activities__c.field-meta.xml
<CustomField>
    <fullName>Future_Activities__c</fullName>
    <formula>Future_Tasks__c + Future_Events__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Future Activities</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Loan_Originator_User__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Originator User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LO_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Future_Activities__c.field-meta.xml
<CustomField>
    <fullName>Future_Activities__c</fullName>
    <description>This field will hold the number of upcoming (open) Activities for the Opportunity.</description>
    <label>Future Activities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Anniversary_Date__c</fullName>
    <description>This hidden field will store the actual date of the loan anniversary and is used in report filtering, but is not displayed in the UI.</description>
    <formula>IF(IsWon, 
 
IF( 
AND(DAY(CloseDate)=29, MONTH(CloseDate)=2), 
IF(DATE(YEAR(TODAY()), 3,1)&gt;= TODAY(), DATE(YEAR(TODAY()),3,1), DATE(YEAR(TODAY())+1,3,1)), 


IF(DATE(YEAR(TODAY()), MONTH(CloseDate), DAY(CloseDate))&gt;= TODAY(), 
DATE(YEAR(TODAY()), MONTH(CloseDate), DAY(CloseDate)), 
DATE(YEAR(TODAY())+1, MONTH(CloseDate), DAY(CloseDate))) 

) 

,
null
)</formula>
    <label>Loan Anniversary Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Originator_User__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Originator User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loans_Originated</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Processor_User__c.field-meta.xml
<CustomField>
    <fullName>Loan_Processor_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Processor User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loans_Processed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Property_County__c.field-meta.xml
<CustomField>
    <fullName>Property_County__c</fullName>
    <label>Property County</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Closed.recordType-meta.xml
<RecordType>
    <fullName>Closed</fullName>
    <active>true</active>
    <businessProcess>Encompass Active</businessProcess>
    <label>Closed</label>
</RecordType>

force-app/main/default/objects/Properties__c/Properties__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Properties Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Properties__c/fields/Loan_Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Anniversary_Date__c</fullName>
    <formula>Most_Recent_Closed_Opportunity__r.Loan_Anniversary_Date__c</formula>
    <label>Loan Anniversary Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Most_Recent_Closed_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Closed_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Most Recent Closed Loan</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Most Recent Closed Loan</relationshipLabel>
    <relationshipName>Most_Recent_Closed_Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_City__c.field-meta.xml
<CustomField>
    <fullName>Property_City__c</fullName>
    <label>City</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_County__c.field-meta.xml
<CustomField>
    <fullName>Property_County__c</fullName>
    <label>County</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_State__c.field-meta.xml
<CustomField>
    <fullName>Property_State__c</fullName>
    <label>State</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_Street__c.field-meta.xml
<CustomField>
    <fullName>Property_Street__c</fullName>
    <label>Street</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Detached</fullName>
                <default>true</default>
                <label>Detached</label>
            </value>
            <value>
                <fullName>Condominium</fullName>
                <label>Condo</label>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Detached Condominium</fullName>
            </value>
            <value>
                <fullName>Manufactured Home</fullName>
            </value>
            <value>
                <fullName>High Rise Condominium</fullName>
            </value>
            <value>
                <fullName>Modular/Pre-Fab</fullName>
            </value>
            <value>
                <fullName>Cooperative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_Zip__c.field-meta.xml
<CustomField>
    <fullName>Property_Zip__c</fullName>
    <label>Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Creation__c/Task_Creation__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting will be used to store criteria for task creation on different objects.</description>
    <label>Task Creation</label>
</CustomObject>

force-app/main/default/objects/Task_Creation__c/fields/Date_Filter_Operator__c.field-meta.xml
<CustomField>
    <fullName>Date_Filter_Operator__c</fullName>
    <description>This field will hold the operator for the date filter (&lt;, &gt;, =, &lt;=, &gt;=).</description>
    <inlineHelpText>Filters based on the date and date filter fields. Values are &lt;, &gt;, =, &lt;=, &gt;=.</inlineHelpText>
    <label>Date Filter Operator</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Creation__c/fields/Date_Range_Filter__c.field-meta.xml
<CustomField>
    <fullName>Date_Range_Filter__c</fullName>
    <description>This field will hold the date range filter for the field in the Field API Name text box.  0 is Today.</description>
    <inlineHelpText>Number of days from today (0 means today, 5 means 5 days from today, -5 means 5 days ago, etc).</inlineHelpText>
    <label>Date Range Filter</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Creation__c/fields/Due_In__c.field-meta.xml
<CustomField>
    <fullName>Due_In__c</fullName>
    <description>This field will hold what day the task should be due in. 0 = same day.</description>
    <inlineHelpText>Day this task is due. 0 = due the same day it is created.</inlineHelpText>
    <label>Due In</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Creation__c/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <description>This field will hold the API  name of the field that has a date in it.  That date will be compared against other criteria on this setting to determine if a task should be created.</description>
    <inlineHelpText>Date field on the object to compare against the date filter.</inlineHelpText>
    <label>Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Creation__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>This field will hold the API name of the object in the &apos;Related To&apos; (or What) portion of the Task.  Custom objects will end with __c.</description>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Creation__c/fields/Task_Name__c.field-meta.xml
<CustomField>
    <fullName>Task_Name__c</fullName>
    <description>This field will hold the subject (name) of the task being created.</description>
    <label>Task Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DateBatchTaskCreation_Test.cls
/*
 * Description: Apex test class for the batch task creation and scheduler classes.
 *
 *  Author              Date                    Change History
 *  ----------          ----------              --------------------
 *  P.S.                2017-12-11              Created
 *  P.S.                2017-12-15              Added support for WhoId on Properties__c tasks
 *  P.S.                2018-01-06              Added support for Last Activity Date and necessary tests
 * */
@isTest
public class DateBatchTaskCreation_Test {

    //This method will stage all appropriate test data including custom settings and needed records
    @testSetup
    static void stageTestData() {
        
        List<Task_Creation__c> taskSettings = new List<Task_Creation__c>();
        
       
        Integer taskDueDate;
        DateTime testDateTime = System.now();
        String dueDayOfWeek = String.valueOf(testDateTime.format('EEE', 'America/Los_Angeles'));
        system.debug ('day of Week:' + dueDayofWeek);
        if (dueDayOfWeek=='Sun') {taskDueDate = -1;}
        if (dueDayOfWeek=='Mon') {taskDueDate = 5;}
        if (dueDayOfWeek=='Tue') {taskDueDate = 4;}
        if (dueDayOfWeek=='Wed') {taskDueDate = 3;}
        if (dueDayOfWeek=='Thu') {taskDueDate = 2;}
        if (dueDayOfWeek=='Fri') {taskDueDate = 1;}
        if (dueDayOfWeek=='Sat') {taskDueDate = 0;}
        
        Task_Creation__c tc6 = new Task_Creation__c(Name='Opp MC Sat Due Date Close Today',Object_API_Name__c='Opportunity',
                                                  Field_API_Name__c='CloseDate',Task_Name__c='O6',
                                                  Date_Filter_Operator__c='=',Date_Range_Filter__c=0,
                                                  Due_In__c=taskDueDate);
        taskSettings.add(tc6);
        
               Task_Creation__c tc9 = new Task_Creation__c(Name='Property task',Object_API_Name__c='Properties__c',
                                                  Field_API_Name__c='CreatedDate',Task_Name__c='P2',
                                                  Date_Filter_Operator__c='=',Date_Range_Filter__c=0,
                                                  Due_In__c=0);
        taskSettings.add(tc9);
        
        Task_Creation__c tc10 = new Task_Creation__c(Name='Contact Task',Object_API_Name__c='Contact',
                                                  Field_API_Name__c='Next_Birthdate__c',Task_Name__c='C1',
                                                  Date_Filter_Operator__c='=',Date_Range_Filter__c=0,
                                                  Due_In__c=0);
        taskSettings.add(tc10);


        insert taskSettings;
        
        User OwnerUser = new User(Firstname='Test',lastname='Owner', Email = 'test@test.com', Username = 'testowner@solidfy.com.dev', alias = 'town', profileid = '00ef4000001B3XBAA0', TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US', EmailEncodingKey = 'ISO-8859-1', LanguageLocaleKey = 'en_US');
        insert OwnerUser;
        User ProcessorUser = new User(Firstname='Test',lastname='Processor', Email = 'test@test.com', Username = 'testprocessor@solidfy.com.dev', alias = 'tproc', profileid = '00ef4000001B3XBAA0', TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US', EmailEncodingKey = 'ISO-8859-1', LanguageLocaleKey = 'en_US');
        insert ProcessorUser;
        User LOUser = new User(Firstname='Test',lastname='LO', Email = 'test@test.com', Username = 'testloanofficer@solidfy.com.dev', alias = 'tloff', profileid = '00ef4000001B3XBAA0', TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US', EmailEncodingKey = 'ISO-8859-1', LanguageLocaleKey = 'en_US');
        insert LOUser;
        
        Account newAcct = new Account(Name='Test', Ownerid = OwnerUser.Id, Loan_Originator_User__c = LOUser.Id);
        insert newAcct;
        
        Date currentDate = Date.today();
        Date bDate = Date.newInstance(1962, currentDate.Month(), currentDate.Day());
        system.debug('birthdate: ' + bDate);
        
        Contact cont = new Contact(FirstName='Test',LastName='Tester', AccountId=newAcct.Id, Birthdate = bDate);
        insert cont;
        
        List<Opportunity> testOpps = new List<Opportunity>();
        
        Opportunity testOpp1 = new Opportunity(Name='Open, Close Date Today',StageName='Analysis / TBD',CloseDate=System.Today(),AccountId=newAcct.Id, OwnerId=OwnerUser.Id, Loan_Originator_User__c = LOUser.id, Loan_Processor_User__c=ProcessorUser.Id);
        testOpps.add(testOpp1);
        Opportunity testOpp2 = new Opportunity(Name='Open, Close Date Future',StageName='Analysis / TBD',CloseDate=System.Today().addDays(15),AccountId=newAcct.Id, OwnerId=OwnerUser.Id, Loan_Originator_User__c = LOUser.id, Loan_Processor_User__c=ProcessorUser.Id);
        testOpps.add(testOpp2);
        Opportunity testOpp3 = new Opportunity(Name='Closed, Close Date Future',StageName='Closed Won',CloseDate=System.Today().addDays(11),AccountId=newAcct.Id, OwnerId=OwnerUser.Id, Loan_Originator_User__c = LOUser.id, Loan_Processor_User__c=ProcessorUser.Id);
        testOpps.add(testOpp3);
        Opportunity testOpp4 = new Opportunity(Name='Closed, Close Date Past',StageName='Closed Won',CloseDate=System.Today().addDays(-10),AccountId=newAcct.Id, OwnerId=OwnerUser.Id, Loan_Originator_User__c = LOUser.id, Loan_Processor_User__c=ProcessorUser.Id);
        testOpps.add(testOpp4);
        Opportunity testOpp5 = new Opportunity(Name='Closed Lost, No Future Task',StageName='Closed Lost',CloseDate=System.Today(),AccountId=newAcct.Id, OwnerId=OwnerUser.Id, Loan_Originator_User__c = LOUser.id, Loan_Processor_User__c=ProcessorUser.Id);
        testOpps.add(testOpp5);
        Opportunity testOpp6 = new Opportunity(Name='Closed Lost, Future Task',StageName='Closed Lost',CloseDate=System.Today(),AccountId=newAcct.Id, OwnerId=OwnerUser.Id, Loan_Originator_User__c = LOUser.id, Loan_Processor_User__c=ProcessorUser.Id, type = 'Client');
        testOpps.add(testOpp6);   
        Opportunity testOpp7 = new Opportunity(Name='Open, Close Date Today',StageName='Analysis / TBD',CloseDate=System.Today(),AccountId=newAcct.Id, OwnerId=OwnerUser.Id, Loan_Originator_User__c = LOUser.id, Loan_Processor_User__c=ProcessorUser.Id, Type = 'Client');
        testOpps.add(testOpp7);
        Opportunity testOpp9 = new Opportunity(Name='Closed Won, Future Task',StageName='Closed Won',CloseDate=System.Today(),AccountId=newAcct.Id, OwnerId=OwnerUser.Id, Loan_Originator_User__c = LOUser.id, Loan_Processor_User__c=ProcessorUser.Id, type = 'Client');
        testOpps.add(testOpp9);   
        
        
        //anniversary date for loan = today.  don't run test on a leap day 
        Date cDate = Date.newInstance((Date.Today().Year() - 1), Date.Today().Month(), Date.Today().Day());
        system.debug ('loan anniversary date:' + cDate);
          
        Opportunity testOpp8 = new Opportunity(Name='Loan Anniversary Today',StageName='Closed Won',CloseDate=cDate,AccountId=newAcct.Id, OwnerId=OwnerUser.Id, Loan_Originator_User__c = LOUser.id, Loan_Processor_User__c=ProcessorUser.Id);
        testOpps.add(testOpp8);
        insert testOpps;
        
        //damn workflow rules change my opp close dates and fail the freaking tests
        testOpp1.CloseDate = System.today();
        update testOpp1;
        testOpp8.CloseDate = cDate;
        update testOpp8;
        //set future task on Opp6
        testOpp6.Future_Activities__c = 1;
        update testOpp6;

        List<Opportunity> newlist = [Select Id, Name, StageName, CloseDate, Future_Activities__c, Loan_Anniversary_Date__c, Loan_Processor_User__c, IsClosed from Opportunity];
        system.debug(newlist);
        
        OpportunityContactRole testOCR1 = new OpportunityContactRole(ContactId=cont.Id,OpportunityId=testOpp3.Id,Role='Borrower');
        insert testOCR1;   
		OpportunityContactRole testOCR2 = new OpportunityContactRole(ContactId=cont.Id,OpportunityId=testOpp7.Id,Role='Borrower');
        insert testOCR2;   

        Properties__c newProperty = new Properties__c(Name='Test Property',Property_Street__c='123 Test',Property_City__c='Test',Property_State__c='MI',
          Property_Zip__c='48187',Property_County__c='Wayne',Property_Type__c='Detached',Most_Recent_Closed_Opportunity__c=testOpp7.Id, OwnerId=OwnerUser.Id);

        insert newProperty;
    }
    
    
    //confirm behavior for scheduler
    testMethod static void testScheduler() {
        
        test.startTest();
        
        new DateBatchTaskScheduler();
        
        test.stopTest();
        
    }
    
    //Confirm behavior for contact or lead task creation
    testMethod static void testCreatePersonTask() {
        Contact testCont = [Select Id from Contact];
        
        test.startTest();
        
        new DateBatchTaskCreation('Contact');
        
        test.stopTest();
        
   
    }

 

}