force-app/main/default/objects/Account/fields/Loan_Originator_User__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Originator User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Originator_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Referred_By__c.field-meta.xml
<CustomField>
    <fullName>Referred_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referred Households</relationshipLabel>
    <relationshipName>Referred_Households</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Loan_Originator_User__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Originator User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LO_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Referred_by__c.field-meta.xml
<CustomField>
    <fullName>Referred_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred by</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referrals Received from this Contact</relationshipLabel>
    <relationshipName>Referrals_Received</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
                <default>true</default>
                <label>Client</label>
            </value>
            <value>
                <fullName>Realtor</fullName>
            </value>
            <value>
                <fullName>Escrow Officer</fullName>
            </value>
            <value>
                <fullName>Lender AE</fullName>
            </value>
            <value>
                <fullName>Insurance Agent</fullName>
            </value>
            <value>
                <fullName>Lender_Ops</fullName>
                <label>Lender - Ops</label>
            </value>
            <value>
                <fullName>Financial Advisor</fullName>
                <label>Financial Advisor / Planner</label>
            </value>
            <value>
                <fullName>Referral Partner - Other</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Loan Originator / Broker</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Prospective LO</fullName>
            </value>
            <value>
                <fullName>Prospective TM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Originator_User__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Originator User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loans_Originated</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_By__c.field-meta.xml
<CustomField>
    <fullName>Referred_By__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Referred By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referred Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Closed.recordType-meta.xml
<RecordType>
    <fullName>Closed</fullName>
    <active>true</active>
    <businessProcess>Encompass Active</businessProcess>
    <label>Closed</label>
</RecordType>

force-app/main/default/classes/solidifyReferralSearchController_Test.cls
@isTest
public class solidifyReferralSearchController_Test {

        //This method will stage all appropriate test data
    @testSetup
    static void stageTestData() {
        
        User OwnerUser = new User(Firstname='Test',lastname='Owner', Email = 'test@test.com', Username = 'testowner@solidfy.com.dev', alias = 'town', profileid = '00ef4000001B3XBAA0', TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US', EmailEncodingKey = 'ISO-8859-1', LanguageLocaleKey = 'en_US');
        insert OwnerUser;

        List<Opportunity> testOpps = new List<Opportunity>();
        
        //Create Referring account and Contact
        Account referringAcct = new Account(Name='Referring Realtor', Ownerid = OwnerUser.Id, Loan_Originator_User__c = OwnerUser.Id);
        insert referringAcct;
        Contact contReferrer = new Contact(FirstName='Test',LastName='Tester3', AccountId=referringAcct.Id, Type__c = 'Client');
        insert contReferrer;
        
		//create referred Account, Contacts, Opportunities
        Account referredAcct = new Account(Name='Referred Client Account', Ownerid = OwnerUser.Id, Loan_Originator_User__c = OwnerUser.Id, Referred_By__c = contReferrer.id );
        insert referredAcct;
        Contact referredCont = new Contact(FirstName='Test',LastName='Tester2', AccountId=referredAcct.Id );
        insert referredCont;
      
        Opportunity OppOpenReferredBy = new Opportunity(Name='ReferredOpp - Open', StageName='Analysis / TBD', CloseDate=System.Today().addDays(15),
                                               AccountId=referredAcct.Id,  
                                               OwnerId=OwnerUser.Id, Loan_Originator_User__c = OwnerUser.id, Amount = 150000);
        testOpps.add(OppOpenReferredBy);
        Opportunity OppClosedReferredBy = new Opportunity(Name='ReferredOpp - Closed', StageName='Closed Won', CloseDate=System.Today().addDays(-15),
                                               AccountId=referredAcct.Id, OwnerId=OwnerUser.Id, 
                                               Loan_Originator_User__c = OwnerUser.id, Amount = 200000);
        testOpps.add(OppClosedReferredBy);

    }
    
    //Run Get Referred Contacts 
       testMethod static void testGetReferredContacts() {
       test.startTest();
       
       solidifyReferralSearchController dt = new solidifyReferralSearchController();
       Contact referredCont = [Select id from Contact WHERE FirstName = 'Test' LIMIT 1];
       solidifyReferralSearchController.getReferredContacts( referredCont.id );
         
        test.stopTest();

        
    }
}