force-app/main/default/objects/Account/fields/Loan_Originator__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator__c</fullName>
    <label>Loan Originator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dusty Broderick</fullName>
            </value>
            <value>
                <fullName>Missy Broderick</fullName>
            </value>
            <value>
                <fullName>Brandon Kyle</fullName>
            </value>
            <value>
                <fullName>Cole Annati</fullName>
            </value>
            <value>
                <fullName>Joe Rivera</fullName>
            </value>
            <value>
                <fullName>Andy Hess</fullName>
            </value>
            <value>
                <fullName>Steve McKnight</fullName>
            </value>
            <value>
                <fullName>Tiffany Attwood</fullName>
            </value>
            <value>
                <fullName>Robert Salas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Followup_Overdue__c.field-meta.xml
<CustomField>
    <fullName>Followup_Overdue__c</fullName>
    <formula>IF(  
  Followup_Date__c &gt; TOday(), 
  IMAGE(&apos;https://img.icons8.com/color/48/000000/low-importance--v1.png&apos;, &apos;Not due&apos;,15,15), 
  IF (
    Followup_Date__c == TODAY(),  
    IMAGE(&apos;https://img.icons8.com/color/48/000000/medium-priority.png&apos;, &apos;Due Today&apos;, 15,15), 
    IMAGE( &apos;https://img.icons8.com/color/48/000000/high-priority.png&apos;, &apos;Overdue&apos;, 15,15)
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Followup Overdue</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>OFlows</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OFlows</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Loan_Amount_f__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount_f__c</fullName>
    <formula>IF (NOT(ISBLANK(Loan__c)),  Loan__r.Loan_Amount__c , IF(NOT(ISBLANK( Lead__c )),  Lead__r.First_Loan_Amount_Scenario_1__c , 0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan Amount formula</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Loan_COE__c.field-meta.xml
<CustomField>
    <fullName>Loan_COE__c</fullName>
    <formula>Loan__r.COE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan COE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Loan_Lock_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Loan_Lock_Expiration__c</fullName>
    <formula>Loan__r.Lock_Expiration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan Lock Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Loan_Originator__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator__c</fullName>
    <formula>TEXT(Loan__r.Loan_Originator__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan Originator</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Loan_Stage__c.field-meta.xml
<CustomField>
    <fullName>Loan_Stage__c</fullName>
    <formula>TEXT(Loan__r.StageName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan Stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Net_Profit__c.field-meta.xml
<CustomField>
    <fullName>Net_Profit__c</fullName>
    <formula>IF(NOT(ISBLANK( Loan__c )), Loan__r.Net_Profit__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Profit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Next_Followup__c.field-meta.xml
<CustomField>
    <fullName>Next_Followup__c</fullName>
    <label>Next Followup In</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 Day</fullName>
            </value>
            <value>
                <fullName>2 Days</fullName>
            </value>
            <value>
                <fullName>1 Week</fullName>
            </value>
            <value>
                <fullName>2 Weeks</fullName>
            </value>
            <value>
                <fullName>3 Weeks</fullName>
            </value>
            <value>
                <fullName>1 Month</fullName>
            </value>
            <value>
                <fullName>3 Days</fullName>
                <isActive>false</isActive>
                <label>3 Days</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Refi-No Cashout</fullName>
            </value>
            <value>
                <fullName>Refi-Cashout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Waiting_Reason__c.field-meta.xml
<CustomField>
    <fullName>Waiting_Reason__c</fullName>
    <label>Waiting Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rate Watch</fullName>
            </value>
            <value>
                <fullName>Credit Repair</fullName>
            </value>
            <value>
                <fullName>Down Payment Limitation</fullName>
            </value>
            <value>
                <fullName>Property Limitation</fullName>
            </value>
            <value>
                <fullName>Income Limitation</fullName>
            </value>
            <value>
                <fullName>Construction Plans</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Loan_Originator__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator__c</fullName>
    <label>Loan Originator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dusty Broderick</fullName>
            </value>
            <value>
                <fullName>Missy Broderick</fullName>
            </value>
            <value>
                <fullName>Brandon Kyle</fullName>
            </value>
            <value>
                <fullName>Cole Annati</fullName>
            </value>
            <value>
                <fullName>Joe Rivera</fullName>
            </value>
            <value>
                <fullName>Andy Hess</fullName>
            </value>
            <value>
                <fullName>Steve McKnight</fullName>
            </value>
            <value>
                <fullName>Tiffany Attwood</fullName>
            </value>
            <value>
                <fullName>Robert Salas</fullName>
            </value>
            <value>
                <fullName>Louis Bing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>First Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Loan_Originator__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator__c</fullName>
    <label>Loan Originator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dusty Broderick</fullName>
            </value>
            <value>
                <fullName>Missy Broderick</fullName>
            </value>
            <value>
                <fullName>Robert Salas</fullName>
            </value>
            <value>
                <fullName>Tiffany Attwood</fullName>
            </value>
            <value>
                <fullName>Andy Hess</fullName>
            </value>
            <value>
                <fullName>Joe Rivera</fullName>
            </value>
            <value>
                <fullName>Louis Bing</fullName>
            </value>
            <value>
                <fullName>Cole Annati</fullName>
            </value>
            <value>
                <fullName>Brandon Kyle</fullName>
            </value>
            <value>
                <fullName>Steve McKnight</fullName>
            </value>
            <value>
                <fullName>Logan Tyler</fullName>
                <isActive>false</isActive>
                <label>Logan Tyler</label>
            </value>
            <value>
                <fullName>Sherman Chaplin</fullName>
                <isActive>false</isActive>
                <label>Sherman Chaplin</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>Refi_No_Cashout</fullName>
                <label>Refinance - No Cash Out</label>
            </value>
            <value>
                <fullName>Refi_Cashout</fullName>
                <label>Refinance - Cash Out</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount with MIP, FF</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Originator__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator__c</fullName>
    <label>Loan Originator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loan_Originator</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Net_Profit__c.field-meta.xml
<CustomField>
    <fullName>Net_Profit__c</fullName>
    <label>Net Profit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Refi-No Cashout</fullName>
            </value>
            <value>
                <fullName>Refi-Cashout</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Const-Perm</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Purch</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>HELOC</fullName>
            </value>
            <value>
                <fullName>HELOAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OFlowComponentDetailsController.cls
public class OFlowComponentDetailsController {
    
    @AuraEnabled
    public static Case loadOFlowRecord(String recordId){
        return [SELECT Id, Subject, ContactId, Contact.FirstName, Contact.LastName, Lead__c, Lead__r.FirstName, Lead__r.LastName, Lead_Status__c, Status, 
        Followup_Date__c, Priority, Purpose__c, Loan_Amount__c, Loan__c, Loan__r.Name, AccountId, Account.Name, Loan_Stage__c, 
        Loan_Lock_Expiration__c, Loan_COE__c, Loan_Originator__c, Revenue__c, Net_Profit__c, Loan_Amount_f__c, Next_Followup__c, Followup_Overdue__c, 
        Waiting_Reason__c, OwnerId, Owner.FirstName, Owner.LastName, Comments, CaseNumber FROM Case WHERE Id =: recordId];
    }

    @AuraEnabled
    public static String updateOFlowRecord(Case oFlowRecord){
        try {
            update oFlowRecord;

            return 'Success';
        } catch (Exception e) {
            return 'Error: ' + e.getMessage();
        }
    }

    @AuraEnabled
    public static List<PicklistWrapper> getPicklistValues(String picklistField){
        List<PicklistWrapper> plValues = new List<PicklistWrapper>();
        Schema.SObjectType objType = Schema.getGlobalDescribe().get('Case');
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        Schema.DescribeFieldResult objFieldInfo = objDescribe.fields.getMap().get(picklistField).getDescribe();
        List<Schema.PicklistEntry> picklistvalues = objFieldInfo.getPicklistValues();
        for(Schema.PicklistEntry plv: picklistvalues) {
            PicklistWrapper plWrap = new PicklistWrapper();
            plWrap.label = plv.getLabel();
            plWrap.text = plv.getValue();
            plWrap.isDefault = plv.isDefaultValue();
            plValues.add(plWrap);
        }
        return plValues;
    }

    private final static Integer MAX_RESULTS = 5;
    @AuraEnabled(cacheable=true)
    public static List<LookupSearchResult> searchContact(String searchTerm, List<String> selectedIds, String anOptionalParam) {
        System.debug('@@@ searchContact');
        searchTerm += '*';

        List<List<SObject>> searchResults = [FIND :searchTerm IN ALL FIELDS RETURNING
        Contact (Id, Name WHERE id NOT IN :selectedIds)
            LIMIT :MAX_RESULTS];

        List<LookupSearchResult> results = new List<LookupSearchResult>();

        String contactIcon = 'standard:contact';
        Contact [] contacts = ((List<Contact>) searchResults[0]);
        System.debug('@@@ contacts: ' + contacts);
        for (Contact contact : contacts) {
            results.add(new LookupSearchResult(contact.Id, 'Contact', contactIcon, contact.Name, 'Contact • '+ contact.Name));
        }

        return results;
    }

    @AuraEnabled(cacheable=true)
    public static List<LookupSearchResult> seachLead(String searchTerm, List<String> selectedIds, String anOptionalParam) {
        searchTerm += '*';

        List<List<SObject>> searchResults = [FIND :searchTerm IN ALL FIELDS RETURNING
        Lead (Id, Name WHERE id NOT IN :selectedIds)
            LIMIT :MAX_RESULTS];

        List<LookupSearchResult> results = new List<LookupSearchResult>();

        String leadIcon = 'standard:lead';
        Lead [] leads = ((List<Lead>) searchResults[0]);
        for (Lead lead : leads) {
            results.add(new LookupSearchResult(lead.Id, 'Lead', leadIcon, lead.Name, 'Lead • '+ lead.Name));
        }

        return results;
    }

    @AuraEnabled(cacheable=true)
    public static List<LookupSearchResult> searchLoan(String searchTerm, List<String> selectedIds, String anOptionalParam) {
        searchTerm += '*';

        List<List<SObject>> searchResults = [FIND :searchTerm IN ALL FIELDS RETURNING
        Opportunity (Id, Name WHERE id NOT IN :selectedIds)
            LIMIT :MAX_RESULTS];

        List<LookupSearchResult> results = new List<LookupSearchResult>();

        String opportunityIcon = 'standard:opportunity';
        Opportunity [] opportunities = ((List<Opportunity>) searchResults[0]);
        for (Opportunity opportunity : opportunities) {
            results.add(new LookupSearchResult(opportunity.Id, 'Opportunity', opportunityIcon, opportunity.Name, 'Loan • '+ opportunity.Name));
        }

        return results;
    }

    @AuraEnabled(cacheable=true)
    public static List<LookupSearchResult> searchAccount(String searchTerm, List<String> selectedIds, String anOptionalParam) {
        searchTerm += '*';

        List<List<SObject>> searchResults = [FIND :searchTerm IN ALL FIELDS RETURNING
        Account (Id, Name WHERE id NOT IN :selectedIds)
            LIMIT :MAX_RESULTS];

        List<LookupSearchResult> results = new List<LookupSearchResult>();

        String accountIcon = 'standard:account';
        Account [] accounts = ((List<Account>) searchResults[0]);
        for (Account account : accounts) {
            results.add(new LookupSearchResult(account.Id, 'Account', accountIcon, account.Name, 'Account • '+ account.Name));
        }

        return results;
    }

    @AuraEnabled(cacheable=true)
    public static List<LookupSearchResult> searchOwner(String searchTerm, List<String> selectedIds, String anOptionalParam) {
        searchTerm += '*';

        List<List<SObject>> searchResults = [FIND :searchTerm IN ALL FIELDS RETURNING
        User (Id, Name WHERE id NOT IN :selectedIds)
            LIMIT :MAX_RESULTS];

        List<LookupSearchResult> results = new List<LookupSearchResult>();

        String userIcon = 'standard:user';
        User [] users = ((List<User>) searchResults[0]);
        for (User user : users) {
            results.add(new LookupSearchResult(user.Id, 'User', userIcon, user.Name, 'Owner • '+ user.Name));
        }

        return results;
    }

    public class PicklistWrapper{
        @AuraEnabled public String label;
        @AuraEnabled public String text;
        @AuraEnabled public Boolean isDefault;
    }
}