force-app/main/default/objects/Properties__c/Properties__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Properties Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Properties__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ScenariosTabControllerTest.cls
@isTest
public class ScenariosTabControllerTest {
@isTest
    public static void ContactScenariosControllerPage(){
        Account testAccount = new Account();
        testAccount.Name = 'TestACCName';
        insert testAccount;
        
        Contact testContact = new Contact();
        testContact.LastName = 'TestLastName';
        testContact.FirstName = 'TestFirstName';
        testContact.AccountId = testAccount.id;
        insert testContact;
       
        Lead testLead = new Lead();
        testLead.FirstName = 'Test';
        testLead.LastName = 'Lead';
        insert testLead;
        
        
        Properties__c testProperties = new Properties__c();
        testProperties.Name = 'TestPropName';
        testProperties.Household__c = testAccount.id;
        insert testProperties;
        
        Test.startTest();
        ScenariosTabController.getPropertyList(testContact.id);
        ScenariosTabController.getPropertyDetails(testProperties.id);
        ScenarioTabLeadCont.createProposalButtonMethod(testLead.Id);
        ScenariosTabController.createProposalButtonMethod(testAccount.Id);
		Test.stopTest();
       }
}