force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Current_Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Current_Interest_Rate__c</fullName>
    <label>Current Interest Rate</label>
    <precision>17</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Amount__c</fullName>
    <label>Current Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Loan_Balance_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Balance_Remaining__c</fullName>
    <label>Scheduled Balance Remaining</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Loan_First_Payment__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_First_Payment__c</fullName>
    <label>Current Loan First Payment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Loan_Last_Payment_Made__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Last_Payment_Made__c</fullName>
    <label>Current Loan Last Payment Made</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Loan_Monthly_Payment__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Monthly_Payment__c</fullName>
    <label>Current Loan Monthly Payment</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Loan_Payments_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Payments_Remaining__c</fullName>
    <formula>Current_Loan_Term__c - Current_Loan_Number_Payments_Made__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Loan Payments Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Term__c</fullName>
    <label>Current Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Fixed_Term_Years__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Term_Years__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Fixed Term Years</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Monthly_PI_Pmt1__c.field-meta.xml
<CustomField>
    <fullName>Monthly_PI_Pmt1__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Rate Analysis</description>
    <label>Monthly PI Pmt1</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Monthly_PI_Pmt2__c.field-meta.xml
<CustomField>
    <fullName>Monthly_PI_Pmt2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly PI Pmt2</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Monthly_PI_Pmt3__c.field-meta.xml
<CustomField>
    <fullName>Monthly_PI_Pmt3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly PI Pmt3</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Monthly_PI_Pmt4__c.field-meta.xml
<CustomField>
    <fullName>Monthly_PI_Pmt4__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly PI Pmt4</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Monthly_PI_Pmt5__c.field-meta.xml
<CustomField>
    <fullName>Monthly_PI_Pmt5__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly PI Pmt5</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Monthly_PI_Pmt6__c.field-meta.xml
<CustomField>
    <fullName>Monthly_PI_Pmt6__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly PI Pmt6</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Most_Recent_Loan__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Number</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>New_Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/New_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>New_Loan_Amount__c</fullName>
    <label>New Loan Amount</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/New_Loan_Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>New_Loan_Interest_Rate__c</fullName>
    <label>New Loan Interest Rate</label>
    <precision>17</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/New_Loan_Monthly_Payment__c.field-meta.xml
<CustomField>
    <fullName>New_Loan_Monthly_Payment__c</fullName>
    <label>New Loan Monthly Payment</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/New_Loan_Payment_To_Keep_Term__c.field-meta.xml
<CustomField>
    <fullName>New_Loan_Payment_To_Keep_Term__c</fullName>
    <label>New Loan Payment To Keep Term</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/New_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>New_Loan_Term__c</fullName>
    <label>New Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Price_1__c.field-meta.xml
<CustomField>
    <fullName>Price_1__c</fullName>
    <label>Price 1</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Price_2__c.field-meta.xml
<CustomField>
    <fullName>Price_2__c</fullName>
    <label>Price 2</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Price_3__c.field-meta.xml
<CustomField>
    <fullName>Price_3__c</fullName>
    <label>Price 3</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Price_4__c.field-meta.xml
<CustomField>
    <fullName>Price_4__c</fullName>
    <label>Price 4</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Price_5__c.field-meta.xml
<CustomField>
    <fullName>Price_5__c</fullName>
    <label>Price 5</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Price_6__c.field-meta.xml
<CustomField>
    <fullName>Price_6__c</fullName>
    <label>Price 6</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Rate_1__c.field-meta.xml
<CustomField>
    <fullName>Rate_1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate 1</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Rate_2__c.field-meta.xml
<CustomField>
    <fullName>Rate_2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate 2</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Rate_3__c.field-meta.xml
<CustomField>
    <fullName>Rate_3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate 3</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Rate_4__c.field-meta.xml
<CustomField>
    <fullName>Rate_4__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate 4</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Rate_5__c.field-meta.xml
<CustomField>
    <fullName>Rate_5__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate 5</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Rate_6__c.field-meta.xml
<CustomField>
    <fullName>Rate_6__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate 6</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Same_Payment_Term_Reduction__c.field-meta.xml
<CustomField>
    <fullName>Same_Payment_Term_Reduction__c</fullName>
    <label>Same Payment Term Reduction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Cost_1__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Cost 1</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Cost_2__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Cost 2</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Cost_3__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Cost 3</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Cost_4__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_4__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Cost 4</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Cost_5__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_5__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Cost 5</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Cost_6__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_6__c</fullName>
    <label>Total Cost 6</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Loan_Amount1__c.field-meta.xml
<CustomField>
    <fullName>Total_Loan_Amount1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Loan Amount1</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Loan_Amount2__c.field-meta.xml
<CustomField>
    <fullName>Total_Loan_Amount2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Loan Amount2</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Loan_Amount3__c.field-meta.xml
<CustomField>
    <fullName>Total_Loan_Amount3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Loan Amount3</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Loan_Amount4__c.field-meta.xml
<CustomField>
    <fullName>Total_Loan_Amount4__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Loan Amount4</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Loan_Amount5__c.field-meta.xml
<CustomField>
    <fullName>Total_Loan_Amount5__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Loan Amount5</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Loan_Amount6__c.field-meta.xml
<CustomField>
    <fullName>Total_Loan_Amount6__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Loan Amount6</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/solidify_ProposalTrigger_Test.cls
@isTest
public class solidify_ProposalTrigger_Test {

    @testSetup
    public static void setup(){
        Account a = New Account(Name = 'TestAccount');
        insert a;
        Opportunity v1 = new Opportunity(Name = 'TestLoan', AccountId = a.id, StageName = 'New', CloseDate = date.Today());
        insert v1;
    	Proposal__c refiProp = new Proposal__c (Name = 'Test', Most_Recent_Loan__c = v1.id, RecordTypeId='012f4000000OatvAAC');
    	insert refiProp;
        
        Proposal__c rateProp =  new Proposal__c (Name = 'Test Rate',Most_Recent_Loan__c =v1.id,RecordTypeId='012f4000000ObpJAAS',
                                                 Rate_1__c = 3.15,Rate_2__c=3.2,Rate_3__c=3.3,Rate_4__c=3.4,Rate_5__c=3.5,Rate_6__c=3.6,
                                                 Price_1__c=0.6,Price_2__c=0.5,Price_3__c=0.4,Price_4__c=0.3,Price_5__c=0.2,Price_6__c=0.1,
                                                Fixed_Term_Years__c=30,Monthly_PI_Pmt6__c=10,Monthly_PI_Pmt1__c=1,Monthly_PI_Pmt2__c=2,
                                                Monthly_PI_Pmt3__c=3,Monthly_PI_Pmt4__c=4,Monthly_PI_Pmt5__c=5,Total_Loan_Amount1__c=100,Total_Loan_Amount2__c=200,
                                                Total_Loan_Amount3__c=300,Total_Loan_Amount4__c=400,Total_Loan_Amount5__c=500,Total_Loan_Amount6__c=600,
                                                Total_Cost_1__c=1,Total_Cost_2__c=2,Total_Cost_3__c=3,Total_Cost_4__c=4,Total_Cost_5__c=5,Total_Cost_6__c=6);
        insert rateProp;
        
        
    }
    
    @isTest
    public static void testUpdate(){
     test.startTest();
    	Proposal__c q = [SELECT Id, Current_Loan_Amount__c, Current_Interest_Rate__c, Current_Loan_Term__c, 
                   Current_Loan_First_Payment__c, Current_Loan_Last_Payment_Made__c, New_Loan_Amount__c,
                   New_Loan_Interest_Rate__c, New_Loan_Term__c, Current_Loan_Monthly_Payment__c FROM Proposal__c WHERE RecordTypeId ='012f4000000OatvAAC' LIMIT 1];
    	q.Name = 'TestUpdate';
        q.Current_Loan_Amount__c = 500000;
    	q.Current_Interest_Rate__c = 4.140;
   		q.Current_Loan_Term__c = 360;
        q.Current_Loan_First_Payment__c = date.valueOf('2019-01-01');
        q.Current_Loan_Last_Payment_Made__c = date.valueOf('2019-10-08');
        q.New_Loan_Amount__c = 492800;
        q.New_Loan_Interest_Rate__c = 3.99;
        q.New_Loan_Term__c = 360;
        update q;
        
        Proposal__c q2 = [SELECT Id, Current_Loan_Balance_Remaining__c, New_Loan_Payment_To_Keep_Term__c, 
                    Current_Loan_Payments_Remaining__c, Current_Loan_Monthly_Payment__c, New_Loan_Monthly_Payment__c, 
                    Same_Payment_Term_Reduction__c FROM Proposal__c WHERE RecordTypeId ='012f4000000OatvAAC' LIMIT 1];

        system.assertEquals(2427.61, q2.Current_Loan_Monthly_Payment__c);
        system.assertEquals(2349.86, q2.New_Loan_Monthly_Payment__c);
        system.debug(q2.Current_Loan_Payments_Remaining__c);
        system.assertEquals(2384.80, q2.New_Loan_Payment_To_Keep_Term__c);
        system.assertEquals(11, q2.Same_Payment_Term_Reduction__c);
        
     test.stopTest();
	
        
        
    }

}