force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Current_Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Current_Interest_Rate__c</fullName>
    <label>Current Interest Rate</label>
    <precision>17</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Amount__c</fullName>
    <label>Current Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Loan_Balance_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Balance_Remaining__c</fullName>
    <label>Scheduled Balance Remaining</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Loan_First_Payment__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_First_Payment__c</fullName>
    <label>Current Loan First Payment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Loan_Last_Payment_Made__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Last_Payment_Made__c</fullName>
    <label>Current Loan Last Payment Made</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Loan_Monthly_Payment__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Monthly_Payment__c</fullName>
    <label>Current Loan Monthly Payment</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Loan_Number_Payments_Made__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Number_Payments_Made__c</fullName>
    <formula>MFLOOR( (Current_Loan_Last_Payment_Made__c -  Current_Loan_First_Payment__c) /30) + 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Loan Number Payments Made</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Loan_Payments_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Payments_Remaining__c</fullName>
    <formula>Current_Loan_Term__c - Current_Loan_Number_Payments_Made__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Loan Payments Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Term__c</fullName>
    <label>Current Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/New_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>New_Loan_Amount__c</fullName>
    <label>New Loan Amount</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/New_Loan_Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>New_Loan_Interest_Rate__c</fullName>
    <label>New Loan Interest Rate</label>
    <precision>17</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/New_Loan_Monthly_Payment__c.field-meta.xml
<CustomField>
    <fullName>New_Loan_Monthly_Payment__c</fullName>
    <label>New Loan Monthly Payment</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/New_Loan_Payment_To_Keep_Term__c.field-meta.xml
<CustomField>
    <fullName>New_Loan_Payment_To_Keep_Term__c</fullName>
    <label>New Loan Payment To Keep Term</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/New_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>New_Loan_Term__c</fullName>
    <label>New Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Same_Payment_Term_Reduction__c.field-meta.xml
<CustomField>
    <fullName>Same_Payment_Term_Reduction__c</fullName>
    <label>Same Payment Term Reduction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/solidifyRefiAnalysisCalcs.cls
public class solidifyRefiAnalysisCalcs {

    public static List<Proposal__c> beforeCalcs(List<Proposal__c> refis) {

        return refis;
    }

    public static void afterCalcs(List<String> refiIds){
        List<Proposal__c> refiProposals = [SELECT Id, Current_Loan_Amount__C, Current_Interest_Rate__c, Current_Loan_Term__c, Current_Loan_First_Payment__c, Current_Loan_Last_Payment_Made__c,
        Current_Loan_Number_Payments_Made__c, Current_Loan_Payments_Remaining__c,
        Current_Loan_Balance_Remaining__c, Current_Loan_Monthly_Payment__c,   
        New_Loan_Amount__c, New_Loan_Term__c, New_Loan_Interest_Rate__c, 
        New_Loan_Payment_To_Keep_Term__c, New_Loan_Monthly_Payment__c 
        FROM Proposal__c WHERE Id IN :refiIds];

        for(Proposal__c q: refiProposals){

            
            if (q.Current_Loan_Amount__c != null && q.Current_Interest_Rate__c != null && q.Current_Loan_Term__c != null){   
                q.Current_Loan_Monthly_Payment__c = solidifyUtil.pmt(q.Current_Loan_Amount__c, q.Current_Interest_Rate__c, integer.valueOf(q.Current_Loan_Term__c));
                system.debug(q.Current_Loan_Monthly_Payment__c);
                system.debug(q.Current_Loan_Number_Payments_Made__c);
                if(q.Current_Loan_Number_Payments_Made__c != null){
                        
                        q.Current_Loan_Balance_Remaining__c = solidifyUtil.balance( q.Current_Loan_Amount__c, q.Current_Interest_Rate__c, integer.valueOf(q.Current_Loan_Number_Payments_Made__c), q.Current_Loan_Monthly_Payment__c );
                }
            }

            if (q.New_Loan_Term__c !=null && q.New_Loan_Amount__c != null && q.New_Loan_Interest_Rate__c != null){
                q.New_Loan_Monthly_Payment__c = solidifyUtil.pmt(q.New_Loan_Amount__c, q.New_Loan_Interest_Rate__c, integer.valueOf(q.New_Loan_Term__c));
                if (q.Current_Loan_Number_Payments_Made__c!=null){                    
                    q.New_Loan_Payment_To_Keep_Term__c = solidifyUtil.pmt(q.New_Loan_Amount__c, q.New_Loan_Interest_Rate__c, integer.valueOf(q.Current_Loan_Payments_Remaining__c));
                }
                system.debug(solidifyUtil.numberPayments(q.New_Loan_Amount__c, q.New_Loan_Interest_Rate__c, q.Current_Loan_Monthly_Payment__c));
                q.Same_Payment_Term_Reduction__c = q.Current_Loan_Payments_Remaining__c - solidifyUtil.numberPayments(q.New_Loan_Amount__c, q.New_Loan_Interest_Rate__c, q.Current_Loan_Monthly_Payment__c);                
            }                     



        }

        update refiProposals;

    }

}