force-app/main/default/objects/Scenario__c/Scenario__c.object-meta.xml
<CustomObject>
    <label>Scenario</label>
    <nameField>
        <displayFormat>SCN-{0000000}</displayFormat>
        <label>Scenario Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scenarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scenario__c/fields/AppraisalFeeS1__c.field-meta.xml
<CustomField>
    <fullName>AppraisalFeeS1__c</fullName>
    <label>AppraisalFeeS1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/AppraisalFeeS2__c.field-meta.xml
<CustomField>
    <fullName>AppraisalFeeS2__c</fullName>
    <label>AppraisalFeeS2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/CopyToScenarios2And3__c.field-meta.xml
<CustomField>
    <fullName>CopyToScenarios2And3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CopyToScenarios2And3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/CreditReportFeeS1__c.field-meta.xml
<CustomField>
    <fullName>CreditReportFeeS1__c</fullName>
    <label>CreditReportFeeS1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/CreditReportFeeS2__c.field-meta.xml
<CustomField>
    <fullName>CreditReportFeeS2__c</fullName>
    <label>CreditReportFeeS2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/DiscountCreditS1__c.field-meta.xml
<CustomField>
    <fullName>DiscountCreditS1__c</fullName>
    <label>DiscountCreditS1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/DiscountCreditS2__c.field-meta.xml
<CustomField>
    <fullName>DiscountCreditS2__c</fullName>
    <label>DiscountCreditS2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/DownpaymentScenario1__c.field-meta.xml
<CustomField>
    <fullName>DownpaymentScenario1__c</fullName>
    <label>DownpaymentScenario1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/DownpaymentScenario2__c.field-meta.xml
<CustomField>
    <fullName>DownpaymentScenario2__c</fullName>
    <label>DownpaymentScenario2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/EscrowFeesS1__c.field-meta.xml
<CustomField>
    <fullName>EscrowFeesS1__c</fullName>
    <label>EscrowFeesS1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/EscrowFeesS2__c.field-meta.xml
<CustomField>
    <fullName>EscrowFeesS2__c</fullName>
    <label>EscrowFeesS2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/EstimatedHOAScenario1__c.field-meta.xml
<CustomField>
    <fullName>EstimatedHOAScenario1__c</fullName>
    <label>EstimatedHOAScenario1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/EstimatedHOAScenario2__c.field-meta.xml
<CustomField>
    <fullName>EstimatedHOAScenario2__c</fullName>
    <label>EstimatedHOAScenario2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/EstimatedInsuranceScenario1__c.field-meta.xml
<CustomField>
    <fullName>EstimatedInsuranceScenario1__c</fullName>
    <label>EstimatedInsuranceScenario1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/EstimatedInsuranceScenario2__c.field-meta.xml
<CustomField>
    <fullName>EstimatedInsuranceScenario2__c</fullName>
    <label>EstimatedInsuranceScenario2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/EstimatedMortgageInsuranceScenario1__c.field-meta.xml
<CustomField>
    <fullName>EstimatedMortgageInsuranceScenario1__c</fullName>
    <label>EstimatedMortgageInsuranceScenario1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/EstimatedMortgageInsuranceScenario2__c.field-meta.xml
<CustomField>
    <fullName>EstimatedMortgageInsuranceScenario2__c</fullName>
    <label>EstimatedMortgageInsuranceScenario2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/EstimatedTaxesScenario1__c.field-meta.xml
<CustomField>
    <fullName>EstimatedTaxesScenario1__c</fullName>
    <label>EstimatedTaxesScenario1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/EstimatedTaxesScenario2__c.field-meta.xml
<CustomField>
    <fullName>EstimatedTaxesScenario2__c</fullName>
    <label>EstimatedTaxesScenario2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/First_Loan_Amount_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_1__c</fullName>
    <label>First_Loan_Amount_Scenario_1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/First_Loan_Amount_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_2__c</fullName>
    <label>First_Loan_Amount_Scenario_2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/LenderFeeS1__c.field-meta.xml
<CustomField>
    <fullName>LenderFeeS1__c</fullName>
    <label>LenderFeeS1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/LenderFeeS2__c.field-meta.xml
<CustomField>
    <fullName>LenderFeeS2__c</fullName>
    <label>LenderFeeS2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/Loan_Program_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>Loan_Program_Scenario_1__c</fullName>
    <label>Loan_Program_Scenario_1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CF30</fullName>
            </value>
            <value>
                <fullName>CF25</fullName>
            </value>
            <value>
                <fullName>CF20</fullName>
            </value>
            <value>
                <fullName>CF15</fullName>
            </value>
            <value>
                <fullName>CF10</fullName>
            </value>
            <value>
                <fullName>HB30</fullName>
            </value>
            <value>
                <fullName>HB25</fullName>
            </value>
            <value>
                <fullName>HB20</fullName>
            </value>
            <value>
                <fullName>HB15</fullName>
            </value>
            <value>
                <fullName>HB10</fullName>
            </value>
            <value>
                <fullName>JF30</fullName>
            </value>
            <value>
                <fullName>JF15</fullName>
            </value>
            <value>
                <fullName>FHA 30</fullName>
            </value>
            <value>
                <fullName>FHA 15</fullName>
            </value>
            <value>
                <fullName>VA 30</fullName>
            </value>
            <value>
                <fullName>VA 15</fullName>
            </value>
            <value>
                <fullName>C 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>FHA 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>VA 5-1 ARM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/Loan_Program_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>Loan_Program_Scenario_2__c</fullName>
    <label>Loan Program Scenario 2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CF30</fullName>
            </value>
            <value>
                <fullName>CF25</fullName>
            </value>
            <value>
                <fullName>CF20</fullName>
            </value>
            <value>
                <fullName>CF15</fullName>
            </value>
            <value>
                <fullName>CF10</fullName>
            </value>
            <value>
                <fullName>HB30</fullName>
            </value>
            <value>
                <fullName>HB25</fullName>
            </value>
            <value>
                <fullName>HB20</fullName>
            </value>
            <value>
                <fullName>HB15</fullName>
            </value>
            <value>
                <fullName>HB10</fullName>
            </value>
            <value>
                <fullName>JF30</fullName>
            </value>
            <value>
                <fullName>JF15</fullName>
            </value>
            <value>
                <fullName>FHA 30</fullName>
            </value>
            <value>
                <fullName>FHA 15</fullName>
            </value>
            <value>
                <fullName>VA 30</fullName>
            </value>
            <value>
                <fullName>VA 15</fullName>
            </value>
            <value>
                <fullName>C 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>FHA 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>VA 5-1 ARM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/Purpose_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>Purpose_Scenario_1__c</fullName>
    <label>Purpose Scenario 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>Refinance - No Cash Out</fullName>
            </value>
            <value>
                <fullName>Refinance - Cash Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/Purpose_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>Purpose_Scenario_2__c</fullName>
    <label>Purpose Scenario 2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>Refinance - No Cash Out</fullName>
            </value>
            <value>
                <fullName>Refinance - Cash Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/Rate_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>Rate_Scenario_1__c</fullName>
    <label>Rate Scenario 1</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/Rate_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>Rate_Scenario_2__c</fullName>
    <label>Rate Scenario 2</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/Term_Due__c.field-meta.xml
<CustomField>
    <fullName>Term_Due__c</fullName>
    <label>Term Due</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/Term_Due_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>Term_Due_Scenario_2__c</fullName>
    <label>Term Due Scenario 2</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/TitleFeeS1__c.field-meta.xml
<CustomField>
    <fullName>TitleFeeS1__c</fullName>
    <label>TitleFeeS1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/TitleFeeS2__c.field-meta.xml
<CustomField>
    <fullName>TitleFeeS2__c</fullName>
    <label>TitleFeeS2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/scenarioTriggerHandler.cls
public with sharing class scenarioTriggerHandler {
    public static void beforeUpdate(List<scenario__c> newScenarios) {

        for(Scenario__c s: newScenarios){
            if(s.CopyToScenarios2And3__c){
                s.Purpose_Scenario_2__c =s.Purpose_Scenario_1__c;
                s.DownPaymentScenario2__c = s.DownPaymentScenario1__c;
                s.Loan_Program_Scenario_2__c=s.Loan_Program_Scenario_1__c;
                s.Term_Due_Scenario_2__c = s.Term_Due__c;
                s.First_Loan_Amount_Scenario_2__c = s.First_Loan_Amount_Scenario_1__c;
                s.Rate_Scenario_2__c = s.Rate_Scenario_1__c;
                s.EstimatedTaxesScenario2__c = s.EstimatedTaxesScenario1__c;
                s.EstimatedInsuranceScenario2__c = s.EstimatedInsuranceScenario1__c;
                s.EstimatedMortgageInsuranceScenario2__c =s.EstimatedMortgageInsuranceScenario1__c;
                s.EstimatedHOAScenario2__c = s.EstimatedHOAScenario1__c;
                s.DiscountCreditS2__c = s.DiscountCreditS1__c;
                s.LenderFeeS2__c = s.LenderFeeS1__c;
                s.AppraisalFeeS2__c = s.AppraisalFeeS1__c;
                s.CreditReportFeeS2__c = s.CreditReportFeeS1__c;
                s.EscrowFeesS2__c = s.EscrowFeesS1__c;
                s.TitleFeeS2__c = s.TitleFeeS1__c;
                s.RecordingFeeS2__c = s.RecordingFeeS1__c;

                s.Purpose_Scenario_3__c =s.Purpose_Scenario_1__c;
                s.DownPaymentScenario3__c = s.DownPaymentScenario1__c;
                s.Loan_Program_Scenario_3__c=s.Loan_Program_Scenario_1__c;
                s.Term_Due_Scenario_3__c = s.Term_Due__c;
                s.First_Loan_Amount_Scenario_3__c = s.First_Loan_Amount_Scenario_1__c;
                s.Rate_Scenario_3__c = s.Rate_Scenario_1__c;
                s.EstimatedTaxesScenario3__c = s.EstimatedTaxesScenario1__c;
                s.EstimatedInsuranceScenario3__c = s.EstimatedInsuranceScenario1__c;
                s.EstimatedMortgageInsuranceScenario3__c =s.EstimatedMortgageInsuranceScenario1__c;
                s.EstimatedHOAScenario3__c = s.EstimatedHOAScenario1__c;
                s.DiscountCreditS3__c = s.DiscountCreditS1__c;
                s.LenderFeeS3__c = s.LenderFeeS1__c;
                s.AppraisalFeeS3__c = s.AppraisalFeeS1__c;
                s.CreditReportFeeS3__c = s.CreditReportFeeS1__c;
                s.EscrowFeesS3__c = s.EscrowFeesS1__c;
                s.TitleFeeS3__c = s.TitleFeeS1__c;
                s.RecordingFeeS3__c = s.RecordingFeeS1__c;

                s.CopyToScenarios2And3__c = false;
            }
        }

    }
}