force-app/main/default/objects/Lead/fields/CancelMIAtS2__c.field-meta.xml
<CustomField>
    <fullName>CancelMIAtS2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cancel MI At (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CancelMIAtS3__c.field-meta.xml
<CustomField>
    <fullName>CancelMIAtS3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cancel MI At (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/First_Loan_Amount_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_1__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/First_Loan_Amount_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_2__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/First_Loan_Amount_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_3__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PaymentResultS2__c.field-meta.xml
<CustomField>
    <fullName>PaymentResultS2__c</fullName>
    <label>Payment Result</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PaymentResultS3__c.field-meta.xml
<CustomField>
    <fullName>PaymentResultS3__c</fullName>
    <label>Payment Result</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Rate_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>Rate_Scenario_1__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Rate_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>Rate_Scenario_2__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Rate_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>Rate_Scenario_3__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Term_Due__c.field-meta.xml
<CustomField>
    <fullName>Term_Due__c</fullName>
    <description>Years</description>
    <label>Term/Due (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Term_Due_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>Term_Due_Scenario_2__c</fullName>
    <description>Years</description>
    <label>Term/Due (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Term_Due_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>Term_Due_Scenario_3__c</fullName>
    <description>Years</description>
    <label>Term/Due (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/UFMIPFFS3__c.field-meta.xml
<CustomField>
    <fullName>UFMIPFFS3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>UFMIP/FF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LeadApi__c/LeadApi__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>LeadApi</label>
</CustomObject>

force-app/main/default/objects/LeadApi__c/fields/partner_vendorid__c.field-meta.xml
<CustomField>
    <fullName>partner_vendorid__c</fullName>
    <label>partner_vendorid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadApi__c/fields/post_patch_endpoint__c.field-meta.xml
<CustomField>
    <fullName>post_patch_endpoint__c</fullName>
    <label>post_patch_endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadTriggerHandlerTest.cls
@isTest
private class LeadTriggerHandlerTest {
    @testSetup static void setup() {
        LeadApi__c ld_Api = new LeadApi__c();
        ld_Api.post_patch_endpoint__c = 'https://apibeta.rockfin.com/rccx-lead-submission-proxy/leads';
        ld_Api.client_secret__c = '3434323Fe';
        ld_Api.client_id__c = '8425705E';
        ld_Api.partner_vendorid__c = 'a01g0000008JYACAA5';
        insert ld_Api;
    }

    @isTest static void onCreateApi(){
        Test.startTest();

        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('LeadApiResp');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');

        Test.setMock(HttpCalloutMock.class, mock);

        Lead l = new Lead (LastName = 'Test', FirstName = 'Teddy');
        l.Status = 'New';
        l.LeadSource = 'LMB';
        l.Term_Due__c = 2;
        l.Rate_Scenario_1__c = 2;
        l.First_Loan_Amount_Scenario_1__c = 2;
        l.Term_Due_Scenario_2__c = 2;
        l.Rate_Scenario_2__c = 2;
        l.First_Loan_Amount_Scenario_2__c =2;
        l.PaymentResultS2__c = 2;
        l.UFMIPFFS2__c = .22;
        l.EstimatedMortgageInsuranceScenario2__c = 2; 
        l.CancelMIAtS2__c = 2;
        l.First_Loan_Amount_Scenario_3__c =2;
        l.PaymentResultS3__c = 2;
        l.UFMIPFFS3__c = .2;
        l.PaymentResultS3__c = 2;
        l.UFMIPFFS3__c = .2;
        l.EstimatedMortgageInsuranceScenario3__c = 2; 
        l.CancelMIAtS3__c = 2;
        l.Term_Due_Scenario_3__c = 2;
        l.Rate_Scenario_3__c = 2;
        l.First_Loan_Amount_Scenario_3__c =2;
        insert l;
        Set<id> leadIds = new Set<Id>();
        leadIds.add(l.id);
        LeadTriggerHandler.postLeadsToRca(leadIds, 'GET');
        Test.stopTest();
    }


}