force-app/main/default/objects/Lead/fields/CancelMIAtS2__c.field-meta.xml
<CustomField>
    <fullName>CancelMIAtS2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cancel MI At (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CancelMIAtS3__c.field-meta.xml
<CustomField>
    <fullName>CancelMIAtS3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cancel MI At (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/First_Loan_Amount_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_1__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/First_Loan_Amount_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_2__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/First_Loan_Amount_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_3__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PaymentResultS2__c.field-meta.xml
<CustomField>
    <fullName>PaymentResultS2__c</fullName>
    <label>Payment Result</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PaymentResultS3__c.field-meta.xml
<CustomField>
    <fullName>PaymentResultS3__c</fullName>
    <label>Payment Result</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Rate_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>Rate_Scenario_1__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Rate_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>Rate_Scenario_2__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Rate_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>Rate_Scenario_3__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Term_Due__c.field-meta.xml
<CustomField>
    <fullName>Term_Due__c</fullName>
    <description>Years</description>
    <label>Term/Due (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Term_Due_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>Term_Due_Scenario_2__c</fullName>
    <description>Years</description>
    <label>Term/Due (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Term_Due_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>Term_Due_Scenario_3__c</fullName>
    <description>Years</description>
    <label>Term/Due (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/UFMIPFFS3__c.field-meta.xml
<CustomField>
    <fullName>UFMIPFFS3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>UFMIP/FF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/LeadTrigger_Test.cls
@isTest
public class LeadTrigger_Test {

    @isTest
    public static void testUpdate(){
        Lead l = new Lead (LastName = 'Test', FirstName = 'Teddy');
        insert l;
        l.Term_Due__c = 2;
        l.Rate_Scenario_1__c = 2;
        l.First_Loan_Amount_Scenario_1__c = 2;
        l.Term_Due_Scenario_2__c = 2;
        l.Rate_Scenario_2__c = 2;
        l.First_Loan_Amount_Scenario_2__c =2;
        l.PaymentResultS2__c = 2;
        l.UFMIPFFS2__c = .22;
        l.EstimatedMortgageInsuranceScenario2__c = 2; 
        l.CancelMIAtS2__c = 2;
        l.First_Loan_Amount_Scenario_3__c =2;
        l.PaymentResultS3__c = 2;
        l.UFMIPFFS3__c = .2;
        l.PaymentResultS3__c = 2;
        l.UFMIPFFS3__c = .2;
        l.EstimatedMortgageInsuranceScenario3__c = 2; 
        l.CancelMIAtS3__c = 2;
        l.Term_Due_Scenario_3__c = 2;
        l.Rate_Scenario_3__c = 2;
        l.First_Loan_Amount_Scenario_3__c =2;
        update l;
        
        Lead newLead = [SELECT Company FROM Lead];
        System.assertEquals ('Teddy Test - Household', newLead.Company);
    }
    @isTest
    public static void testDelete() {
        Lead l = new Lead (LastName = 'Test', FirstName = 'Teddy');
        insert l;
        delete l;
        undelete l;
    }
}