force-app/main/default/objects/Lead/fields/CLTV_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>CLTV_Scenario_1__c</fullName>
    <formula>(First_Loan_Amount_Scenario_1__c +  Second_Loan_Amount__c) /  Estimated_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CLTV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CLTV_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>CLTV_Scenario_2__c</fullName>
    <formula>(First_Loan_Amount_Scenario_2__c + Second_Loan_Amount_Scenario_2__c) / Estimated_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CLTV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CLTV_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>CLTV_Scenario_3__c</fullName>
    <formula>(First_Loan_Amount_Scenario_3__c + Second_Loan_Amount_Scenario_3__c) / Estimated_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CLTV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <label>Current Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Current_Payment__c.field-meta.xml
<CustomField>
    <fullName>Current_Payment__c</fullName>
    <label>Current Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Current_Rate__c.field-meta.xml
<CustomField>
    <fullName>Current_Rate__c</fullName>
    <label>First Loan Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Estimated_Value__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Value__c</fullName>
    <label>Est Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/First_Loan_Amount_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_1__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/First_Loan_Amount_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_2__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/First_Loan_Amount_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_3__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Loan_Program_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>Loan_Program_Scenario_1__c</fullName>
    <label>Loan Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loan_Program_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Loan_Program_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>Loan_Program_Scenario_2__c</fullName>
    <label>Loan Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loan_Program_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Loan_Program_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>Loan_Program_Scenario_3__c</fullName>
    <label>Loan Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CF30</fullName>
            </value>
            <value>
                <fullName>CF25</fullName>
            </value>
            <value>
                <fullName>CF20</fullName>
            </value>
            <value>
                <fullName>CF15</fullName>
            </value>
            <value>
                <fullName>CF10</fullName>
            </value>
            <value>
                <fullName>HB30</fullName>
            </value>
            <value>
                <fullName>HB25</fullName>
            </value>
            <value>
                <fullName>HB20</fullName>
            </value>
            <value>
                <fullName>HB15</fullName>
            </value>
            <value>
                <fullName>HB10</fullName>
            </value>
            <value>
                <fullName>JF30</fullName>
            </value>
            <value>
                <fullName>JF15</fullName>
            </value>
            <value>
                <fullName>FHA 30</fullName>
            </value>
            <value>
                <fullName>FHA 15</fullName>
            </value>
            <value>
                <fullName>VA 30</fullName>
            </value>
            <value>
                <fullName>VA 15</fullName>
            </value>
            <value>
                <fullName>C 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>FHA 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>VA 5-1 ARM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/LTV_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>LTV_Scenario_2__c</fullName>
    <formula>First_Loan_Amount_Scenario_2__c / Estimated_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LTV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LTV_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>LTV_Scenario_3__c</fullName>
    <formula>First_Loan_Amount_Scenario_3__c / Estimated_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LTV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Monthly_Payment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Payment__c</fullName>
    <formula>First_Loan_Amount_Scenario_1__c *(  Rate_Scenario_1__c /12)*((1+(  Rate_Scenario_1__c /12))^  (Term_Due__c * 12)) /(((1+(  Rate_Scenario_1__c /12))^  (Term_Due__c * 12)) -1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Monthly_Payment_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Payment_Scenario_2__c</fullName>
    <formula>First_Loan_Amount_Scenario_2__c *( Rate_Scenario_2__c /12)*((1+( Rate_Scenario_2__c /12))^ (Term_Due_Scenario_2__c * 12)) /(((1+( Rate_Scenario_2__c /12))^ (Term_Due_Scenario_2__c * 12)) -1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Monthly_Payment_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Payment_Scenario_3__c</fullName>
    <formula>First_Loan_Amount_Scenario_3__c *( Rate_Scenario_3__c /12)*((1+( Rate_Scenario_3__c /12))^ (Term_Due_Scenario_3__c * 12)) /(((1+( Rate_Scenario_3__c /12))^ (Term_Due_Scenario_3__c * 12)) -1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label>No Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Occupancy__c.field-meta.xml
<CustomField>
    <fullName>Occupancy__c</fullName>
    <label>Occupancy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>Refi_No_Cashout</fullName>
                <label>Refinance - No Cash Out</label>
            </value>
            <value>
                <fullName>Refi_Cashout</fullName>
                <label>Refinance - Cash Out</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Purpose_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>Purpose_Scenario_1__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Refinance - No Cash Out</fullName>
            </value>
            <value>
                <fullName>Refinance - Cash Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Rate_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>Rate_Scenario_1__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Rate_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>Rate_Scenario_2__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Rate_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>Rate_Scenario_3__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Subject_Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Subject_Property_Type__c</fullName>
    <label>Prop Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Property_Types_Lead</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Term_Due__c.field-meta.xml
<CustomField>
    <fullName>Term_Due__c</fullName>
    <description>Years</description>
    <label>Term/Due (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Term_Due_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>Term_Due_Scenario_2__c</fullName>
    <description>Years</description>
    <label>Term/Due (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Term_Due_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>Term_Due_Scenario_3__c</fullName>
    <description>Years</description>
    <label>Term/Due (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Total_Interest_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Scenario_1__c</fullName>
    <description>This a simple way of re-creating the “CUMIPMT” formula of Excel, it will just consider the entire term instead of a specific time period within it (ie months 60-120).</description>
    <formula>( Monthly_Payment_Scenario_1__c   *   Term_Due__c * 12)  -    First_Loan_Amount_Scenario_1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Interest Scenario 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Total_Interest_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Scenario_2__c</fullName>
    <description>This a simple way of re-creating the “CUMIPMT” formula of Excel, it will just consider the entire term instead of a specific time period within it (ie months 60-120).</description>
    <formula>(Monthly_Payment_Scenario_2__c  *   Term_Due_Scenario_2__c * 12)  -    First_Loan_Amount_Scenario_2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Interest Scenario 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Total_Interest_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Scenario_3__c</fullName>
    <description>This a simple way of re-creating the “CUMIPMT” formula of Excel, it will just consider the entire term instead of a specific time period within it (ie months 60-120).</description>
    <formula>(Monthly_Payment_Scenario_3__c  *   Term_Due_Scenario_3__c * 12) -    First_Loan_Amount_Scenario_3__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Interest Scenario 3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ScenariosPDFPageController.cls
/************************************************************************************************************
* @description : Controller of ScenariosPDFPage
* @author      : Capital S
* @date        : 2021-04-13
* **********************************************************************************************************/
public class ScenariosPDFPageController {
    public Lead leadRecord{get;set;}
    public Boolean isRefinance{get;set;}
    public String leftTableWidth{get;set;}
    public String rightTableWidth{get;set;}
    
    public ScenariosPDFPageController() {
        String recordId = ApexPages.CurrentPage().getparameters().get('id');
        leftTableWidth = 'width:0%';
        rightTableWidth = 'width:100%';
        isRefinance = false;

        if(!String.isEmpty(recordId)){
            leadRecord = [SELECT Id,Purpose__c,Occupancy__c,Subject_Property_Type__c,Number_of_Units__c,
            Estimated_Value__c,Current_Program__c,Current_Balance__c,Current_Rate__c,Current_Payment__c,
            Purpose_Scenario_1__c,Purpose_Scenario_2__c,Purpose_Scenario_3__c,
            Loan_Program_Scenario_1__c,Loan_Program_Scenario_2__c,Loan_Program_Scenario_3__c,
            Term_Due__c,Term_Due_Scenario_2__c,Term_Due_Scenario_3__c,
            First_Loan_Amount_Scenario_1__c,First_Loan_Amount_Scenario_2__c,First_Loan_Amount_Scenario_3__c,
            Rate_Scenario_1__c,Rate_Scenario_2__c,Rate_Scenario_3__c,
            LTV_Scenario_1__c,LTV_Scenario_2__c,LTV_Scenario_3__c,
            CLTV_Scenario_1__c,CLTV_Scenario_2__c,CLTV_Scenario_3__c,
            Monthly_Payment__c,Monthly_Payment_Scenario_2__c,Monthly_Payment_Scenario_3__c,
            Total_Interest_Scenario_1__c,Total_Interest_Scenario_2__c,Total_Interest_Scenario_3__c,
            Monthly_Payment_Savings__c,Monthly_Payment_Savings_Scenario_2__c,Monthly_Payment_Savings_Scenario_3__c,
            Daily_Interest_Savings__c,Daily_Interest_Savings_Scenario_2__c,Daily_Interest_Savings_Scenario_3__c,
            On_Pace_Payment_Scenario_1__c,On_Pace_Payment_Scenario_2__c,On_Pace_Payment_Scenario_3__c,
            On_Pace_Savings_Scenario_1__c,On_Pace_Savings_Scenario_2__c,On_Pace_Savings_Scenario_3__c,
            Maturity_Reduction_Scenario_1__c,Maturity_Reduction_Scenario_2__c,Maturity_Reduction_Scenario_3__c,
            Lifetime_Savings_Scenario_1__c,Lifetime_Savings_Scenario_2__c,Lifetime_Savings_Scenario_3__c
            FROM Lead WHERE Id =:recordId];
            
            if(leadRecord.Purpose__c == 'Refinance' || leadRecord.Purpose__c == 'Refi_No_Cashout' || leadRecord.Purpose__c == 'Refi_Cashout'){
                isRefinance = true;
                leftTableWidth = 'width:30%';
                rightTableWidth = 'width:70%';
            }
        }
    }
}