force-app/main/default/objects/Lead/fields/CoBorrower_FirstName__c.field-meta.xml
<CustomField>
    <fullName>CoBorrower_FirstName__c</fullName>
    <label>First Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CoBorrower_LastName__c.field-meta.xml
<CustomField>
    <fullName>CoBorrower_LastName__c</fullName>
    <label>Last Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadTriggerHelper.cls
public class LeadTriggerHelper {

    
    public static Lead replaceCompany(Lead l){
         if(String.IsBlank(l.CoBorrower_FirstName__c) && String.IsBlank(l.CoBorrower_LastName__c)){
                    l.Company = l.FirstName + ' ' + l.LastName + ' - Household';
                } else {
                    l.Company = l.FirstName + ' ' + l.LastName + ' - ' +  l.CoBorrower_FirstName__c + ' ' + l.CoBorrower_LastName__c + ' Household' ;
                }
        return l;
    }
    
}