force-app/main/default/objects/Lead/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>First Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <label>Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CONV</fullName>
            </value>
            <value>
                <fullName>FHA</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>USDA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Heloc</fullName>
            </value>
            <value>
                <fullName>ARM (BB)</fullName>
            </value>
            <value>
                <fullName>Reverse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Current_Schedule_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Schedule_Balance__c</fullName>
    <description>This field will calculate the projected remaining balance on a loan based on the loan amount, close date, interest rate, and loan program.</description>
    <formula>If( OR(IsWon, IsPickVal(StageName, &apos;Closed Elsewhere&apos;)), Loan_Amount__c+((Loan_Amount__c- Payment_Amount__c *12/  Interest_Rate_SF__c  )*EXP(( 

IF(ISBLANK(First_Payment__c), 
(YEAR(TODAY())-YEAR(CloseDate))*12+MONTH(TODAY())-MONTH(CloseDate), 
(YEAR(TODAY())-YEAR(First_Payment__c))*12+MONTH(TODAY())-MONTH(First_Payment__c)+1) 

)*LN(1+Interest_Rate_SF__c/12))+Payment_Amount__c*12/Interest_Rate_SF__c )-(( Loan_Amount__c-Payment_Amount__c*12/Interest_Rate_SF__c)*EXP((1-1)*LN(1+Interest_Rate_SF__c/12))+Payment_Amount__c*12/Interest_Rate_SF__c ), null)</formula>
    <label>Scheduled Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Due_In_Months__c.field-meta.xml
<CustomField>
    <fullName>Due_In_Months__c</fullName>
    <label>Due In Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/First_Payment__c.field-meta.xml
<CustomField>
    <fullName>First_Payment__c</fullName>
    <label>First Payment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>Salesforce Interest Rate</description>
    <label>Legacy Interest Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount with MIP, FF</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <label>Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CONV</fullName>
            </value>
            <value>
                <fullName>FHA</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>USDA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Heloc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>This field will hold the payment amount for the loan.</description>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Property_Disposition__c.field-meta.xml
<CustomField>
    <fullName>Property_Disposition__c</fullName>
    <formula>Text(Subject_Property_Name__r.Property_Disposition__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Property Disposition</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Properties__c/Properties__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Properties Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Properties__c/fields/Current_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Current_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Loan</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <formula>Most_Recent_Closed_Opportunity__r.Amount</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Most_Recent_Closed_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Closed_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Most Recent Closed Loan</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Most Recent Closed Loan</relationshipLabel>
    <relationshipName>Most_Recent_Closed_Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_Disposition__c.field-meta.xml
<CustomField>
    <fullName>Property_Disposition__c</fullName>
    <label>Property Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Paid in Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <label>Loan Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/solidify_proposalController.cls
public class solidify_proposalController {
private final static Integer MAX_RESULTS = 5;

    @AuraEnabled(cacheable=true)
    public static List<LookupSearchResult> searchBorrower(String searchTerm, List<String> selectedIds) {
        
        // Prepare query paramters
        searchTerm += '*';

        // Execute search query
        List<List<SObject>> searchResults = [FIND :searchTerm IN ALL FIELDS RETURNING
            Contact (Id, Name, Email WHERE id NOT IN :selectedIds),
            Lead (Id, Name, Email WHERE id NOT IN :selectedIds AND isConverted = false)
            LIMIT :MAX_RESULTS];

        // Prepare results
        List<LookupSearchResult> results = new List<LookupSearchResult>();

        // Extract Contacts & convert them into LookupSearchResult
        String contactIcon = 'standard:contact';
        Contact [] contacts = ((List<Contact>) searchResults[0]);
        for (Contact contact : contacts) {
            results.add(new LookupSearchResult(contact.Id, 'Contact', contactIcon, Contact.Name, 'Contact • '+ contact.Email));
            
        }
        
         // Extract Leads & convert them into LookupSearchResult
        String leadIcon = 'standard:lead';
        Lead [] leads = ((List<Lead>) searchResults[1]);
        for (Lead lead : leads) {
            results.add(new LookupSearchResult(lead.Id, 'Lead', leadIcon, Lead.Name, 'Lead • '+ lead.Email));
        }


        return results;
    }
    
    @auraEnabled
    public static List<Properties__c> getPropertyList(Id contactId){
        Contact c = [SELECT Id, AccountId FROM Contact WHERE Id=:contactId LIMIT 1];
        system.debug(c.AccountId);
        
        list<Properties__c> props = [SELECT Id, Name, Property_Disposition__c FROM Properties__c WHERE Household__c = :c.AccountId];
        system.debug(props);
        return props;
		        
    }
    
    @auraEnabled
    public static Contact getContact(Id contactId){
        Contact c = [SELECT id, FirstName, LastName, AccountId FROM Contact WHERE Id=:contactId LIMIT 1];
        return c;
    }
    
    @auraEnabled
    public static Opportunity getLoanForProperty(String propertyId){
        System.debug(propertyId);
        Properties__c prop = [SELECT Id, Most_Recent_Closed_Opportunity__c, Current_Opportunity__c FROM Properties__c WHERE Id = :propertyId LIMIT 1];
        
        Id oppId;
        
        If(prop.Most_Recent_Closed_Opportunity__c!=null){
            oppId = prop.Most_Recent_Closed_Opportunity__c;
        } else {
            return null;
        }
        
        return [SELECT Id, Loan_Amount__c, Amount, Payment_Amount__c, CloseDate, Loan_Type__c, Interest_Rate__c, Current_Schedule_Balance__c, Due_In_Months__c, First_Payment__c FROM Opportunity WHERE Id = :oppId];
    }
    
    @auraEnabled
    public static Contact getContactForProperty(String propertyId){
        Properties__c prop = [SELECT Id, Household__c FROM Properties__c WHERE Id = :propertyId];
        
        Contact c = [SELECT Id, FirstName, LastName, AccountId FROM Contact WHERE AccountId = :prop.Household__c LIMIT 1];
        return c;
        
    }
    
    @auraEnabled
    public static Properties__c getPropertyInfo(String propertyId){
    	Properties__c prop = [SELECT Id, Name FROM Properties__c WHERE Id = :propertyId];
        
        return prop;
    }
    
    @auraEnabled
    public static Contact getContactById(String contactId){
        return [SELECT FirstName, LastName, Id, AccountId FROM Contact WHERE Id = :contactId LIMIT 1];
    }
    
    @auraEnabled
    public static decimal getLoanBalance(decimal loanAmt, decimal interestRate, integer numberPayments, decimal payment ){
        system.debug('loanAmt: ' + loanAmt);
        system.debug('interestRate: ' + interestRate);
        system.debug('numberPayments: ' + numberPayments);
        system.debug('payment: ' + payment);
        return solidifyUtil.balance(loanAmt, interestRate, numberPayments, payment);
    }

    @AuraEnabled
    public static String saveProposalRecord(Proposal__c newProposal){
        insert newProposal;
        return newProposal.Id;
    }
}