force-app/main/default/objects/Lead/fields/Loan_Originator__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator__c</fullName>
    <label>Loan Originator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dusty Broderick</fullName>
            </value>
            <value>
                <fullName>Missy Broderick</fullName>
            </value>
            <value>
                <fullName>Robert Salas</fullName>
            </value>
            <value>
                <fullName>Tiffany Attwood</fullName>
            </value>
            <value>
                <fullName>Andy Hess</fullName>
            </value>
            <value>
                <fullName>Joe Rivera</fullName>
            </value>
            <value>
                <fullName>Louis Bing</fullName>
            </value>
            <value>
                <fullName>Cole Annati</fullName>
            </value>
            <value>
                <fullName>Brandon Kyle</fullName>
            </value>
            <value>
                <fullName>Steve McKnight</fullName>
            </value>
            <value>
                <fullName>Logan Tyler</fullName>
                <isActive>false</isActive>
                <label>Logan Tyler</label>
            </value>
            <value>
                <fullName>Sherman Chaplin</fullName>
                <isActive>false</isActive>
                <label>Sherman Chaplin</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Loan_Originator_User__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Originator User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LO_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/leadOriginatorTest.cls
@isTest
public class leadOriginatorTest {
    @isTest
    public static void testInsert() {        
        Lead lead = new Lead(FirstName = 'Test', LastName = 'Tester', Loan_Originator__c = 'Dusty Broderick');
        insert lead;
        Lead newLead = [SELECT Id, Loan_Originator_User__c FROM Lead WHERE FirstName = 'Test'];
        User newUser = [SELECT ID FROM User WHERE FirstName = 'Dusty' AND LastName = 'Broderick'];
        System.assertEquals(newUser.Id, newLead.Loan_Originator_User__c);
    }
    @isTest
    public static void testUpdate() {
        Lead lead = new Lead(FirstName = 'Test', LastName = 'Tester');
        insert lead;
        lead.Loan_Originator__c = 'Dusty Broderick';
        update lead;
        Lead newLead = [SELECT Id, Loan_Originator_User__c FROM Lead WHERE FirstName = 'Test'];
        User newUser = [SELECT ID FROM User WHERE FirstName = 'Dusty' AND LastName = 'Broderick'];
        System.assertEquals(newUser.Id, newLead.Loan_Originator_User__c);
    }
    
}