force-app/main/default/objects/Lead/fields/Loan_Originator__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator__c</fullName>
    <label>Loan Originator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dusty Broderick</fullName>
            </value>
            <value>
                <fullName>Missy Broderick</fullName>
            </value>
            <value>
                <fullName>Robert Salas</fullName>
            </value>
            <value>
                <fullName>Tiffany Attwood</fullName>
            </value>
            <value>
                <fullName>Andy Hess</fullName>
            </value>
            <value>
                <fullName>Joe Rivera</fullName>
            </value>
            <value>
                <fullName>Louis Bing</fullName>
            </value>
            <value>
                <fullName>Cole Annati</fullName>
            </value>
            <value>
                <fullName>Brandon Kyle</fullName>
            </value>
            <value>
                <fullName>Steve McKnight</fullName>
            </value>
            <value>
                <fullName>Logan Tyler</fullName>
                <isActive>false</isActive>
                <label>Logan Tyler</label>
            </value>
            <value>
                <fullName>Sherman Chaplin</fullName>
                <isActive>false</isActive>
                <label>Sherman Chaplin</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Loan_Originator_User__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Originator User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LO_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/leadOriginatorHandler.cls
public class leadOriginatorHandler {
    public static void onInsert(List<Lead> leadList) {
        Map<String, Id> userMap = new Map<String, Id>();
        for (User newUser : [SELECT ID, FirstName, LastName FROM USER]) {
            String userName = newUSer.FirstName + ' ' + newUser.LastName;
            userMap.put(userName, newUser.Id);
        }
        for(Lead lead : leadList) {
            lead.Loan_Originator_User__c = userMap.get(lead.Loan_Originator__c);           
        }
        
    }
    public static void onUpdate(List<Lead> leadList, Map<Id, Lead> oldMap) {
        Map<String, Id> userMap = new Map<String, Id>();
        for (User newUser : [SELECT ID, FirstName, LastName FROM USER]) {
            String userName = newUSer.FirstName + ' ' + newUser.LastName;
            userMap.put(userName, newUser.Id);
        }
        
        for(Lead lead : leadList) {
            if(lead.Loan_Originator__c != oldMap.get(lead.Id).Loan_Originator__c) {
                lead.Loan_Originator_User__c = userMap.get(lead.Loan_Originator__c);                
            }
        }       
    }

}