force-app/main/default/objects/Opportunity/fields/COE__c.field-meta.xml
<CustomField>
    <fullName>COE__c</fullName>
    <label>COE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subject_Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Property_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject Property Name</label>
    <referenceTo>Properties__c</referenceTo>
    <relationshipLabel>Related Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Properties__c/Properties__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Properties Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Properties__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Detached</fullName>
                <default>true</default>
                <label>Detached</label>
            </value>
            <value>
                <fullName>Condominium</fullName>
                <label>Condo</label>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Detached Condominium</fullName>
            </value>
            <value>
                <fullName>Manufactured Home</fullName>
            </value>
            <value>
                <fullName>High Rise Condominium</fullName>
            </value>
            <value>
                <fullName>Modular/Pre-Fab</fullName>
            </value>
            <value>
                <fullName>Cooperative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScenarioLoanDetailControllerTest.cls
@isTest
public class ScenarioLoanDetailControllerTest {

	@TestSetup
	static void setup() {
		insert new Properties__c(Property_Type__c = 'Test property');
        
	}

	@isTest
	static void validateGetPropertyTypePicklist() {
		Schema.DescribeFieldResult fieldResult = Properties__c.Property_Type__c.getDescribe();
		Map<String, String> result = ScenarioLoanDetailController.getPropertyTypePicklist();
		List<Schema.PicklistEntry> pValues = fieldResult.getPicklistValues();
		for (Schema.PicklistEntry p: pValues) {
			System.assertEquals(p.getLabel(), result.get(p.getValue()));
		}
	}

	@isTest
	static void validateUpdateProperties() {
		Properties__c properties = [SELECT Id, Property_Type__c FROM Properties__c WHERE Property_Type__c =: 'Test property'];
		ScenarioLoanDetailController.updateProperties(null, properties.Id, 'Detached');

		Properties__c properties2 = [SELECT Id, Property_Type__c FROM Properties__c WHERE Id =: properties.Id];
		System.assertEquals('Detached', properties2.Property_Type__c);
	}
    
    @isTest
	static void updatePropertiesTest() {
        Opportunity opp = new Opportunity(Name = 'Test Account', StageName = 'Won', COE__c = Date.today().addDays(5));
        insert opp;
		Properties__c properties = [SELECT Id, Property_Type__c FROM Properties__c WHERE Property_Type__c =: 'Test property'];
		ScenarioLoanDetailController.updateProperties(opp.Id, null, 'Detached');

		Opportunity oppAfterUpdate = [SELECT Id, Subject_Property_Name__r.Property_Type__c FROM Opportunity WHERE Id =: opp.Id];
		System.assertEquals('Detached', oppAfterUpdate.Subject_Property_Name__r.Property_Type__c);
	}
}