force-app/main/default/objects/Opportunity/fields/Current_Schedule_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Schedule_Balance__c</fullName>
    <description>This field will calculate the projected remaining balance on a loan based on the loan amount, close date, interest rate, and loan program.</description>
    <formula>If( OR(IsWon, IsPickVal(StageName, &apos;Closed Elsewhere&apos;)), Loan_Amount__c+((Loan_Amount__c- Payment_Amount__c *12/  Interest_Rate_SF__c  )*EXP(( 

IF(ISBLANK(First_Payment__c), 
(YEAR(TODAY())-YEAR(CloseDate))*12+MONTH(TODAY())-MONTH(CloseDate), 
(YEAR(TODAY())-YEAR(First_Payment__c))*12+MONTH(TODAY())-MONTH(First_Payment__c)+1) 

)*LN(1+Interest_Rate_SF__c/12))+Payment_Amount__c*12/Interest_Rate_SF__c )-(( Loan_Amount__c-Payment_Amount__c*12/Interest_Rate_SF__c)*EXP((1-1)*LN(1+Interest_Rate_SF__c/12))+Payment_Amount__c*12/Interest_Rate_SF__c ), null)</formula>
    <label>Scheduled Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Due_In_Months__c.field-meta.xml
<CustomField>
    <fullName>Due_In_Months__c</fullName>
    <label>Due In Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Originator_User__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Originator User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loans_Originated</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subject_Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Property_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject Property Name</label>
    <referenceTo>Properties__c</referenceTo>
    <relationshipLabel>Related Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Scenario.recordType-meta.xml
<RecordType>
    <fullName>Scenario</fullName>
    <active>true</active>
    <businessProcess>Scenarios</businessProcess>
    <label>Scenario</label>
</RecordType>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/APRScenario1__c.field-meta.xml
<CustomField>
    <fullName>APRScenario1__c</fullName>
    <label>APR</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/APRScenario2__c.field-meta.xml
<CustomField>
    <fullName>APRScenario2__c</fullName>
    <label>APR</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/APRScenario3__c.field-meta.xml
<CustomField>
    <fullName>APRScenario3__c</fullName>
    <label>APR</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/CancelMIAtS1__c.field-meta.xml
<CustomField>
    <fullName>CancelMIAtS1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cancel MI At (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/CancelMIAtS2__c.field-meta.xml
<CustomField>
    <fullName>CancelMIAtS2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cancel MI At (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/CancelMIAtS3__c.field-meta.xml
<CustomField>
    <fullName>CancelMIAtS3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cancel MI At (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Amount__c</fullName>
    <label>Current Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/EstimatedMortgageInsuranceScenario1__c.field-meta.xml
<CustomField>
    <fullName>EstimatedMortgageInsuranceScenario1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimated Mortgage Insurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/EstimatedMortgageInsuranceScenario2__c.field-meta.xml
<CustomField>
    <fullName>EstimatedMortgageInsuranceScenario2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimated Mortgage Insurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/EstimatedMortgageInsuranceScenario3__c.field-meta.xml
<CustomField>
    <fullName>EstimatedMortgageInsuranceScenario3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimated Mortgage Insurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/First_Loan_Amount_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_1__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/First_Loan_Amount_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_2__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/First_Loan_Amount_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_3__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Most_Recent_Loan__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Number</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>New_Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/PaymentResultS1__c.field-meta.xml
<CustomField>
    <fullName>PaymentResultS1__c</fullName>
    <label>Payment Result</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/PaymentResultS2__c.field-meta.xml
<CustomField>
    <fullName>PaymentResultS2__c</fullName>
    <label>Payment Result</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/PaymentResultS3__c.field-meta.xml
<CustomField>
    <fullName>PaymentResultS3__c</fullName>
    <label>Payment Result</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Properties__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Rate_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>Rate_Scenario_1__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Rate_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>Rate_Scenario_2__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Rate_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>Rate_Scenario_3__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/SolidifyContact__c.field-meta.xml
<CustomField>
    <fullName>SolidifyContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solidify Contact</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Term_Due_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>Term_Due_Scenario_1__c</fullName>
    <description>Years</description>
    <label>Term/Due (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Term_Due_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>Term_Due_Scenario_2__c</fullName>
    <description>Years</description>
    <label>Term/Due (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Term_Due_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>Term_Due_Scenario_3__c</fullName>
    <description>Years</description>
    <label>Term/Due (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/TotalFeesS1__c.field-meta.xml
<CustomField>
    <fullName>TotalFeesS1__c</fullName>
    <formula>IF((DiscountCreditS1__c+LenderFeeS1__c+AppraisalFeeS1__c+CreditReportFeeS1__c+EscrowFeesS1__c+TitleFeeS1__c+RecordingFeeS1__c)&gt;0,DiscountCreditS1__c+LenderFeeS1__c+AppraisalFeeS1__c+CreditReportFeeS1__c+EscrowFeesS1__c+TitleFeeS1__c+RecordingFeeS1__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/TotalFeesS2__c.field-meta.xml
<CustomField>
    <fullName>TotalFeesS2__c</fullName>
    <formula>IF((DiscountCreditS2__c+LenderFeeS2__c+AppraisalFeeS2__c+CreditReportFeeS2__c+EscrowFeesS2__c+TitleFeeS2__c+RecordingFeeS2__c)&gt;0,DiscountCreditS2__c+LenderFeeS2__c+AppraisalFeeS2__c+CreditReportFeeS2__c+EscrowFeesS2__c+TitleFeeS2__c+RecordingFeeS2__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/TotalFeesS3__c.field-meta.xml
<CustomField>
    <fullName>TotalFeesS3__c</fullName>
    <formula>IF((DiscountCreditS3__c+LenderFeeS3__c+AppraisalFeeS3__c+CreditReportFeeS3__c+EscrowFeesS3__c+TitleFeeS3__c+RecordingFeeS3__c)&gt;0,DiscountCreditS3__c+LenderFeeS3__c+AppraisalFeeS3__c+CreditReportFeeS3__c+EscrowFeesS3__c+TitleFeeS3__c+RecordingFeeS3__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/UFMIPFFS1__c.field-meta.xml
<CustomField>
    <fullName>UFMIPFFS1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>UFMIP/FF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/UFMIPFFS2__c.field-meta.xml
<CustomField>
    <fullName>UFMIPFFS2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>UFMIP/FF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/UFMIPFFS3__c.field-meta.xml
<CustomField>
    <fullName>UFMIPFFS3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>UFMIP/FF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/recordTypes/Scenario.recordType-meta.xml
<RecordType>
    <fullName>Scenario</fullName>
    <active>true</active>
    <label>Scenario</label>
</RecordType>

force-app/main/default/classes/solidifyLoanComparisonCalcs.cls
//tested by ProposalTriggerTest
public class solidifyLoanComparisonCalcs {

    public static list<Proposal__c> beforeInsertCalcs (List<Proposal__c> proposals){

        List<String> oppIds = new List<String>();
        for(Proposal__c p: proposals){
            oppIds.add(p.Most_Recent_Loan__c);
        }

        Map<String, Opportunity> opps = new Map<String, Opportunity>([SELECT Id, Subject_Property_Name__c, ContactId, Loan_Originator_User__c, Current_Schedule_Balance__c, Due_In_Months__c  FROM Opportunity WHERE Id IN :oppIds]);

        for(Proposal__c p: proposals){
            if(opps.containsKey(p.Most_Recent_Loan__c)){
                Opportunity o = opps.get(p.Most_Recent_Loan__c);
                p.Term_Due_Scenario_1__c = o?.Due_In_Months__c>0 ? o?.Due_In_Months__c/12 : 30;
                p.Property__c = o?.Subject_Property_Name__c;
                p.Current_Loan_Amount__c = o?.Current_Schedule_Balance__c;
                p.Borrower__c = o?.ContactId;
                p.SolidifyContact__c = o?.Loan_Originator_User__c;
            }
        }

        return proposals;
    }

    public static list<Proposal__c> beforeUpdateCalcs (List<Proposal__c> proposals){

     /*   for(Proposal__c p: proposals){



        }
        */
        return proposals;
    }
    

    public static void afterCalcs(List<String> proposalIds) {

        List<Proposal__c> loanCompProposals = [SELECT Id, Term_Due_Scenario_1__c, Rate_Scenario_1__c, TotalFeesS1__c, First_Loan_Amount_Scenario_1__c, PaymentResultS1__c,
            Term_Due_Scenario_2__c, Rate_Scenario_2__c, TotalFeesS2__c, First_Loan_Amount_Scenario_2__c, PaymentResultS2__c, 
            Term_Due_Scenario_3__c, Rate_Scenario_3__c, TotalFeesS3__c, First_Loan_Amount_Scenario_3__c, PaymentResultS3__c,
            EstimatedMortgageInsuranceScenario1__c, CancelMIAtS1__c,UFMIPFFS1__c, 
            EstimatedMortgageInsuranceScenario2__c, CancelMIAtS2__c,UFMIPFFS2__c, 
            EstimatedMortgageInsuranceScenario3__c, CancelMIAtS3__c,UFMIPFFS3__c 
            FROM Proposal__c WHERE Id IN :proposalIds];
            
        for (Proposal__c l: loanCompProposals){

            //Scenario 1 Payment & APR
            if(l.Term_Due_Scenario_1__c != NULL && l.Rate_Scenario_1__c != NULL && l.TotalFeesS1__c != NULL && l.First_Loan_Amount_Scenario_1__c != NULL) {
                l.PaymentResultS1__c = solidifyUtil.payment(l.First_Loan_Amount_Scenario_1__c, l.Rate_Scenario_1__c, integer.ValueOf(l.Term_Due_Scenario_1__c));
                Double paymentForAPR1 = l.PaymentResultS1__c + ( nz(l.EstimatedMortgageInsuranceScenario1__c) - nz(l.CancelMIAtS1__c));
                system.debug(l.First_Loan_Amount_Scenario_1__c + ':'+ l.UFMIPFFS1__c +':' +l.TotalFeesS1__c);
                Double pvForAPR1 = l.First_Loan_Amount_Scenario_1__c - nz(l.UFMIPFFS1__c) - l.TotalFeesS1__c;
                l.APRScenario1__c = solidifyUtil.effectiveRate(l.Term_Due_Scenario_1__c, paymentForAPR1, pvForAPR1, l.Rate_Scenario_1__c);
            }   

            //Scenario 2 Payment & APR
            if(l.Term_Due_Scenario_2__c != NULL && l.Rate_Scenario_2__c != NULL && l.TotalFeesS2__c != NULL && l.First_Loan_Amount_Scenario_2__c != NULL) {
                l.PaymentResultS2__c = solidifyUtil.payment(l.First_Loan_Amount_Scenario_2__c, l.Rate_Scenario_2__c, integer.valueOf(l.Term_Due_Scenario_2__c));
                Double paymentForAPR2 = l.PaymentResultS2__c + ( nz(l.EstimatedMortgageInsuranceScenario2__c) - nz(l.CancelMIAtS2__c));
                Double pvForAPR2 = l.First_Loan_Amount_Scenario_2__c - nz(l.UFMIPFFS2__c) - l.TotalFeesS2__c;
                l.APRScenario2__c = solidifyUtil.effectiveRate(l.Term_Due_Scenario_2__c, paymentForAPR2, pvForAPR2, l.Rate_Scenario_2__c);
            }   

            //Scenario 3 Payment & APR
            if(l.Term_Due_Scenario_3__c != NULL && l.Rate_Scenario_3__c != NULL && l.TotalFeesS3__c != NULL && l.First_Loan_Amount_Scenario_3__c != NULL) {
                l.PaymentResultS3__c = solidifyUtil.payment(l.First_Loan_Amount_Scenario_3__c, l.Rate_Scenario_3__c, integer.ValueOf(l.Term_Due_Scenario_3__c));
                Double paymentForAPR3 = l.PaymentResultS3__c + ( nz(l.EstimatedMortgageInsuranceScenario3__c) - nz(l.CancelMIAtS3__c) );
                Double pvForAPR3 = l.First_Loan_Amount_Scenario_3__c - nz(l.UFMIPFFS3__c) - l.TotalFeesS3__c;
                l.APRScenario3__c = solidifyUtil.effectiveRate(l.Term_Due_Scenario_3__c, paymentForAPR3, pvForAPR3, l.Rate_Scenario_3__c);
            }   

        }
        update loanCompProposals;
    }    
    
    public static decimal nz(decimal input){
        if(input == null){
            return 0;
        } else {
            return input;
        }
    }
}