force-app/main/default/objects/Opportunity/fields/Hold_Until__c.field-meta.xml
<CustomField>
    <fullName>Hold_Until__c</fullName>
    <label>Silence Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rush_Requested__c.field-meta.xml
<CustomField>
    <fullName>Rush_Requested__c</fullName>
    <label>Expected Close</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/LoanDateSectionComponentController.cls
public class LoanDateSectionComponentController {
    
    @AuraEnabled
    public static Opportunity loadLoanRecord(String recordId){
        return [SELECT Id, Rush_Requested__c, Hold_Until__c FROM Opportunity WHERE Id =: recordId];
    }

    @AuraEnabled
    public static String updateLoanRecord(Opportunity loanRecord){
        try {
            update loanRecord;

            return 'Success';
        } catch (Exception e) {
            return 'Error: ' + e.getMessage();
        }
    }
}