force-app/main/default/objects/Opportunity/fields/Subject_Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Property_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject Property Name</label>
    <referenceTo>Properties__c</referenceTo>
    <relationshipLabel>Related Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Properties__c/Properties__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Properties Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Properties__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Detached</fullName>
                <default>true</default>
                <label>Detached</label>
            </value>
            <value>
                <fullName>Condominium</fullName>
                <label>Condo</label>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Detached Condominium</fullName>
            </value>
            <value>
                <fullName>Manufactured Home</fullName>
            </value>
            <value>
                <fullName>High Rise Condominium</fullName>
            </value>
            <value>
                <fullName>Modular/Pre-Fab</fullName>
            </value>
            <value>
                <fullName>Cooperative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScenarioLoanDetailController.cls
public with sharing class ScenarioLoanDetailController {

	@AuraEnabled
	public static Map<String, String> getPropertyTypePicklist(){
		Map<String, String> options = new Map<String, String>();

		Schema.DescribeFieldResult fieldResult = Properties__c.Property_Type__c.getDescribe();

		List<Schema.PicklistEntry> pValues = fieldResult.getPicklistValues();
		for (Schema.PicklistEntry p: pValues) {
			options.put(p.getValue(), p.getLabel());
		}

		return options;
	}

	@AuraEnabled
	public static void updateProperties(String opportunityId, String propertyId, String propertyTypeValue) {
		Properties__c properties;
        if (String.isEmpty(propertyId)) {
            properties = new Properties__c(Property_Type__c = propertyTypeValue);
        } else {
            properties = [SELECT Id, Property_Type__c FROM Properties__c WHERE Id =: propertyId];
        }
        System.debug(properties);
		if (String.isEmpty(propertyId)) {
            properties = new Properties__c(Property_Type__c = propertyTypeValue);
            System.debug(properties);
			Opportunity opportunity = [SELECT Id, Subject_Property_Name__c FROM Opportunity WHERE Id =: opportunityId];
            insert properties;
            System.debug(properties);
            opportunity.Subject_Property_Name__c = properties.Id;
            update opportunity;
            System.debug(properties);
		}
		properties.Property_Type__c = propertyTypeValue;
		update properties;
	}
}