force-app/main/default/objects/Opportunity/fields/Subject_Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Property_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject Property Name</label>
    <referenceTo>Properties__c</referenceTo>
    <relationshipLabel>Related Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Properties__c/Properties__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Properties Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Properties__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_City__c.field-meta.xml
<CustomField>
    <fullName>Property_City__c</fullName>
    <label>City</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_Street__c.field-meta.xml
<CustomField>
    <fullName>Property_Street__c</fullName>
    <label>Street</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/propertyTriggerHandler_Test.cls
@isTest
public class propertyTriggerHandler_Test {

    @testSetup
    public static void createTestData(){
        Account a = new Account(Name = 'Test Account 1');
        insert a;
        Properties__c p = new Properties__c(Household__c = a.id, Property_Street__c = '123 4th Street');
        insert p;
        Opportunity o = new Opportunity(Name = 'Loan 1', AccountId = a.id, CloseDate = Date.Today(), StageName = 'New', Subject_Property_Name__c = p.id);
        insert o;
        
        
    }
    
    @isTest
    public static void testDupeProperty(){
        Account a = [SELECT Id FROM Account LIMIT 1];
        Properties__c origProp = [SELECT Id FROM Properties__c LIMIT 1];
       
        Properties__c newProp = new Properties__c(Household__c = a.id, Property_Street__c = '123 4th Street', Property_City__c = 'San Diego');
		insert newProp;
        
        Opportunity o = [SELECT Id, Subject_Property_Name__c FROM Opportunity LIMIT 1];
        system.assertEquals(o.Subject_Property_Name__c, newProp.id);
        
        List<Properties__c> props = [SELECT Id FROM Properties__c];
        system.assertEquals(props.size(), 1);
        
    }
    
    @isTest
    public static void testNewProperty(){
        Account a = [SELECT Id FROM Account LIMIT 1];
        Properties__c origProp = [SELECT Id FROM Properties__c LIMIT 1];
       
        Properties__c newProp = new Properties__c(Household__c = a.id, Property_Street__c = '1515 88th Street', Property_City__c = 'San Diego');
		insert newProp;
        
        Opportunity o = [SELECT Id, Subject_Property_Name__c FROM Opportunity LIMIT 1];
        system.assertEquals(o.Subject_Property_Name__c, origProp.id);
        
        List<Properties__c> props = [SELECT Id FROM Properties__c];
        system.assertEquals(props.size(), 2);
        
    }
       
    
}