force-app/main/default/objects/Contact/fields/AppraisalFeeS1__c.field-meta.xml
<CustomField>
    <fullName>AppraisalFeeS1__c</fullName>
    <label>Appraisal Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CancelMIAtS1__c.field-meta.xml
<CustomField>
    <fullName>CancelMIAtS1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cancel MI At (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CopytoScenarios2and3__c.field-meta.xml
<CustomField>
    <fullName>CopytoScenarios2and3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Copy to Scenarios 2 and 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/First_Loan_Amount_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_1__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Term_Due_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>Term_Due_Scenario_1__c</fullName>
    <label>Term/Due (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Term_Due_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>Term_Due_Scenario_2__c</fullName>
    <label>Term/Due (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UFMIPFFS1__c.field-meta.xml
<CustomField>
    <fullName>UFMIPFFS1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>UFMIP/FF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subject_Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Property_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject Property Name</label>
    <referenceTo>Properties__c</referenceTo>
    <relationshipLabel>Related Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Closed.recordType-meta.xml
<RecordType>
    <fullName>Closed</fullName>
    <active>true</active>
    <businessProcess>Encompass Active</businessProcess>
    <label>Closed</label>
</RecordType>

force-app/main/default/objects/Properties__c/Properties__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Properties Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Properties__c/fields/Property_City__c.field-meta.xml
<CustomField>
    <fullName>Property_City__c</fullName>
    <label>City</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_Street__c.field-meta.xml
<CustomField>
    <fullName>Property_Street__c</fullName>
    <label>Street</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Add_Fees_to_Loan_Balance__c.field-meta.xml
<CustomField>
    <fullName>Add_Fees_to_Loan_Balance__c</fullName>
    <label>Add Fees to Loan Balance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/AppraisalFeeS1__c.field-meta.xml
<CustomField>
    <fullName>AppraisalFeeS1__c</fullName>
    <label>Appraisal Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/CancelMIAtS1__c.field-meta.xml
<CustomField>
    <fullName>CancelMIAtS1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cancel MI At (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/CopytoScenarios2and3__c.field-meta.xml
<CustomField>
    <fullName>CopytoScenarios2and3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Copy to Scenarios 2 and 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Current_Interest_Rate__c</fullName>
    <label>Current Interest Rate</label>
    <precision>17</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Amount__c</fullName>
    <label>Current Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Current_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Term__c</fullName>
    <label>Current Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Est_Fees_Lender__c.field-meta.xml
<CustomField>
    <fullName>Est_Fees_Lender__c</fullName>
    <label>Est Fees Lender</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/EstimatedMortgageInsuranceScenario1__c.field-meta.xml
<CustomField>
    <fullName>EstimatedMortgageInsuranceScenario1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimated Mortgage Insurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/First_Loan_Amount_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_1__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Fixed_Term_Years__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Term_Years__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Fixed Term Years</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Global_Pricing_Adjuster__c.field-meta.xml
<CustomField>
    <fullName>Global_Pricing_Adjuster__c</fullName>
    <inlineHelpText>For general bonuses or any instances where all pricing needs to be adjusted by the same amount.</inlineHelpText>
    <label>Global Pricing Adjuster</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Most_Recent_Loan__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Number</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>New_Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/New_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>New_Loan_Amount__c</fullName>
    <label>New Loan Amount</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/New_Loan_Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>New_Loan_Interest_Rate__c</fullName>
    <label>New Loan Interest Rate</label>
    <precision>17</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/New_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>New_Loan_Term__c</fullName>
    <label>New Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Origination_Fee__c.field-meta.xml
<CustomField>
    <fullName>Origination_Fee__c</fullName>
    <label>Compensation (LPC / BPC)</label>
    <precision>9</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Override_Comp__c.field-meta.xml
<CustomField>
    <fullName>Override_Comp__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override Comp</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/PaymentResultS1__c.field-meta.xml
<CustomField>
    <fullName>PaymentResultS1__c</fullName>
    <label>Payment Result</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Price_1__c.field-meta.xml
<CustomField>
    <fullName>Price_1__c</fullName>
    <label>Price 1</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Price_2__c.field-meta.xml
<CustomField>
    <fullName>Price_2__c</fullName>
    <label>Price 2</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Price_3__c.field-meta.xml
<CustomField>
    <fullName>Price_3__c</fullName>
    <label>Price 3</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Price_4__c.field-meta.xml
<CustomField>
    <fullName>Price_4__c</fullName>
    <label>Price 4</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Price_5__c.field-meta.xml
<CustomField>
    <fullName>Price_5__c</fullName>
    <label>Price 5</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Price_6__c.field-meta.xml
<CustomField>
    <fullName>Price_6__c</fullName>
    <label>Price 6</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Rate_1__c.field-meta.xml
<CustomField>
    <fullName>Rate_1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate 1</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Rate_2__c.field-meta.xml
<CustomField>
    <fullName>Rate_2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate 2</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Rate_3__c.field-meta.xml
<CustomField>
    <fullName>Rate_3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate 3</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Rate_4__c.field-meta.xml
<CustomField>
    <fullName>Rate_4__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate 4</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Rate_5__c.field-meta.xml
<CustomField>
    <fullName>Rate_5__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate 5</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Rate_6__c.field-meta.xml
<CustomField>
    <fullName>Rate_6__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate 6</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Rate_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>Rate_Scenario_1__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Term_Due_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>Term_Due_Scenario_1__c</fullName>
    <description>Years</description>
    <label>Term/Due (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Cost_1__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Cost 1</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Cost_2__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Cost 2</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Cost_3__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Cost 3</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Cost_4__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_4__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Cost 4</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Cost_5__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_5__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Cost 5</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Cost_6__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_6__c</fullName>
    <label>Total Cost 6</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/UFMIPFFS1__c.field-meta.xml
<CustomField>
    <fullName>UFMIPFFS1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>UFMIP/FF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProposalTriggerTest.cls
@isTest
public class ProposalTriggerTest {

    @TestSetup
    static void testData(){
        Account a = new Account(Name = 'Test Household');
        insert a;

        Contact c = new Contact(FirstName = 'Borrower', LastName = 'Test', accountId = a.Id);
        insert c;

        Properties__c p = new Properties__c(Name = 'Borrower - 1415 State Street', Property_Street__c = '1415 State Street', Property_City__c = 'San Diego' );
        insert p;

        Opportunity l = new Opportunity(Name = 'Borrower State Street Purchase', CloseDate = Date.Today().addYears(-1), StageName = 'New', AccountId = a.Id, ContactId = c.Id, Subject_Property_Name__c = p.Id );
        insert l;
        l.StageName = 'Closed Won';
        update l;

        OpportunityContactRole ocr = new OpportunityContactRole(ContactId = c.id, OpportunityId= l.id, Role = 'Borrower');
        insert ocr;
    }

    @isTest
    public static void testRefiProposal(){
        Opportunity o = [SELECT Id FROM Opportunity];
        Contact c = [SELECT Id FROM Contact];
        Proposal__c p = new Proposal__c (
            Name = 'Test', 
            recordTypeId = Constants.REFI_PROPOSAL_RECORDTYPEID, 
            Most_recent_Loan__c = o.id, 
            Borrower__c = c.id,
            Current_Loan_Amount__c = 350000,
            New_Loan_Amount__c = 250000,
            Current_Interest_Rate__c = 4.25,
            New_Loan_Interest_Rate__c = 3.75,
            Current_Loan_Term__c = 30,
            New_Loan_Term__c = 30);
        insert p;
        p.New_Loan_Amount__c = 300000;
        p.New_Loan_Interest_Rate__c = 2.75;
        p.Est_Fees_Lender__c = 2000;
        p.Global_Pricing_Adjuster__c = 0;
        p.Origination_Fee__c = 1.5;
        update p;
        
        Proposal__c newProp = [SELECT Name, New_Loan_Amount__c FROM Proposal__c];
        System.assertEquals (300000, newProp.New_Loan_Amount__c);
    }

    @isTest
    public static void testRateAnalysisProposal(){
        Opportunity o = [SELECT Id FROM Opportunity];
        Contact c = [SELECT Id FROM Contact];
        Proposal__c p = new Proposal__c (
            Name = 'Test', 
            recordTypeId = Constants.RATE_ANALYSIS_RECORDTYPEID, 
            Most_recent_Loan__c = o.id, 
            Borrower__c = c.id,
            New_Loan_Amount__c =300000,
            Fixed_Term_Years__c = 30,
            Origination_Fee__c = 1.5,
            Rate_1__c = 1.5,
            Total_Cost_1__c = 3000,
            Price_1__c = 1.2,
            Rate_2__c = 2,
            Total_Cost_2__c = 3000,
            Price_2__c = .6,
            Rate_3__c = 2.5,
            Total_Cost_3__c = 3000,
            Price_3__c = 0,
            Rate_4__c = 3,
            Total_Cost_4__c = 3000,
            Price_4__c = 0,
            Rate_5__c = 3.5,
            Total_Cost_5__c = 3000,
            Price_5__c = 0,
            Rate_6__c = 4,
            Total_Cost_6__c = 3000,
            Price_6__c = 0);

        insert p;
       
        p.Est_Fees_Lender__c = 2000;
        p.Global_Pricing_Adjuster__c = 1;   
        p.Add_Fees_to_Loan_Balance__c = 'No';
        update p;
        
        Proposal__c newProp = [SELECT Rate_6__c FROM Proposal__c];
        System.assertEquals (4, newProp.Rate_6__c);

        p.Override_Comp__c = true;
        p.Add_Fees_to_Loan_Balance__c = 'Yes';
        update p;
    }

    @isTest
    public static void testLoanCompProposal(){ 

        Opportunity o = [SELECT Id FROM Opportunity];
        Contact c = [SELECT Id FROM Contact];
        Proposal__c p = new Proposal__c (
            Name = 'Test', 
            recordTypeId = Constants.LOAN_COMP_RECORDTYPEID, 
            Most_recent_Loan__c = o.id, 
            Borrower__c = c.id,
            Term_Due_Scenario_1__c = 30,
            Rate_Scenario_1__c = 2,
            First_Loan_Amount_Scenario_1__c = 200000,
            AppraisalFeeS1__c = 2000,
            CancelMIAtS1__c = 2,
            PaymentResultS1__c = 2,
            UFMIPFFS1__c = .2,
            EstimatedMortgageInsuranceScenario1__c = 2);
        insert p;

        p.CopytoScenarios2and3__c = true;
        p.Term_Due_Scenario_2__c = 30;
        p.Rate_Scenario_2__c = 3;
        p.First_Loan_Amount_Scenario_2__c =100000;
        p.AppraisalFeeS2__c = 3000;
        p.PaymentResultS2__c = 2;
        p.UFMIPFFS2__c = .22;
        p.EstimatedMortgageInsuranceScenario2__c = 200; 
        p.CancelMIAtS2__c = 2;
        p.First_Loan_Amount_Scenario_3__c =250000;
        p.PaymentResultS3__c = 2;
        p.UFMIPFFS3__c = .2;
        p.EstimatedMortgageInsuranceScenario3__c = 2; 
        p.AppraisalFeeS3__c = 1000;
        p.CancelMIAtS3__c = 2;
        p.Term_Due_Scenario_3__c = 15;
        p.Rate_Scenario_3__c = 2;
        p.Global_Pricing_Adjuster__c = 0;
        p.Origination_Fee__c = 1.5;
        update p;
        
        Proposal__c newProp = [SELECT Origination_Fee__c FROM Proposal__c];
        System.assertEquals (1.5, newProp.Origination_Fee__c);
    }


}