force-app/main/default/objects/Contact/fields/CancelMIAtS1__c.field-meta.xml
<CustomField>
    <fullName>CancelMIAtS1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cancel MI At (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EstimatedMortgageInsuranceScenario2__c.field-meta.xml
<CustomField>
    <fullName>EstimatedMortgageInsuranceScenario2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimated Mortgage Insurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EstimatedMortgageInsuranceScenario3__c.field-meta.xml
<CustomField>
    <fullName>EstimatedMortgageInsuranceScenario3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimated Mortgage Insurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/First_Loan_Amount_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_1__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/First_Loan_Amount_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_2__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/First_Loan_Amount_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_3__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RateScenario2__c.field-meta.xml
<CustomField>
    <fullName>RateScenario2__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RateScenario3__c.field-meta.xml
<CustomField>
    <fullName>RateScenario3__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Term_Due_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>Term_Due_Scenario_1__c</fullName>
    <label>Term/Due (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Term_Due_Scenario_2__c.field-meta.xml
<CustomField>
    <fullName>Term_Due_Scenario_2__c</fullName>
    <label>Term/Due (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Term_Due_Scenario_3__c.field-meta.xml
<CustomField>
    <fullName>Term_Due_Scenario_3__c</fullName>
    <label>Term/Due (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UFMIPFFS1__c.field-meta.xml
<CustomField>
    <fullName>UFMIPFFS1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>UFMIP/FF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UFMIPFFS2__c.field-meta.xml
<CustomField>
    <fullName>UFMIPFFS2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>UFMIP/FF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ContactTrigger_Test.cls
@isTest
public class ContactTrigger_Test {
    @isTest
    public static void testUpdate(){
        Contact c = new Contact (LastName = 'Test', FirstName = 'Teddy', MailingState ='California');
        insert c;
        c.Term_Due_Scenario_1__c = 2;
        c.Rate_Scenario_1__c = 2;
        c.First_Loan_Amount_Scenario_1__c = 2;
        c.CancelMIAtS1__c = 2;
        c.PaymentResultS1__c = 2;
        c.UFMIPFFS1__c = .2;
        c.EstimatedMortgageInsuranceScenario1__c = 2; 
        c.Term_Due_Scenario_2__c = 2;
        c.RateScenario2__c = 2;
        c.First_Loan_Amount_Scenario_2__c =2;
        c.PaymentResultS2__c = 2;
        c.UFMIPFFS2__c = .22;
        c.EstimatedMortgageInsuranceScenario2__c = 2; 
        c.CancelMIAtS2__c = 2;
        c.First_Loan_Amount_Scenario_3__c =2;
        c.PaymentResultS3__c = 2;
        c.UFMIPFFS3__c = .2;
        c.EstimatedMortgageInsuranceScenario3__c = 2; 
        c.CancelMIAtS3__c = 2;
        c.Term_Due_Scenario_3__c = 2;
        c.RateScenario3__c = 2;
        c.First_Loan_Amount_Scenario_3__c =2;
        update c;
        
        Contact newContact = [SELECT LastName FROM Contact];
        System.assertEquals ('Test', newContact.LastName);
    }
    @isTest
    public static void testDelete() {
        Contact c = new Contact (LastName = 'Test', FirstName = 'Teddy');
        insert c;
        delete c;
        undelete c;
    }

}