force-app/main/default/objects/Contact/fields/Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Preferred Partner</fullName>
            </value>
            <value>
                <fullName>Fired</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
                <isActive>false</isActive>
                <label>Lead</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_2__c.field-meta.xml
<CustomField>
    <fullName>Email_2__c</fullName>
    <inlineHelpText>Generally will be a Salesforce-only email.  To be used for alternative contacting purposes or data scrub results.</inlineHelpText>
    <label>Email 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Employer_Name__c.field-meta.xml
<CustomField>
    <fullName>Employer_Name__c</fullName>
    <inlineHelpText>For Clients Only</inlineHelpText>
    <label>Employer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Ethnicity__c.field-meta.xml
<CustomField>
    <fullName>Ethnicity__c</fullName>
    <description>This field will be used to track the ethnicity of borrowers and co-borrowers.  Currently set to the number of the origination system.</description>
    <label>Ethnicity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hispanic or Latino</fullName>
            </value>
            <value>
                <fullName>Not Hispanic or Latino</fullName>
            </value>
            <value>
                <fullName>Do not wish to furnish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/FICO__c.field-meta.xml
<CustomField>
    <fullName>FICO__c</fullName>
    <label>FICO</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>This field will be used to track the gender of borrowers and co-borrowers.  Currently set to the number from the origination system.</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Greeting_Name__c.field-meta.xml
<CustomField>
    <fullName>Greeting_Name__c</fullName>
    <formula>if(not(isblank( Nickname__c)),  Nickname__c ,  FirstName )</formula>
    <label>Greeting Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Income__c.field-meta.xml
<CustomField>
    <fullName>Income__c</fullName>
    <label>Income</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Income_Sources__c.field-meta.xml
<CustomField>
    <fullName>Income_Sources__c</fullName>
    <label>Income Sources</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Income_Sources</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Loan_Originator__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator__c</fullName>
    <label>Loan Originator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dusty Broderick</fullName>
            </value>
            <value>
                <fullName>Missy Broderick</fullName>
            </value>
            <value>
                <fullName>Brandon Kyle</fullName>
            </value>
            <value>
                <fullName>Cole Annati</fullName>
            </value>
            <value>
                <fullName>Joe Rivera</fullName>
            </value>
            <value>
                <fullName>Andy Hess</fullName>
            </value>
            <value>
                <fullName>Steve McKnight</fullName>
            </value>
            <value>
                <fullName>Tiffany Attwood</fullName>
            </value>
            <value>
                <fullName>Robert Salas</fullName>
            </value>
            <value>
                <fullName>Louis Bing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <label>Nickname</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Present_Address__c.field-meta.xml
<CustomField>
    <fullName>Present_Address__c</fullName>
    <label>Present Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Present_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Present_Address_City__c</fullName>
    <label>Present Address City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Present_Address_State__c.field-meta.xml
<CustomField>
    <fullName>Present_Address_State__c</fullName>
    <label>Present Address State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Present_Address_Zip__c.field-meta.xml
<CustomField>
    <fullName>Present_Address_Zip__c</fullName>
    <label>Present Address Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <description>This field will be used to track the race of borrowers and co-borrowers.  Currently set to match the number of the origination system.</description>
    <label>Race</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>American Indian or Alaskan Native</fullName>
            </value>
            <value>
                <fullName>Asian</fullName>
            </value>
            <value>
                <fullName>Black or African American</fullName>
            </value>
            <value>
                <fullName>Native Hawaiian or Other Pacific Islander Or None Selected</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Do not wish to furnish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Referred_by__c.field-meta.xml
<CustomField>
    <fullName>Referred_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred by</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referrals Received from this Contact</relationshipLabel>
    <relationshipName>Referrals_Received</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
                <default>true</default>
                <label>Client</label>
            </value>
            <value>
                <fullName>Realtor</fullName>
            </value>
            <value>
                <fullName>Escrow Officer</fullName>
            </value>
            <value>
                <fullName>Lender AE</fullName>
            </value>
            <value>
                <fullName>Insurance Agent</fullName>
            </value>
            <value>
                <fullName>Lender_Ops</fullName>
                <label>Lender - Ops</label>
            </value>
            <value>
                <fullName>Financial Advisor</fullName>
                <label>Financial Advisor / Planner</label>
            </value>
            <value>
                <fullName>Referral Partner - Other</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Loan Originator / Broker</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Prospective LO</fullName>
            </value>
            <value>
                <fullName>Prospective TM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Veteran__c.field-meta.xml
<CustomField>
    <fullName>Veteran__c</fullName>
    <label>Veteran</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Years_on_Job__c.field-meta.xml
<CustomField>
    <fullName>Years_on_Job__c</fullName>
    <label>Years on Job</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContactDetailsComponentController.cls
public class ContactDetailsComponentController {

    @AuraEnabled
    public static Contact loadContactRecord(String recordId){
        return [SELECT Id, FirstName, LastName, Nickname__c, Greeting_Name__c, Birthdate, Age__c, Gender__c, Ethnicity__c, Race__c, Veteran__c, FICO__c, Type__c, Contact_Status__c, Email,
            Email_2__c, Home_Phone__c, Business_Phone__c, MobilePhone, Income_Sources__c, Employer_Name__c, Title, Years_on_Job__c, Income__c, LeadSource, Referred_by__c, Referred_by__r.FirstName,
            Referred_by__r.LastName, Loan_Originator__c, MailingStreet, MailingCity, MailingState, MailingPostalCode, Present_Address__c, Present_Address_City__c, Present_Address_State__c, 
            Present_Address_Zip__c, HasOptedOutOfEmail, smagicinteract__SMSOptOut__c FROM Contact WHERE Id =: recordId];
    }

    @AuraEnabled
    public static String updateContactRecord(Contact contactRecord){
        try {
            update contactRecord;

            return 'Success';
        } catch (Exception e) {
            return 'Error: ' + e.getMessage();
        }
    }

    @AuraEnabled
    public static List<PicklistWrapper> getPicklistValues(String picklistField){
        List<PicklistWrapper> plValues = new List<PicklistWrapper>();
        Schema.SObjectType objType = Schema.getGlobalDescribe().get('Contact');
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        Schema.DescribeFieldResult objFieldInfo = objDescribe.fields.getMap().get(picklistField).getDescribe();
        List<Schema.PicklistEntry> picklistvalues = objFieldInfo.getPicklistValues();
        for(Schema.PicklistEntry plv: picklistvalues) {
            PicklistWrapper plWrap = new PicklistWrapper();
            plWrap.label = plv.getLabel();
            plWrap.text = plv.getValue();
            plWrap.isDefault = plv.isDefaultValue();
            plValues.add(plWrap);
        }
        return plValues;
    }

    private final static Integer MAX_RESULTS = 5;
    @AuraEnabled(cacheable=true)
    public static List<LookupSearchResult> searchContact(String searchTerm, List<String> selectedIds, String anOptionalParam) {
        System.debug('@@@ searchContact');
        searchTerm += '*';

        List<List<SObject>> searchResults = [FIND :searchTerm IN ALL FIELDS RETURNING
        Contact (Id, Name WHERE id NOT IN :selectedIds)
            LIMIT :MAX_RESULTS];

        List<LookupSearchResult> results = new List<LookupSearchResult>();

        String contactIcon = 'standard:contact';
        Contact [] contacts = ((List<Contact>) searchResults[0]);
        System.debug('@@@ contacts: ' + contacts);
        for (Contact contact : contacts) {
            results.add(new LookupSearchResult(contact.Id, 'Contact', contactIcon, contact.Name, 'Contact • '+ contact.Name));
        }

        return results;
    }

    public class PicklistWrapper{
        @AuraEnabled public String label;
        @AuraEnabled public String text;
        @AuraEnabled public Boolean isDefault;
    }
}