force-app/main/default/objects/Contact/fields/Current_Program__c.field-meta.xml
<CustomField>
    <fullName>Current_Program__c</fullName>
    <label>Current Program</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Current_Rate__c.field-meta.xml
<CustomField>
    <fullName>Current_Rate__c</fullName>
    <label>Current Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_2__c.field-meta.xml
<CustomField>
    <fullName>Email_2__c</fullName>
    <inlineHelpText>Generally will be a Salesforce-only email.  To be used for alternative contacting purposes or data scrub results.</inlineHelpText>
    <label>Email 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Income_Sources__c.field-meta.xml
<CustomField>
    <fullName>Income_Sources__c</fullName>
    <label>Income Sources</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Income_Sources</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <label>Nickname</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label>Number of Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Occupancy__c.field-meta.xml
<CustomField>
    <fullName>Occupancy__c</fullName>
    <label>Occupancy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Referred_by__c.field-meta.xml
<CustomField>
    <fullName>Referred_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred by</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referrals Received from this Contact</relationshipLabel>
    <relationshipName>Referrals_Received</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Subject_Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Subject_Property_Type__c</fullName>
    <label>Subject Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Detached</fullName>
            </value>
            <value>
                <fullName>Multi-Family</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Detached Condominium</fullName>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Manufactured Home</fullName>
            </value>
            <value>
                <fullName>High Rise Condominium</fullName>
            </value>
            <value>
                <fullName>Modular/Pre-Fab</fullName>
            </value>
            <value>
                <fullName>Cooperative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Veteran__c.field-meta.xml
<CustomField>
    <fullName>Veteran__c</fullName>
    <label>Veteran</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Borrower_PMOC__c.field-meta.xml
<CustomField>
    <fullName>Borrower_PMOC__c</fullName>
    <inlineHelpText>Preferred Method of Communication</inlineHelpText>
    <label>PMOC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>No Preference</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_Phone__c.field-meta.xml
<CustomField>
    <fullName>Business_Phone__c</fullName>
    <label>B Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CoBorrower_Business_Phone__c.field-meta.xml
<CustomField>
    <fullName>CoBorrower_Business_Phone__c</fullName>
    <label>B Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CoBorrower_Employer__c.field-meta.xml
<CustomField>
    <fullName>CoBorrower_Employer__c</fullName>
    <label>CB Employer</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CoBorrower_Est_Income__c.field-meta.xml
<CustomField>
    <fullName>CoBorrower_Est_Income__c</fullName>
    <label>Mo Income</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CoBorrower_FirstName__c.field-meta.xml
<CustomField>
    <fullName>CoBorrower_FirstName__c</fullName>
    <label>First Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CoBorrower_Home_Phone__c.field-meta.xml
<CustomField>
    <fullName>CoBorrower_Home_Phone__c</fullName>
    <label>H Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CoBorrower_Income_Source_New__c.field-meta.xml
<CustomField>
    <fullName>CoBorrower_Income_Source_New__c</fullName>
    <inlineHelpText>Check all that apply</inlineHelpText>
    <label>Income Source</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Income_Sources</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CoBorrower_LastName__c.field-meta.xml
<CustomField>
    <fullName>CoBorrower_LastName__c</fullName>
    <label>Last Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CoBorrower_Mobile__c.field-meta.xml
<CustomField>
    <fullName>CoBorrower_Mobile__c</fullName>
    <label>Cell Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CoBorrower_Nickname__c.field-meta.xml
<CustomField>
    <fullName>CoBorrower_Nickname__c</fullName>
    <label>Nickname</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CoBorrower_PMOC__c.field-meta.xml
<CustomField>
    <fullName>CoBorrower_PMOC__c</fullName>
    <inlineHelpText>Preferred Method of Communication</inlineHelpText>
    <label>CB PMOC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>No Preference</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <label>Current Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Current_Payment__c.field-meta.xml
<CustomField>
    <fullName>Current_Payment__c</fullName>
    <label>Current Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Current_Rate__c.field-meta.xml
<CustomField>
    <fullName>Current_Rate__c</fullName>
    <label>First Loan Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email_2__c.field-meta.xml
<CustomField>
    <fullName>Email_2__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Estimated_Income__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Income__c</fullName>
    <label>Mo Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/First_Time_Homebuyer__c.field-meta.xml
<CustomField>
    <fullName>First_Time_Homebuyer__c</fullName>
    <label>First Time Homebuyer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-Borrower</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Home_Phone__c.field-meta.xml
<CustomField>
    <fullName>Home_Phone__c</fullName>
    <label>H Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Income_Sources__c.field-meta.xml
<CustomField>
    <fullName>Income_Sources__c</fullName>
    <inlineHelpText>Check all that apply</inlineHelpText>
    <label>Income Source</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Income_Sources</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <label>Nickname</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Occupancy__c.field-meta.xml
<CustomField>
    <fullName>Occupancy__c</fullName>
    <label>Occupancy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>Refi_No_Cashout</fullName>
                <label>Refinance - No Cash Out</label>
            </value>
            <value>
                <fullName>Refi_Cashout</fullName>
                <label>Refinance - Cash Out</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Qualifying_Fico__c.field-meta.xml
<CustomField>
    <fullName>Qualifying_Fico__c</fullName>
    <description>Lowest Middle Fico Score of All Borrowers</description>
    <label>Qualifying Fico</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Referred_By__c.field-meta.xml
<CustomField>
    <fullName>Referred_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Subject_Property_City__c.field-meta.xml
<CustomField>
    <fullName>Subject_Property_City__c</fullName>
    <label>Subject Property City</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Subject_Property_State__c.field-meta.xml
<CustomField>
    <fullName>Subject_Property_State__c</fullName>
    <label>Subject Property State</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Subject_Property_Street__c.field-meta.xml
<CustomField>
    <fullName>Subject_Property_Street__c</fullName>
    <label>Subject Property Street</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Subject_Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Subject_Property_Type__c</fullName>
    <label>Prop Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Property_Types_Lead</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Subject_Property_Zip__c.field-meta.xml
<CustomField>
    <fullName>Subject_Property_Zip__c</fullName>
    <label>Subject Property Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Veteran__c.field-meta.xml
<CustomField>
    <fullName>Veteran__c</fullName>
    <label>Veteran</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-Borrower</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadBorrowerDetailsController.cls
public class LeadBorrowerDetailsController {
   
    @AuraEnabled
    public static Lead loadLeadRecord(String recordId){
        return [SELECT Id, FirstName, LastName, Nickname__c, Home_Phone__c, Business_Phone__c, MobilePhone, Email, Borrower_PMOC__c, Employer__c, Estimated_Income__c, Income_Sources__c,
            CoBorrower_FirstName__c, CoBorrower_LastName__c, CoBorrower_Nickname__c, CoBorrower_Home_Phone__c, CoBorrower_Business_Phone__c, CoBorrower_Mobile__c, Email_2__c, CoBorrower_PMOC__c,
            CoBorrower_Employer__c, CoBorrower_Est_Income__c, Purpose__c, Occupancy__c, Current_Program__c, Current_Balance__c, Current_Rate__c, Current_Payment__c, CoBorrower_Income_Source_New__c,
            Qualifying_Fico__c, First_Time_Homebuyer__c, Veteran__c, Subject_Property_Street__c, Subject_Property_City__c, Subject_Property_State__c, Subject_Property_Zip__c, LeadSource, Referred_By__c,
            Referred_By__r.FirstName, Referred_By__r.LastName, Subject_Property_Type__c, Number_of_Units__c, Estimated_Value__c, TBD__c, Purchase_Price__c, Down_Payment__c, Loan_Amount__c
            FROM Lead WHERE Id =: recordId];
    }

    @AuraEnabled
    public static String updateLeadRecord(Lead leadRecord){
        try {
            update leadRecord;

            return 'Success';
        } catch (Exception e) {
            return 'Error: ' + e.getMessage();
        }
    }

    private final static Integer MAX_RESULTS = 5;
    @AuraEnabled(cacheable=true)
    public static List<LookupSearchResult> searchContact(String searchTerm, List<String> selectedIds, String anOptionalParam) {
        System.debug('@@@ searchContact');
        searchTerm += '*';

        List<List<SObject>> searchResults = [FIND :searchTerm IN ALL FIELDS RETURNING
        Contact (Id, Name WHERE id NOT IN :selectedIds)
            LIMIT :MAX_RESULTS];

        List<LookupSearchResult> results = new List<LookupSearchResult>();

        String contactIcon = 'standard:contact';
        Contact [] contacts = ((List<Contact>) searchResults[0]);
        System.debug('@@@ contacts: ' + contacts);
        for (Contact contact : contacts) {
            results.add(new LookupSearchResult(contact.Id, 'Contact', contactIcon, contact.Name, 'Contact • '+ contact.Name));
        }

        return results;
    }


    @AuraEnabled
    public static List<PicklistWrapper> getPicklistValues(String picklistField){
        List<PicklistWrapper> plValues = new List<PicklistWrapper>();
        Schema.SObjectType objType = Schema.getGlobalDescribe().get('Lead');
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        Schema.DescribeFieldResult objFieldInfo = objDescribe.fields.getMap().get(picklistField).getDescribe();
        List<Schema.PicklistEntry> picklistvalues = objFieldInfo.getPicklistValues();
        for(Schema.PicklistEntry plv: picklistvalues) {
            PicklistWrapper plWrap = new PicklistWrapper();
            plWrap.label = plv.getLabel();
            plWrap.value = plv.getValue();
            plValues.add(plWrap);
        }
        return plValues;
    }



    @AuraEnabled
	public static string getSuggestions(String input) {
        String url = 'https://maps.googleapis.com/maps/api/place/autocomplete/json?'
	            + 'input=' + EncodingUtil.urlEncode(input, 'UTF-8')
	            + '&types=address' 
            	+ '&location=33.1276035,-117.2936107&radius=1000' + getKey(); 
		system.debug(url);		        
	    String response = getResponse(url);
	    return response;
	}
    
    @AuraEnabled
	public static string getPlaceDetails(String placeId) {
     	String url = 'https://maps.googleapis.com/maps/api/place/details/json?'
	            + 'placeid=' + EncodingUtil.urlEncode(placeId, 'UTF-8')
	            + getKey(); 
	    String response = getResponse(url);
	    return response;
	}
 
	public static string getResponse(string strURL){
        HttpResponse res = new HttpResponse();
        res = fullResponse(strurl);
		String responseBody = res.getBody(); 
		return responseBody;
	}
    
    public static httpResponse fullResponse(string strURL){
        Http h = new Http();
		HttpRequest req = new HttpRequest();
		HttpResponse res = new HttpResponse();
		req.setMethod('GET');
		req.setEndpoint(strURL);
		req.setTimeout(120000);
		res = h.send(req); 
        return res;
    }
 
	public static string getKey(){
		string key = 'AIzaSyCmcGPbEA0svIjLFo5DsstJ5flthYknNGs';
		string output = '&key=' + key;	 
		return output;
	}

    public class PicklistWrapper{
        @AuraEnabled public String label;
        @AuraEnabled public String value;
    }
}