force-app/main/default/objects/Contact/fields/Days_Since_Last_Activity__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Last_Activity__c</fullName>
    <formula>IF(
AND(ISBLANK(LastActivityDate), ISBLANK(Last_Email_Date__c)),
NULL,
MIN(
IF(ISBLANK(LastActivityDate), 9999, TODAY() - LastActivityDate),
IF(ISBLANK(Last_Email_Date__c), 9999, TODAY() - Last_Email_Date__c)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Since Last Activity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Days_Since_Last_Activity_Pardot__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Last_Activity_Pardot__c</fullName>
    <label>Days Since Last Activity Pardot</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContactLastActivityPardotSched.cls
global class ContactLastActivityPardotSched implements Database.Batchable<sObject>, Schedulable {

    String query = 'SELECT Id, Days_Since_Last_Activity__c, Days_Since_Last_Activity_Pardot__c FROM Contact WHERE Days_Since_Last_Activity__c>0 Order By AccountId';

    global ContactLastActivityPardotSched() {
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {

        For(Contact c: (List<Contact>) scope){
            c.Days_Since_Last_Activity_Pardot__c = c.Days_Since_Last_Activity__c;
        }
		update scope;
        
    }

    global void finish(Database.BatchableContext BC) {
	// finish code
    }

    global void execute(SchedulableContext SC) {
 		database.executebatch(new ContactLastActivityPardotSched());
    }
    
}