force-app/main/default/objects/Contact/fields/First_Loan_Amount_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_1__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/First_Loan_Amount_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_1__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Current_Schedule_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Schedule_Balance__c</fullName>
    <description>This field will calculate the projected remaining balance on a loan based on the loan amount, close date, interest rate, and loan program.</description>
    <formula>If( OR(IsWon, IsPickVal(StageName, &apos;Closed Elsewhere&apos;)), Loan_Amount__c+((Loan_Amount__c- Payment_Amount__c *12/  Interest_Rate_SF__c  )*EXP(( 

IF(ISBLANK(First_Payment__c), 
(YEAR(TODAY())-YEAR(CloseDate))*12+MONTH(TODAY())-MONTH(CloseDate), 
(YEAR(TODAY())-YEAR(First_Payment__c))*12+MONTH(TODAY())-MONTH(First_Payment__c)+1) 

)*LN(1+Interest_Rate_SF__c/12))+Payment_Amount__c*12/Interest_Rate_SF__c )-(( Loan_Amount__c-Payment_Amount__c*12/Interest_Rate_SF__c)*EXP((1-1)*LN(1+Interest_Rate_SF__c/12))+Payment_Amount__c*12/Interest_Rate_SF__c ), null)</formula>
    <label>Scheduled Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Borrower_Lead__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/First_Loan_Amount_Scenario_1__c.field-meta.xml
<CustomField>
    <fullName>First_Loan_Amount_Scenario_1__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Most_Recent_Loan__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Number</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>New_Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/New_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>New_Loan_Amount__c</fullName>
    <label>New Loan Amount</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Loan_Amount1__c.field-meta.xml
<CustomField>
    <fullName>Total_Loan_Amount1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Loan Amount1</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/recordTypes/Refi.recordType-meta.xml
<RecordType>
    <fullName>Refi</fullName>
    <active>true</active>
    <label>Refi Analysis</label>
</RecordType>

force-app/main/default/objects/ProposalSetting__mdt/ProposalSetting__mdt.object-meta.xml
<CustomObject>
    <label>ProposalSetting</label>
    <pluralLabel>ProposalSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ProposalSetting__mdt/fields/Setting_Type__c.field-meta.xml
<CustomField>
    <fullName>Setting_Type__c</fullName>
    <label>Setting Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ComparisonAnalysisDefaultMapping</fullName>
                <default>true</default>
                <label>ComparisonAnalysisDefaultMapping</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProposalSetting__mdt/fields/Value_1__c.field-meta.xml
<CustomField>
    <fullName>Value_1__c</fullName>
    <label>Value 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProposalSetting__mdt/fields/Value_2__c.field-meta.xml
<CustomField>
    <fullName>Value_2__c</fullName>
    <label>Value 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProposalTriggerHandler.cls
/**
 * @description       : Handles trigger processing for all Proposal recordtypes.
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-09-2022
 * @last modified by  : Pamela White
 * Change log         : Consolidated all triggers and handlers, moved calculations to Util function, ripped out redundant code 
**/
public class ProposalTriggerHandler {
    
    public static void afterInsertUpdate(Set<Id> proposalIds, Map<Id, Proposal__c> oldProposalMap){
        List<Proposal__c> proposals = [SELECT Id, RecordType.DeveloperName FROM Proposal__c WHERE Id IN: proposalIds];
        
        List<String> refis = new List<String>();
        List<String> rateAnalyses = new List<String>();
        List<String> loanComparison = new List<String>();
        for(Proposal__c p: proposals){
            system.debug(p.recordTypeId);
            if(p.recordTypeId == Constants.REFI_PROPOSAL_RECORDTYPEID){
                refis.add(p.id);
            }
            if(p.recordTypeId == Constants.RATE_ANALYSIS_RECORDTYPEID){
                rateAnalyses.add(p.id);
            }
            if(p.recordTypeId == Constants.LOAN_COMP_RECORDTYPEID ){
                loanComparison.add(p.id);
            }
        }
        if(refis.size()>0){
           solidifyRefiAnalysisCalcs.afterCalcs(refis);  
        }
        if(rateAnalyses.size()>0){
	        solidifyRateAnalysisCalcs.afterCalcs(rateAnalyses);
        }
        if(loanComparison.size()>0){
            solidifyLoanComparisonCalcs.afterCalcs(loanComparison);
        }
   }
    
    public static void beforeUpdate(List<Proposal__c> proposals ){
        //calculations for refi proposals
        List<Proposal__c> refiProposals = new List<Proposal__c>();
        List<Proposal__c> rateAnalyses = new List<Proposal__c>();
        List<Proposal__c> loanComps = new List<Proposal__c>();
        for(Proposal__c p:proposals){
            system.debug(p.recordTypeId);
            if(p.recordTypeId == Constants.REFI_PROPOSAL_RECORDTYPEID){
                refiProposals.add(p);
            } else if (p.recordTypeId == Constants.LOAN_COMP_RECORDTYPEID ) {
                loanComps.add(p);
            } else if (p.recordTypeId == Constants.RATE_ANALYSIS_RECORDTYPEID) {
                rateAnalyses.add(p);
            }
        }

        if(trigger.IsInsert && loanComps.size()>0){
            loanComps = solidifyLoanComparisonCalcs.beforeInsertCalcs(loanComps);
        } else if(loanComps.size()>0){
            loanComps = solidifyLoanComparisonCalcs.beforeUpdateCalcs(loanComps);
        }
        
        if(refiProposals.size()>0){
            refiProposals = solidifyRefiAnalysisCalcs.beforeCalcs(refiProposals);
        }
        
        if(rateAnalyses.size()>0){
            rateAnalyses = solidifyRateAnalysisCalcs.beforeCalcs(rateAnalyses);
        }

    }

    public static void beforeInsert(List<proposal__c> proposals){

        List<String> borrowerIds = new List<String>();
        List<String> leadIds = new List<String>();
        List<String> oppIds = new List<String>();
        Map<String, RecordType> recordTypeMap = new Map<String, RecordType>([SELECT Id, Name FROM RecordType WHERE SobjectType = 'Proposal__c']);

        for (Proposal__c p: proposals){
            borrowerIds.add(p.Borrower__c);
            leadIds.add(p.Borrower_Lead__c);
            oppIds.add(p.Most_Recent_Loan__c);
        }
        
        Map<String, Contact> contacts;
        Map<String, Lead> leads;
        Map<String, OpportunityContactRole> loanContacts = new Map<String, OpportunityContactRole>();
        Map<String, Opportunity> opps = new Map<String, Opportunity>([SELECT Id,Current_Schedule_Balance__c FROM Opportunity WHERE Id IN :oppIds]);

        if(OppIds.size()>0){
            for( OpportunityContactRole ocr :[SELECT Id, OpportunityId, ContactId FROM OpportunityContactRole WHERE Role = 'Borrower' AND OpportunityId IN :oppIds]){
                 loanContacts.put(ocr.OpportunityId, ocr);
                 BorrowerIds.add(ocr.ContactId);
            }
        }

        if(BorrowerIds.size()>0){
            contacts = new Map<String, Contact>([SELECT Id, LastName, AccountId FROM Contact WHERE Id IN :borrowerIds]);
        }
        if(LeadIds.size()>0){
            leads = new Map<String, Lead>([SELECT Id, LastName FROM Lead WHERE Id IN :leadIds]);
        }

        for (Proposal__c p:proposals){
            String LastName = '';

            if(p.Most_Recent_Loan__c !=null && (p.RecordTypeId == Constants.RATE_ANALYSIS_RECORDTYPEID || p.RecordTypeId == Constants.LOAN_COMP_RECORDTYPEID )){
                p = transferDataFromLoan_CompAnalysis(p);
            }

            if(p.Borrower__c!=null){
                LastName = contacts.get(p.Borrower__c).LastName;
                p.Account__c = contacts.get(p.Borrower__c).AccountId;
            } else if (p.Most_Recent_Loan__c != null && loanContacts.containsKey(p.Most_Recent_Loan__c) ){
                LastName = contacts.get( loanContacts.get(p.Most_Recent_Loan__c).ContactId ).LastName;
                p.Account__c = contacts.get( loanContacts.get(p.Most_Recent_Loan__c).ContactId ).AccountId;
                p.New_Loan_Amount__c = opps.get( p.Most_Recent_Loan__c).Current_Schedule_Balance__c;
                p.First_Loan_Amount_Scenario_1__c = opps.get( p.Most_Recent_Loan__c).Current_Schedule_Balance__c;
                p.Total_Loan_Amount1__c =  opps.get( p.Most_Recent_Loan__c).Current_Schedule_Balance__c;
            } else if (p.Borrower_Lead__c !=null){
                LastName = leads.get(p.Borrower_Lead__c).LastName;
            } 
            
            if(p.Name == null || p.Name == String.valueOf(p.Id)){
                p.Name = LastName + ' - ' + recordTypeMap.get(p.recordTypeId).Name  + ' - ' + String.valueOf(Date.TODAY()) ;
            }

        }
    }

    public static Proposal__c transferDataFromLoan_CompAnalysis(Proposal__c p){
        List<ProposalSetting__mdt> settings = [SELECT Id, Value_1__c, Value_2__c 
                FROM ProposalSetting__mdt 
                WHERE Setting_Type__c = 'ComparisonAnalysisDefaultMapping'];
        Set<String> opportunityFields = new Set<String>();
        for(ProposalSetting__mdt s: settings){
                opportunityFields.add(s.Value_1__c);
        }
        String queryString = 'SELECT Id, ' + String.join(New List<String>(opportunityFields), ', ').removeEnd(', ') + ' FROM Opportunity WHERE Id = \'' + p.Most_Recent_Loan__c +'\'';
        system.debug(queryString);
        Opportunity loan = Database.Query(queryString);

        for(ProposalSetting__mdt s: settings){
            if(p.get(s.Value_2__c) == null || p.get(s.Value_2__c) == '' || p.get(s.Value_2__c)==0){
                p.put(s.Value_2__c, loan.get(s.Value_1__c));
            }
        }

        return p;

    }
}