force-app/main/default/objects/Contact/fields/Loan_Originator__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator__c</fullName>
    <label>Loan Originator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dusty Broderick</fullName>
            </value>
            <value>
                <fullName>Missy Broderick</fullName>
            </value>
            <value>
                <fullName>Brandon Kyle</fullName>
            </value>
            <value>
                <fullName>Cole Annati</fullName>
            </value>
            <value>
                <fullName>Joe Rivera</fullName>
            </value>
            <value>
                <fullName>Andy Hess</fullName>
            </value>
            <value>
                <fullName>Steve McKnight</fullName>
            </value>
            <value>
                <fullName>Tiffany Attwood</fullName>
            </value>
            <value>
                <fullName>Robert Salas</fullName>
            </value>
            <value>
                <fullName>Louis Bing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Loan_Originator_User__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Originator User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LO_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/contactOriginatorHandler.cls
public class contactOriginatorHandler {
	public static void onInsert(List<Contact> conList) {
        Map<String, Id> userMap = new Map<String, Id>();
        for (User newUser : [SELECT ID, FirstName, LastName FROM USER]) {
            String userName = newUSer.FirstName + ' ' + newUser.LastName;
            userMap.put(userName, newUser.Id);
        }
        for(Contact con : conList) {
            con.Loan_Originator_User__c = userMap.get(con.Loan_Originator__c);           
        }
        
    }
    public static void onUpdate(List<Contact> conList, Map<Id, Contact> oldMap) {
        Map<String, Id> userMap = new Map<String, Id>();
        for (User newUser : [SELECT ID, FirstName, LastName FROM USER]) {
            String userName = newUSer.FirstName + ' ' + newUser.LastName;
            userMap.put(userName, newUser.Id);
        }
        
        for(Contact con : conList) {
            if(con.Loan_Originator__c != oldMap.get(con.Id).Loan_Originator__c) {
                con.Loan_Originator_User__c = userMap.get(con.Loan_Originator__c);                
            }
        }       
    }
}