force-app/main/default/objects/Contact/fields/Loan_Originator__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator__c</fullName>
    <label>Loan Originator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dusty Broderick</fullName>
            </value>
            <value>
                <fullName>Missy Broderick</fullName>
            </value>
            <value>
                <fullName>Brandon Kyle</fullName>
            </value>
            <value>
                <fullName>Cole Annati</fullName>
            </value>
            <value>
                <fullName>Joe Rivera</fullName>
            </value>
            <value>
                <fullName>Andy Hess</fullName>
            </value>
            <value>
                <fullName>Steve McKnight</fullName>
            </value>
            <value>
                <fullName>Tiffany Attwood</fullName>
            </value>
            <value>
                <fullName>Robert Salas</fullName>
            </value>
            <value>
                <fullName>Louis Bing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Loan_Originator_User__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Originator User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LO_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/contactOriginatorTest.cls
@isTest
public class contactOriginatorTest {
    @isTest
    public static void testInsert() {        
        Contact con = new Contact(FirstName = 'Test', LastName = 'Tester', Loan_Originator__c = 'Dusty Broderick');
        insert con;
        Contact newCon = [SELECT Id, Loan_Originator_User__c FROM Contact WHERE FirstName = 'Test'];
        User newUser = [SELECT ID FROM User WHERE FirstName = 'Dusty' AND LastName = 'Broderick'];
        System.assertEquals(newUser.Id, newCon.Loan_Originator_User__c);
    }
    @isTest
    public static void testUpdate() {
        Contact con = new Contact(FirstName = 'Test', LastName = 'Tester');
        insert con;
        con.Loan_Originator__c = 'Dusty Broderick';
        update con;
        Contact newCon = [SELECT Id, Loan_Originator_User__c FROM Contact WHERE FirstName = 'Test'];
        User newUser = [SELECT ID FROM User WHERE FirstName = 'Dusty' AND LastName = 'Broderick'];
        System.assertEquals(newUser.Id, newCon.Loan_Originator_User__c);
    }
    
}