force-app/main/default/objects/Contact/fields/Loan_Originator__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator__c</fullName>
    <label>Loan Originator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dusty Broderick</fullName>
            </value>
            <value>
                <fullName>Missy Broderick</fullName>
            </value>
            <value>
                <fullName>Brandon Kyle</fullName>
            </value>
            <value>
                <fullName>Cole Annati</fullName>
            </value>
            <value>
                <fullName>Joe Rivera</fullName>
            </value>
            <value>
                <fullName>Andy Hess</fullName>
            </value>
            <value>
                <fullName>Steve McKnight</fullName>
            </value>
            <value>
                <fullName>Tiffany Attwood</fullName>
            </value>
            <value>
                <fullName>Robert Salas</fullName>
            </value>
            <value>
                <fullName>Louis Bing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Admin_Fee__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fee__c</fullName>
    <label>Admin Fee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buyout (Fee in Price)</fullName>
            </value>
            <value>
                <fullName>Charge to Borrower</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Appraisal__c.field-meta.xml
<CustomField>
    <fullName>Appraisal__c</fullName>
    <label>Appraisal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reimbursed to LO</fullName>
            </value>
            <value>
                <fullName>Reimbursed to Broker</fullName>
            </value>
            <value>
                <fullName>Paid by Client</fullName>
            </value>
            <value>
                <fullName>Expecting PIW</fullName>
            </value>
            <value>
                <fullName>PIW</fullName>
            </value>
            <value>
                <fullName>Streamline / IRRRL</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Appraisal_Contingency__c.field-meta.xml
<CustomField>
    <fullName>Appraisal_Contingency__c</fullName>
    <label>Appraisal Contingency</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approval_Expected__c.field-meta.xml
<CustomField>
    <fullName>Approval_Expected__c</fullName>
    <label>Approval Expected</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Buyers_Agent__c.field-meta.xml
<CustomField>
    <fullName>Buyers_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyers Agent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans (Buyers Agent)</relationshipLabel>
    <relationshipName>Buyers_Agent_Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CD_Out_By__c.field-meta.xml
<CustomField>
    <fullName>CD_Out_By__c</fullName>
    <label>Acknowledge CD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Co_Loan_Originator__c.field-meta.xml
<CustomField>
    <fullName>Co_Loan_Originator__c</fullName>
    <label>Co-Loan Originator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loan_Originator</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/COE__c.field-meta.xml
<CustomField>
    <fullName>COE__c</fullName>
    <label>COE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Escrow_Contact__c.field-meta.xml
<CustomField>
    <fullName>Escrow_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Escrow Officer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company</value>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Type</field>
            <operation>equals</operation>
            <value>Escrow Company</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans (Escrow Officer)</relationshipLabel>
    <relationshipName>Escrow_Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Escrows__c.field-meta.xml
<CustomField>
    <fullName>Escrows__c</fullName>
    <label>Escrows</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None Waived</fullName>
            </value>
            <value>
                <fullName>None Waived - Same Servicer</fullName>
            </value>
            <value>
                <fullName>All Waived</fullName>
            </value>
            <value>
                <fullName>See Mortgage Statement</fullName>
            </value>
            <value>
                <fullName>Insurance Only</fullName>
            </value>
            <value>
                <fullName>Taxes Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Fee_Structure__c.field-meta.xml
<CustomField>
    <fullName>Fee_Structure__c</fullName>
    <label>Fee Structure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Cost</fullName>
            </value>
            <value>
                <fullName>No Points</fullName>
            </value>
            <value>
                <fullName>Points and Fees</fullName>
            </value>
            <value>
                <fullName>Check with LO</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Conditions_In_By__c.field-meta.xml
<CustomField>
    <fullName>Final_Conditions_In_By__c</fullName>
    <label>Conditions Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Docs_In_By__c.field-meta.xml
<CustomField>
    <fullName>Initial_Docs_In_By__c</fullName>
    <label>Initial Docs Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LE_Acknowledged_By__c.field-meta.xml
<CustomField>
    <fullName>LE_Acknowledged_By__c</fullName>
    <label>Acknowledge LE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>United Wholesale</fullName>
                <label>UWM</label>
            </value>
            <value>
                <fullName>PennyMac</fullName>
            </value>
            <value>
                <fullName>Freedom Mortgage</fullName>
            </value>
            <value>
                <fullName>Flagstar</fullName>
            </value>
            <value>
                <fullName>New Rez</fullName>
            </value>
            <value>
                <fullName>The Loan Store</fullName>
            </value>
            <value>
                <fullName>Plaza</fullName>
            </value>
            <value>
                <fullName>MortgageOne</fullName>
            </value>
            <value>
                <fullName>HomeXpress</fullName>
            </value>
            <value>
                <fullName>Acra</fullName>
            </value>
            <value>
                <fullName>Kind Lending</fullName>
            </value>
            <value>
                <fullName>FBC</fullName>
            </value>
            <value>
                <fullName>NexBank</fullName>
            </value>
            <value>
                <fullName>EPM</fullName>
            </value>
            <value>
                <fullName>Quontic</fullName>
            </value>
            <value>
                <fullName>Angel Oak</fullName>
            </value>
            <value>
                <fullName>Mega Capital</fullName>
            </value>
            <value>
                <fullName>REMN</fullName>
            </value>
            <value>
                <fullName>NQM Funding</fullName>
            </value>
            <value>
                <fullName>Symmetry</fullName>
            </value>
            <value>
                <fullName>Quorum FCU</fullName>
            </value>
            <value>
                <fullName>Deephaven</fullName>
            </value>
            <value>
                <fullName>Fund Loans</fullName>
            </value>
            <value>
                <fullName>Change Wholesale</fullName>
            </value>
            <value>
                <fullName>Advancial Financial</fullName>
            </value>
            <value>
                <fullName>PRMG</fullName>
            </value>
            <value>
                <fullName>PBM</fullName>
            </value>
            <value>
                <fullName>Long Bridge</fullName>
            </value>
            <value>
                <fullName>Private Lien</fullName>
            </value>
            <value>
                <fullName>Rocket Mortgage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lender_AE__c.field-meta.xml
<CustomField>
    <fullName>Lender_AE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lender AE</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company</value>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Type</field>
            <operation>equals</operation>
            <value>Lender / Bank</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans (Lender AE)</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Contingency__c.field-meta.xml
<CustomField>
    <fullName>Loan_Contingency__c</fullName>
    <label>Loan Contingency</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Originator__c.field-meta.xml
<CustomField>
    <fullName>Loan_Originator__c</fullName>
    <label>Loan Originator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loan_Originator</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Processor__c.field-meta.xml
<CustomField>
    <fullName>Loan_Processor__c</fullName>
    <label>Loan Processor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Status_Update__c.field-meta.xml
<CustomField>
    <fullName>Loan_Status_Update__c</fullName>
    <description>(LSU) AZ only</description>
    <inlineHelpText>(LSU) AZ only</inlineHelpText>
    <label>Loan Status Update</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Goal__c.field-meta.xml
<CustomField>
    <fullName>Primary_Goal__c</fullName>
    <label>Primary Goal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Reduce Rate</fullName>
            </value>
            <value>
                <fullName>Reduce Payment</fullName>
            </value>
            <value>
                <fullName>Eliminate MI</fullName>
            </value>
            <value>
                <fullName>Pay Off Loan Faster</fullName>
            </value>
            <value>
                <fullName>Debt Consolidation</fullName>
            </value>
            <value>
                <fullName>Home Improvement</fullName>
            </value>
            <value>
                <fullName>Future Investments</fullName>
            </value>
            <value>
                <fullName>Buy Out Partner</fullName>
            </value>
            <value>
                <fullName>Other - See Notes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sellers_Agent__c.field-meta.xml
<CustomField>
    <fullName>Sellers_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sellers Agent</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company</value>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Type</field>
            <operation>equals</operation>
            <value>Realty Company</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans (Sellers Agent)</relationshipLabel>
    <relationshipName>Sellers_Agent_Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sign_Final_Docs_By__c.field-meta.xml
<CustomField>
    <fullName>Sign_Final_Docs_By__c</fullName>
    <label>Sign Final Docs</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/LoanSetupComponentController.cls
public class LoanSetupComponentController {

    @AuraEnabled
    public static Opportunity loadLoanRecord(String recordId){
        return [SELECT Id, Name, COE__c, Co_Loan_Originator__c, Initial_Docs_In_By__c, LE_Acknowledged_By__c, Loan_Status_Update__c, Appraisal_Contingency__c, Loan_Contingency__c, Approval_Expected__c, Final_Conditions_In_By__c,
        CD_Out_By__c, Sign_Final_Docs_By__c, Loan_Originator__c, Loan_Processor__c, LeadSource, Lender__c, Lender_AE__c, Lender_AE__r.FirstName, Lender_AE__r.LastName, Escrow_Contact__c, 
        Escrow_Contact__r.FirstName, Escrow_Contact__r.LastName, Buyers_Agent__c, Buyers_Agent__r.FirstName, Buyers_Agent__r.LastName, Sellers_Agent__c, Sellers_Agent__r.FirstName, Sellers_Agent__r.LastName,
        Primary_Goal__c, Appraisal__c, Escrows__c, Admin_Fee__c,Fee_Structure__c, Other_Liens_New__c, Full_VOE__c, IncomeType__c, Vesting__c, Closing_Funds__c, Referred_By__c, Referred_By__r.FirstName, Referred_By__r.LastName, 
        Purpose__c, Subject_Property_Name__r.Property_State__c, Lock_Expiration__c
        FROM Opportunity WHERE Id =: recordId];
    }

    @AuraEnabled
    public static String updateLoanRecord(Opportunity loanRecord){
        try {
            update loanRecord;

            return 'Success';
        } catch (Exception e) {
            return 'Error: ' + e.getMessage();
        }
    }

    @AuraEnabled
    public static List<PicklistWrapper> getPicklistValues(String picklistField){
        List<PicklistWrapper> plValues = new List<PicklistWrapper>();
        Schema.SObjectType objType = Schema.getGlobalDescribe().get('Opportunity');
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        Schema.DescribeFieldResult objFieldInfo = objDescribe.fields.getMap().get(picklistField).getDescribe();
        List<Schema.PicklistEntry> picklistvalues = objFieldInfo.getPicklistValues();
        for(Schema.PicklistEntry plv: picklistvalues) {
            PicklistWrapper plWrap = new PicklistWrapper();
            plWrap.label = plv.getLabel();
            plWrap.text = plv.getValue();
            plWrap.isDefault = plv.isDefaultValue();
            plValues.add(plWrap);
        }
        return plValues;
    }

    private final static Integer MAX_RESULTS = 5;
    @AuraEnabled(cacheable=true)
    public static List<LookupSearchResult> searchContact(String searchTerm, List<String> selectedIds, String anOptionalParam) {
        System.debug('@@@ searchContact');
        searchTerm += '*';

        List<List<SObject>> searchResults = [FIND :searchTerm IN ALL FIELDS RETURNING
        Contact (Id, Name WHERE id NOT IN :selectedIds)
            LIMIT :MAX_RESULTS];

        List<LookupSearchResult> results = new List<LookupSearchResult>();

        String contactIcon = 'standard:contact';
        Contact [] contacts = ((List<Contact>) searchResults[0]);
        System.debug('@@@ contacts: ' + contacts);
        for (Contact contact : contacts) {
            results.add(new LookupSearchResult(contact.Id, 'Contact', contactIcon, contact.Name, 'Contact • '+ contact.Name));
        }

        return results;
    }

    public class PicklistWrapper{
        @AuraEnabled public String label;
        @AuraEnabled public String text;
        @AuraEnabled public Boolean isDefault;
    }
}