force-app/main/default/objects/Contact/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label>Number of Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Occupancy__c.field-meta.xml
<CustomField>
    <fullName>Occupancy__c</fullName>
    <label>Occupancy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Borrower_Record__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field will only be populated when the loan is added from Salesforce - Temporary field used to create Loan Contact Relationship records.</description>
    <label>Borrower</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans (Borrower)</relationshipLabel>
    <relationshipName>Loans_Borrower</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Current_Schedule_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Schedule_Balance__c</fullName>
    <description>This field will calculate the projected remaining balance on a loan based on the loan amount, close date, interest rate, and loan program.</description>
    <formula>If( OR(IsWon, IsPickVal(StageName, &apos;Closed Elsewhere&apos;)), Loan_Amount__c+((Loan_Amount__c- Payment_Amount__c *12/  Interest_Rate_SF__c  )*EXP(( 

IF(ISBLANK(First_Payment__c), 
(YEAR(TODAY())-YEAR(CloseDate))*12+MONTH(TODAY())-MONTH(CloseDate), 
(YEAR(TODAY())-YEAR(First_Payment__c))*12+MONTH(TODAY())-MONTH(First_Payment__c)+1) 

)*LN(1+Interest_Rate_SF__c/12))+Payment_Amount__c*12/Interest_Rate_SF__c )-(( Loan_Amount__c-Payment_Amount__c*12/Interest_Rate_SF__c)*EXP((1-1)*LN(1+Interest_Rate_SF__c/12))+Payment_Amount__c*12/Interest_Rate_SF__c ), null)</formula>
    <label>Scheduled Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Days_Closed__c.field-meta.xml
<CustomField>
    <fullName>Days_Closed__c</fullName>
    <formula>If(Today()- CloseDate&lt;0,null,Today() - CloseDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Closed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/First_Payment__c.field-meta.xml
<CustomField>
    <fullName>First_Payment__c</fullName>
    <label>First Payment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>Salesforce Interest Rate</description>
    <label>Legacy Interest Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Program__c.field-meta.xml
<CustomField>
    <fullName>Loan_Program__c</fullName>
    <label>Loan Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CF30</fullName>
            </value>
            <value>
                <fullName>CF25</fullName>
            </value>
            <value>
                <fullName>CF20</fullName>
            </value>
            <value>
                <fullName>CF15</fullName>
            </value>
            <value>
                <fullName>CF10</fullName>
            </value>
            <value>
                <fullName>HB30</fullName>
            </value>
            <value>
                <fullName>HB25</fullName>
            </value>
            <value>
                <fullName>HB20</fullName>
            </value>
            <value>
                <fullName>HB15</fullName>
            </value>
            <value>
                <fullName>HB10</fullName>
            </value>
            <value>
                <fullName>JF30</fullName>
            </value>
            <value>
                <fullName>JF15</fullName>
            </value>
            <value>
                <fullName>FHA 30</fullName>
            </value>
            <value>
                <fullName>FHA 15</fullName>
            </value>
            <value>
                <fullName>VA 30</fullName>
            </value>
            <value>
                <fullName>VA 15</fullName>
            </value>
            <value>
                <fullName>C 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>FHA 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>VA 5-1 ARM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <label>Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CONV</fullName>
            </value>
            <value>
                <fullName>FHA</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>USDA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Heloc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Property_Disposition__c.field-meta.xml
<CustomField>
    <fullName>Property_Disposition__c</fullName>
    <formula>Text(Subject_Property_Name__r.Property_Disposition__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Property Disposition</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Qual_FICO__c.field-meta.xml
<CustomField>
    <fullName>Qual_FICO__c</fullName>
    <description>Minimum of Borrower and CoBorrower FICO scores</description>
    <formula>If(ISBLANK(Co_Borrower_Fico__c),Borrower_FICO__c,Min(Borrower_FICO__c, Co_Borrower_Fico__c))</formula>
    <label>Qualifying FICO</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subject_Prop_Street__c.field-meta.xml
<CustomField>
    <fullName>Subject_Prop_Street__c</fullName>
    <formula>Subject_Property_Name__r.Property_Street__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subject Prop Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Closed.recordType-meta.xml
<RecordType>
    <fullName>Closed</fullName>
    <active>true</active>
    <businessProcess>Encompass Active</businessProcess>
    <label>Closed</label>
</RecordType>

force-app/main/default/objects/Properties__c/Properties__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Properties Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Properties__c/fields/CLTV_of_Most_Recent_Closed_Loan__c.field-meta.xml
<CustomField>
    <fullName>CLTV_of_Most_Recent_Closed_Loan__c</fullName>
    <formula>Most_Recent_Closed_Opportunity__r.CLTV__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CLTV</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Lender_of_Most_Recent_Closing__c.field-meta.xml
<CustomField>
    <fullName>Lender_of_Most_Recent_Closing__c</fullName>
    <formula>TEXT( Most_Recent_Closed_Opportunity__r.Lender__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lender</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/LTV_of_Most_Recent_Closing__c.field-meta.xml
<CustomField>
    <fullName>LTV_of_Most_Recent_Closing__c</fullName>
    <formula>Most_Recent_Closed_Opportunity__r.LTV__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LTV</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Most_Recent_Closed_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Closed_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Most Recent Closed Loan</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Most Recent Closed Loan</relationshipLabel>
    <relationshipName>Most_Recent_Closed_Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label>Units</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Occupancy__c.field-meta.xml
<CustomField>
    <fullName>Occupancy__c</fullName>
    <label>Occupancy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Second</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_Disposition__c.field-meta.xml
<CustomField>
    <fullName>Property_Disposition__c</fullName>
    <label>Property Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Paid in Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Detached</fullName>
                <default>true</default>
                <label>Detached</label>
            </value>
            <value>
                <fullName>Condominium</fullName>
                <label>Condo</label>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Detached Condominium</fullName>
            </value>
            <value>
                <fullName>Manufactured Home</fullName>
            </value>
            <value>
                <fullName>High Rise Condominium</fullName>
            </value>
            <value>
                <fullName>Modular/Pre-Fab</fullName>
            </value>
            <value>
                <fullName>Cooperative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Properties__c/fields/Qual_Fico__c.field-meta.xml
<CustomField>
    <fullName>Qual_Fico__c</fullName>
    <formula>Most_Recent_Closed_Opportunity__r.Qual_FICO__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Qual Fico</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ResearchSearchController.cls
public with sharing class ResearchSearchController {
//test by solidify_researchSearchController_Test
//
    @AuraEnabled
    public static list<Properties__c> getPropertyLoans(String LoanType, String LoanProg, String InterestRate, String MinFico, String MaxFico, String MinSchedBal, String MaxSchedBal, String LoanPurpose, String LoanOccupancy, String LoanOriginator, String EarliestDate, String LatestDate, String MinDaysClosed, String sortby, String sortOrder){
        system.debug(LoanType);
        system.debug(EarliestDate);
        system.debug(LatestDate);
        String query = 'SELECT Id, Name, Household__c, Household__r.Name, Most_Recent_Closed_Opportunity__c, Most_Recent_Closed_Opportunity__r.Name, Most_Recent_Closed_Opportunity__r.Subject_Prop_Street__c, Most_Recent_Closed_Opportunity__r.Occupancy__c, '
            + 'Property_Type__c , Number_of_Units__c , Most_Recent_Closed_Opportunity__r.Loan_Type__c, Most_Recent_Closed_Opportunity__r.Loan_Program__c, Most_Recent_Closed_Opportunity__r.Current_Schedule_Balance__c, ' 
            + 'Most_Recent_Closed_Opportunity__r.Interest_Rate__c , Qual_Fico__c, LTV_of_Most_Recent_Closing__c, CLTV_of_Most_Recent_Closed_Loan__c, ' 
            + 'Lender_of_Most_Recent_Closing__c , Most_Recent_Closed_Opportunity__r.Days_Closed__c, Most_Recent_Closed_Opportunity__r.CloseDate, Most_Recent_Closed_Opportunity__r.First_Payment__c, ' 
            + 'Most_Recent_Closed_Opportunity__r.Borrower_Record__c, Most_Recent_Closed_Opportunity__r.Borrower_Record__r.Name '
            + 'FROM Properties__c '
            + 'WHERE Most_Recent_Closed_Opportunity__r.StageName = \'Closed Won\' AND Property_Disposition__c != \'Pending Sale\' AND Property_Disposition__c != \'Sold\'';
            system.debug(query);
        /*
		String query = 'SELECT Id, Name, Property_Disposition__c, Household__r.Name, Most_Recent_Closed_Opportunity__c, Most_Recent_Closed_Opportunity__r.CloseDate,' 
            + 'Most_Recent_Closed_Opportunity__r.Loan_Type__c, Most_Recent_Closed_Opportunity__r.Purpose__c, Most_Recent_Closed_Opportunity__r.Occupancy__c,' 
            + 'Most_Recent_Closed_Opportunity__r.Loan_Amount__c, Most_Recent_Closed_Opportunity__r.Interest_Rate__c, Most_Recent_Closed_Opportunity__r.Loan_Originator__c, '
            + 'Most_Recent_Closed_Opportunity__r.Current_Schedule_Balance__c, Most_Recent_Closed_Opportunity__r.Borrower_Fico__c '
            + 'Most_Recent_Closed_Opportunity__r.Borrower_Record__c, Most_Recent_Closed_Opportunity__r.Borrower_Record__r.Name '
            + 'FROM Properties__c '
            + 'WHERE Most_Recent_Closed_Opportunity__r.StageName = \'Closed Won\' AND Property_Disposition__c != \'Sold\'';
            system.debug(query);'
		*/
        if (!(String.IsBlank(LoanType) && String.IsBlank(LoanProg) && String.IsBlank(InterestRate) && String.IsBlank(LoanPurpose) && String.IsBlank(LoanOccupancy) &&
              String.IsBlank(MinFico) && String.IsBlank(MaxFico) && String.IsBlank(MinSchedBal) && String.IsBlank(MaxSchedBal) &&
              String.IsBlank(LoanOriginator) && String.IsBlank(EarliestDate) && String.IsBlank(LatestDate))) {
                  system.debug('adding to query');
            if (!String.IsBlank(LoanType) ){
                query = query + ' AND Most_Recent_Closed_Opportunity__r.Loan_Type__c = :LoanType ';
            }
            if (!String.IsBlank(LoanProg) ){
                query = query + ' AND Most_Recent_Closed_Opportunity__r.Loan_Program__c = :LoanProg ';
            }
            if (!String.IsBlank(LoanPurpose)){
                query = query + ' AND Most_Recent_Closed_Opportunity__r.Purpose__c = :LoanPurpose ';
            }
            if (!String.IsBlank(LoanOccupancy)){
                system.debug(LoanOccupancy);
                query = query + ' AND Most_Recent_Closed_Opportunity__r.Occupancy__c = :LoanOccupancy ';
            }
            if (!String.IsBlank(LoanOriginator)){
                query = query + ' AND Most_Recent_Closed_Opportunity__r.Loan_Originator__c = :LoanOriginator ';
            }
            if (!String.IsBlank(InterestRate)){
                system.debug(InterestRate);
                decimal IR = decimal.valueOf(InterestRate);
                query = query + ' AND Most_Recent_Closed_Opportunity__r.Interest_Rate__c >= :IR ';
            }
            if (!String.IsBlank(MinFico)){
                integer mnFico = integer.valueOf(MinFico);
                query = query + ' AND Most_Recent_Closed_Opportunity__r.Borrower_Fico__c >= :MnFico ';
            }
            if (!String.IsBlank(MaxFico)){
                integer mxFico = integer.valueOf(MaxFico);
                query = query + ' AND Most_Recent_Closed_Opportunity__r.Borrower_Fico__c <= :MxFico ';
            }
            if (!String.IsBlank(MinSchedBal)){
                integer mnBal = integer.valueOf(MinSchedBal);
                query = query + ' AND Most_Recent_Closed_Opportunity__r.Current_Schedule_Balance__c >= :MnBal ';
            }
            if (!String.IsBlank(MaxSchedBal)){
                integer mxBal = integer.valueOf(MaxSchedBal);
                query = query + ' AND Most_Recent_Closed_Opportunity__r.Current_Schedule_Balance__c <= :MxBal ';
            }
            if (!String.IsBlank(EarliestDate)){
                system.debug(EarliestDate);
                date Earliest = Date.valueOf(EarliestDate);
                query = query + ' AND Most_Recent_Closed_Opportunity__r.CloseDate >= :Earliest ';
            }
            if (!String.IsBlank(LatestDate) ){
                date Latest = Date.valueOf(LatestDate);
                query = query + ' AND Most_Recent_Closed_Opportunity__r.CloseDate <= :Latest ';
            }
            if (!String.IsBlank(MinDaysClosed) ){
                integer minClose = integer.valueOf(MinDaysClosed);
                query = query + ' AND Most_Recent_Closed_Opportunity__r.Days_Closed__c >= :minClose ';
            }
        }

        System.debug('@@@ sortOrder: ' + sortOrder);
        System.debug('@@@ sortby: ' + sortby);
        if( sortby != NULL && sortOrder != NULL  ){
            String finalSortBy = getSoryByField(sortby);
            query += ' ORDER BY '+ finalSortBy+' '+ sortOrder+' NULLS LAST';

            System.debug('@@@ query: ' + query);
        }

        return Database.query(query);
    }

    public static String getSoryByField(String sortby){
        switch on sortby {
            when 'householdName' {
                return 'Household__r.Name';
            }
            when 'loanFileName' {
                return 'Most_Recent_Closed_Opportunity__r.Name';
            }
            when 'subjectPropStreet' {
                return 'Most_Recent_Closed_Opportunity__r.Subject_Prop_Street__c';
            }
            when 'occupancy' {
                return 'Most_Recent_Closed_Opportunity__r.Occupancy__c';
            }
            when 'loanType' {
                return 'Most_Recent_Closed_Opportunity__r.Loan_Type__c';
            }
            when 'loanProgram' {
                return 'Most_Recent_Closed_Opportunity__r.Loan_Program__c';
            }
            when 'scheduleBal' {
                return 'Most_Recent_Closed_Opportunity__r.Current_Schedule_Balance__c';
            }
            when 'interestRate' {
                return 'Most_Recent_Closed_Opportunity__r.Interest_Rate__c';
            }
            when 'daysClosed' {
                return 'Most_Recent_Closed_Opportunity__r.Days_Closed__c';
            }
            when 'closeDate' {
                return 'Most_Recent_Closed_Opportunity__r.CloseDate';
            }
            when 'firstPayment' {
                return 'Most_Recent_Closed_Opportunity__r.First_Payment__c';
            }
            when 'Property_Type__c' {
                return 'Property_Type__c';
            }
            when 'Number_of_Units__c' {
                return 'Number_of_Units__c';
            }
            when 'Qual_Fico__c' {
                return 'Qual_Fico__c';
            }
            when 'Lender_of_Most_Recent_Closing__c' {
                return 'Lender_of_Most_Recent_Closing__c';
            }
            when else {
                return 'Household__r.Name';
            }
        }
    }
    
    @AuraEnabled
    public static list<String> getProposalTypes(){
        list<String> proposalTypes = new list<string>();
        proposalTypes.add('Refi');
        
        return proposalTypes;
    }
    
    @AuraEnabled
    public static list<String> getLoanTypes(){
        list<String> pickListValuesList = new list<String>();
        Schema.DescribeFieldResult fieldResult = Opportunity.Loan_Type__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			pickListValuesList.add(pickListVal.getLabel());
		}     
		return pickListValuesList;

    }
    
    @AuraEnabled
    public static list<String> getLoanPrograms(){
        list<String> pickListValuesList = new list<String>();
        Schema.DescribeFieldResult fieldResult = Opportunity.Loan_Program__c .getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			pickListValuesList.add(pickListVal.getLabel());
		}     
		return pickListValuesList;

    }
    
    @AuraEnabled
    public static list<String> getLoanPurposes(){
        list<String> pickListValuesList = new list<String>();
        Schema.DescribeFieldResult fieldResult = Opportunity.Purpose__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			pickListValuesList.add(pickListVal.getLabel());
		}     
		return pickListValuesList;
    }
    
    @AuraEnabled
    public static list<String> getLoanOccupancies(){
       list<String> pickListValuesList = new list<String>();
        Schema.DescribeFieldResult fieldResult = Opportunity.Occupancy__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			pickListValuesList.add(pickListVal.getLabel());
		}     
		return pickListValuesList;
    }
    
    @auraEnabled
    public static list<String> getLoanOriginators(){
      list<String> pickListValuesList = new list<String>();
   /*      Schema.DescribeFieldResult fieldResult = Opportunity.Loan_Originator__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			pickListValuesList.add(pickListVal.getLabel());
		}     */
        List<AggregateResult> results = [SELECT Loan_Originator__c FROM Opportunity GROUP BY Loan_Originator__c];
        for (AggregateResult r: results){
           pickListValuesList.add((String)r.get('Loan_Originator__c'));
        }
		return pickListValuesList;
    }
    
}