force-app/main/default/objects/Contact/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>First Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Loan_Program__c.field-meta.xml
<CustomField>
    <fullName>Loan_Program__c</fullName>
    <label>Loan Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CF30</fullName>
            </value>
            <value>
                <fullName>CF25</fullName>
            </value>
            <value>
                <fullName>CF20</fullName>
            </value>
            <value>
                <fullName>CF15</fullName>
            </value>
            <value>
                <fullName>CF10</fullName>
            </value>
            <value>
                <fullName>HB30</fullName>
            </value>
            <value>
                <fullName>HB25</fullName>
            </value>
            <value>
                <fullName>HB20</fullName>
            </value>
            <value>
                <fullName>HB15</fullName>
            </value>
            <value>
                <fullName>HB10</fullName>
            </value>
            <value>
                <fullName>JF30</fullName>
            </value>
            <value>
                <fullName>JF15</fullName>
            </value>
            <value>
                <fullName>FHA 30</fullName>
            </value>
            <value>
                <fullName>FHA 15</fullName>
            </value>
            <value>
                <fullName>VA 30</fullName>
            </value>
            <value>
                <fullName>VA 15</fullName>
            </value>
            <value>
                <fullName>C 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>FHA 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>VA 5-1 ARM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <label>Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CONV</fullName>
            </value>
            <value>
                <fullName>FHA</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>USDA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Heloc</fullName>
            </value>
            <value>
                <fullName>ARM (BB)</fullName>
            </value>
            <value>
                <fullName>Reverse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>Refi_No_Cashout</fullName>
                <label>Refinance - No Cash Out</label>
            </value>
            <value>
                <fullName>Refi_Cashout</fullName>
                <label>Refinance - Cash Out</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Appraised_Value__c.field-meta.xml
<CustomField>
    <fullName>Appraised_Value__c</fullName>
    <label>Appraised Value</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount with MIP, FF</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Program__c.field-meta.xml
<CustomField>
    <fullName>Loan_Program__c</fullName>
    <label>Loan Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CF30</fullName>
            </value>
            <value>
                <fullName>CF25</fullName>
            </value>
            <value>
                <fullName>CF20</fullName>
            </value>
            <value>
                <fullName>CF15</fullName>
            </value>
            <value>
                <fullName>CF10</fullName>
            </value>
            <value>
                <fullName>HB30</fullName>
            </value>
            <value>
                <fullName>HB25</fullName>
            </value>
            <value>
                <fullName>HB20</fullName>
            </value>
            <value>
                <fullName>HB15</fullName>
            </value>
            <value>
                <fullName>HB10</fullName>
            </value>
            <value>
                <fullName>JF30</fullName>
            </value>
            <value>
                <fullName>JF15</fullName>
            </value>
            <value>
                <fullName>FHA 30</fullName>
            </value>
            <value>
                <fullName>FHA 15</fullName>
            </value>
            <value>
                <fullName>VA 30</fullName>
            </value>
            <value>
                <fullName>VA 15</fullName>
            </value>
            <value>
                <fullName>C 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>C 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>H 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 3-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 7-1 ARM</fullName>
            </value>
            <value>
                <fullName>J 10-1 ARM</fullName>
            </value>
            <value>
                <fullName>FHA 5-1 ARM</fullName>
            </value>
            <value>
                <fullName>VA 5-1 ARM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <label>Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CONV</fullName>
            </value>
            <value>
                <fullName>FHA</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>USDA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Heloc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Price__c</fullName>
    <label>Purchase Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Refi-No Cashout</fullName>
            </value>
            <value>
                <fullName>Refi-Cashout</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Const-Perm</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Purch</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>HELOC</fullName>
            </value>
            <value>
                <fullName>HELOAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Qual_FICO__c.field-meta.xml
<CustomField>
    <fullName>Qual_FICO__c</fullName>
    <description>Minimum of Borrower and CoBorrower FICO scores</description>
    <formula>If(ISBLANK(Co_Borrower_Fico__c),Borrower_FICO__c,Min(Borrower_FICO__c, Co_Borrower_Fico__c))</formula>
    <label>Qualifying FICO</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/customLookUpController.cls
public class customLookUpController {
    @AuraEnabled
    public static List < sObject > getBorrowerList(String searchKeyWord) {

        List < sObject > borrowerList = new List < sObject > ();
        String searchKey = searchKeyWord + '%';
            
        String sQuery1 =  'select id, Name from Contact where LastName LIKE: searchKey  limit 10';
        List < sObject > lstOfRecords1 = Database.query(sQuery1);
        
        for (sObject obj1: lstOfRecords1) {
            borrowerList.add(obj1);
        }
        
        String sQuery2 =  'select id, Name from Contact where FirstName LIKE: searchKey  limit 5';
        List < sObject > lstOfRecords2 = Database.query(sQuery2);
        
        for (sObject obj2: lstOfRecords2) {
            borrowerList.add(obj2);
        }
        
        String sQuery3 =  'select id, Name from Contact where Name LIKE: searchKey  limit 5';
        List < sObject > lstOfRecords3 = Database.query(sQuery3);
        
        for (sObject obj3: lstOfRecords3) {
            borrowerList.add(obj3);
        }
 
		String sQuery4 =  'SELECT Id,Name,Status FROM Lead WHERE Status != \'Active Loan\' AND Status != \'Archived\' and LastName LIKE: searchKey  limit 10';
        List < sObject > lstOfRecords4 = Database.query(sQuery4);
        for (sObject obj4: lstOfRecords4) {
            borrowerList.add(obj4);
        }
        
        		String sQuery5 =  'SELECT Id,Name,Status FROM Lead WHERE Status != \'Active Loan\' AND Status != \'Archived\' and FirstName LIKE: searchKey  limit 5';
        List < sObject > lstOfRecords5 = Database.query(sQuery5);
        for (sObject obj5: lstOfRecords5) {
            borrowerList.add(obj5);
        }
        
        		String sQuery6 =  'SELECT Id,Name,Status FROM Lead WHERE Status != \'Active Loan\' AND Status != \'Archived\' and LastName LIKE: searchKey limit 5';
        List < sObject > lstOfRecords6 = Database.query(sQuery6);
        for (sObject obj6: lstOfRecords6) {
            borrowerList.add(obj6);
        }
     Set <sObject> recordSet = new Set <sObject>();
        recordSet.addAll(borrowerList);
        borrowerList.clear();
        borrowerList.addAll(recordSet);
    return borrowerList;
}
    
@AuraEnabled
    public static List<Opportunity> getLoanList(String contactId){
        List < Opportunity> loanList = new List < Opportunity > ();
          String sQuery =  'select id, Name,Purpose__c,Loan_Amount__c,Qual_FICO__c,Loan_Program__c,Loan_Type__c,Purchase_Price__c,Appraised_Value__c from Opportunity where ContactId=: contactId';
 
        List<Opportunity> opps = Database.query(sQuery);
        
       for (Opportunity opp : opps){
            	loanList.add(opp);
        }
  
        return loanList; 
    
    }
    
}