force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/AssetOrLiability__c.field-meta.xml
<CustomField>
    <fullName>AssetOrLiability__c</fullName>
    <label>Asset Or Liability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asset</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets-Liabilities</relationshipLabel>
    <relationshipName>AssetsLiabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/insertAssetRecord.cls
public with sharing class insertAssetRecord 
{
    @AuraEnabled
    public static List<Asset__c> saveAsset(List<Asset__c> lstAsset, ID recordID) 
    {
        try 
        {
            system.debug('List Asset Before ::: ' + lstAsset);
            system.debug('List Asset Before ::: ' + lstAsset.size());
            
            String objectName = recordId.getSObjectType().getDescribe().getName();
            System.debug('Object Name: ' + objectName);
            
            for(Asset__c ast : lstAsset)
            {
                if(objectName.equalsIgnoreCase('Opportunity'))
                {
                    ast.Loan__c = recordID;
                    ast.AssetOrLiability__c = 'Liability';
                }
                else if(objectName.equalsIgnoreCase('Lead'))
                {
                    ast.Lead__c = recordID;
                    ast.AssetOrLiability__c = 'Liability';
                }
                System.debug('Asset ::: ' + ast);
            }
            
            system.debug('List Asset After ::: ' + lstAsset);
            system.debug('List Asset After ::: ' + lstAsset.size());
            
            if(!lstAsset.IsEmpty())
            {
                insert lstAsset;
            }
            return lstAsset;                  
        }
        catch(Exception ex) 
        {
            throw new AuraHandledException(ex.getMessage());
        }
    }
}