force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/AssetOrLiability__c.field-meta.xml
<CustomField>
    <fullName>AssetOrLiability__c</fullName>
    <label>Asset Or Liability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asset</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Prospecting.recordType-meta.xml
<RecordType>
    <fullName>Prospecting</fullName>
    <active>true</active>
    <businessProcess>Prospecting</businessProcess>
    <label>Prospecting</label>
</RecordType>

force-app/main/default/classes/insertAssetRecordTest.cls
@isTest
private class insertAssetRecordTest {
    
    @isTest
    static void testSaveAsset_Opportunity() 
    {
        // Create test Opportunity
        Opportunity testOpportunity = new Opportunity(Name='Test Opportunity', StageName='Prospecting', CloseDate=Date.today());
        insert testOpportunity;
                
        List<Asset__c> testAssets = new List<Asset__c>();
        for(Integer i=0; i<5; i++) 
        {
            Asset__c asset = new Asset__c(Name='Test Asset ' + i, AssetOrLiability__c='Asset');
            testAssets.add(asset);
        }                                
                
        // Create test Lead
        Lead testLead = new Lead(FirstName='Test', LastName='Lead', Company='Test Company');
        insert testLead;
                
        List<Asset__c> testAssets1 = new List<Asset__c>();
        for(Integer i=0; i<5; i++) 
        {
            Asset__c asset = new Asset__c(Name='Test Asset ' + i, AssetOrLiability__c='Asset');
            testAssets1.add(asset);
        }
                
        Test.startTest();
        List<Asset__c> savedAssets = insertAssetRecord.saveAsset(testAssets, testOpportunity.Id);
        List<Asset__c> savedAssets1 = insertAssetRecord.saveAsset(testAssets1, testLead.Id);
        Test.stopTest();
    }    
}