force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/AssetOrLiability__c.field-meta.xml
<CustomField>
    <fullName>AssetOrLiability__c</fullName>
    <label>Asset Or Liability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asset</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SubjectPropertyNegativeNetCashFlow__c.field-meta.xml
<CustomField>
    <fullName>SubjectPropertyNegativeNetCashFlow__c</fullName>
    <label>Other Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AssetTriggerHandler.cls
public class AssetTriggerHandler {
    
    public static void handleAfterInsert(list<Asset__c> newAssets){
        Set<String> leadIds = new Set<String>();
        for(Asset__c a: newAssets){
            leadIds.add(a.Lead__c);
        }
        
        if(leadIds.size()>0){
            recalcLeadTotals(leadIds);
        }
        
    }
    
    public static void handleAfterUpdate(list<Asset__c> newAssets, Map<Id, Asset__c> oldMap){
        Set<String> leadIds = new Set<String>();
        for(Asset__c a: newAssets){
            if(a.Payment__c != oldMap.get(a.id).Payment__c){
	            leadIds.add(a.Lead__c);            
            }
            
        }
        
        if(leadIds.size()>0){
            recalcLeadTotals(leadIds);
        }
        
    }
    
    public static void recalcLeadTotals(Set<String> LeadIds){
        List<Lead> leads = [SELECT Id FROM Lead WHERE Id IN :leadIds];
        
        List<AggregateResult> results = [SELECT Count(Id) ct, Sum(Payment__c) pmt, Sum(Amount__c) amt, Lead__c, AssetOrLiability__c 
                                         FROM Asset__c WHERE Lead__c IN :leadIds
                                         GROUP BY Lead__c, AssetOrLiability__c];
		Map<String, AggregateResult> resultMap = new Map<String, AggregateResult>();
        for(AggregateResult r: results){
            String keyfields = r.get('Lead__c') + '-' + r.get('AssetOrLiability__c');
            resultMap.put(keyfields, r); 
        }     
        
        for(Lead l: leads){
            l.SubjectPropertyNegativeNetCashFlow__c = (Decimal)resultMap.get(l.id + '-Liability').get('pmt');
        }
        
        update leads;
        
    }

}