force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/AssetOrLiability__c.field-meta.xml
<CustomField>
    <fullName>AssetOrLiability__c</fullName>
    <label>Asset Or Liability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asset</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets-Liabilities</relationshipLabel>
    <relationshipName>AssetsLiabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Planned_Payment__c.field-meta.xml
<CustomField>
    <fullName>Planned_Payment__c</fullName>
    <label>Planned Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Car</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Client&apos;</defaultValue>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
                <default>true</default>
                <label>Client</label>
            </value>
            <value>
                <fullName>Escrow Officer</fullName>
            </value>
            <value>
                <fullName>Lender</fullName>
            </value>
            <value>
                <fullName>Insurance Agent</fullName>
            </value>
            <value>
                <fullName>Financial Advisor</fullName>
            </value>
            <value>
                <fullName>Referral Partner - Other</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>Salesforce Interest Rate</description>
    <label>Legacy Interest Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/AssetsController.cls
public with sharing class AssetsController 
{    
    @AuraEnabled(cacheable=true)
    public static List<Asset__c> getAssetsList(Id LoanId, String Type) 
    {
        System.debug('recordId :: ' + LoanId);
        Id r = LoanId;
        String objectAPIName = r.getSObjectType().getDescribe().getName();
        System.debug('objectAPIName :: ' + objectAPIName);
        if(objectAPIName == 'Opportunity')
        {
            return getAssetListLoan(LoanId, type);
        } 
        else if (objectAPIName == 'Lead')
        {
            return getAssetListLead(LoanId, type);
        } 
        else 
        {
            return null;
        }                    
    }
    
    /*@AuraEnabled(cacheable=true)
    public static Lead getLeadInfo(Id LoanId) 
    {
        System.debug('recordId :: ' + LoanId);
        Id r = LoanId;
        String objectAPIName = r.getSObjectType().getDescribe().getName();
        System.debug('objectAPIName :: ' + objectAPIName);
        
        if (objectAPIName == 'Lead')
        {
            return getLeadRec(LoanId);
        } 
        else 
        {
            return null;
        }                    
    }
    
    @AuraEnabled(cacheable=true)
    public static Lead getLeadRec(Id LoanId) 
    {
        System.debug('AssetListLoan :: ' + LoanId);        
        //return [SELECT Id, Name, Amount__c, AssetOrLiability__c, Lead__c, Type__c, Loan__c, Interest_Rate__c, Payment__c,Planned_Payment__c FROM Asset__c Where Loan__c = :LoanId];
        return null;
    }*/
    
    @AuraEnabled(cacheable=true)
    public static List<Asset__c> getAssetListLoan(Id LoanId, String Type) 
    {
        System.debug('AssetListLoan :: ' + LoanId);
        System.debug('AssetListLoan Type :: ' + Type);
        return [SELECT Id, Name, Amount__c, AssetOrLiability__c, 
                Lead__c, Type__c, Loan__c, Interest_Rate__c, Payment__c, 
                Planned_Payment__c FROM Asset__c Where Loan__c = :LoanId AND AssetOrLiability__c = :type ];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Asset__c> getAssetListLead(String LeadId, String Type) 
    {
        System.debug('AssetListLead :: ' + LeadId);
        System.debug('AssetListLead Type :: ' + Type);
        return [SELECT Id, Name, Amount__c, AssetOrLiability__c, Lead__c, Type__c, Loan__c, Interest_Rate__c,Payment__c,Planned_Payment__c FROM Asset__c 
                Where Lead__c = :LeadId AND AssetOrLiability__c = :type ];
    }
    
    @AuraEnabled(cacheable=true)
    public static void saveLiability(Asset__c record) 
    {
        record.AssetOrLiability__c = 'Liability';
        upsert record;
    }
    
    @AuraEnabled(cacheable=true)
    public static Asset__c getSingleAsset(string AssetId) 
    {
        return [
            SELECT Id, Name, Amount__c, AssetOrLiability__c, Lead__c, Type__c, Loan__c, Interest_Rate__c
            FROM Asset__c
            WHERE Id = :AssetId
            LIMIT 1
        ];
    }
    
    @AuraEnabled
    public static void updateAssets(List<Asset__c> assetsForUpdate) 
    {
        // Make sure we can update the database before trying to update
        if (!Schema.sObjectType.Asset__c.isUpdateable()) 
        {
            throw new SecurityException(
                'Insufficient permissions to update assets'
            );
        }
        update assetsForUpdate;
    }
    
    public class AssetUpdateException extends Exception 
    {
        
    }    
}