force-app/main/default/objects/encompass_By_EM__Data_Model__c/encompass_By_EM__Data_Model__c.object-meta.xml
<CustomObject>
    <label>Data Model</label>
    <nameField>
        <label>Data Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/encompass_By_EM__Data_Model__c/fields/encompass_By_EM__Additional_Mappings__c.field-meta.xml
<CustomField>
    <fullName>encompass_By_EM__Additional_Mappings__c</fullName>
    <label>Additional Mappings</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/encompass_By_EM__Data_Model__c/fields/encompass_By_EM__Mappings__c.field-meta.xml
<CustomField>
    <fullName>encompass_By_EM__Mappings__c</fullName>
    <label>Mappings</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Adjustments_Other_Credits__c.field-meta.xml
<CustomField>
    <fullName>Adjustments_Other_Credits__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Available on the LE and CD, typically includes items paid by others such as tax prorations</inlineHelpText>
    <label>Adjustments &amp; Other Credits</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Appraisal_Required__c.field-meta.xml
<CustomField>
    <fullName>Appraisal_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Appraisal Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Credit_Supplement_Required__c.field-meta.xml
<CustomField>
    <fullName>Credit_Supplement_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Credit Supplement Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/encompass_By_EM__Encompass_Loan_Id__c.field-meta.xml
<CustomField>
    <fullName>encompass_By_EM__Encompass_Loan_Id__c</fullName>
    <externalId>true</externalId>
    <label>Encompass Loan Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/encompass_By_EM__Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>encompass_By_EM__Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Escrows_Waived__c.field-meta.xml
<CustomField>
    <fullName>Escrows_Waived__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is the field synced to Point.  Values are true/false.  Use the Escrows_Waived_Formula__c field for user-friendly values.</description>
    <label>Escrows Waived Checkbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Evidence_of_Insurance_Required__c.field-meta.xml
<CustomField>
    <fullName>Evidence_of_Insurance_Required__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Insurance Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/First_Time_Homebuyer__c.field-meta.xml
<CustomField>
    <fullName>First_Time_Homebuyer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>First Time Homebuyer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/HOA_Docs_Required__c.field-meta.xml
<CustomField>
    <fullName>HOA_Docs_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HOA Docs Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Override_Stage_Change__c.field-meta.xml
<CustomField>
    <fullName>Override_Stage_Change__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Admin override for Stages that would otherwise be reset because of Point</inlineHelpText>
    <label>Override Stage Change</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payoff_Required__c.field-meta.xml
<CustomField>
    <fullName>Payoff_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payoff Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RateSheet_Checkbox__c.field-meta.xml
<CustomField>
    <fullName>RateSheet_Checkbox__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RateSheet_Checkbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Send_Gift_Required__c.field-meta.xml
<CustomField>
    <fullName>Send_Gift_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Gift Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subordination_Required__c.field-meta.xml
<CustomField>
    <fullName>Subordination_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Subordination Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Title_Required__c.field-meta.xml
<CustomField>
    <fullName>Title_Required__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Title Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Update_Loan_File_Team__c.field-meta.xml
<CustomField>
    <fullName>Update_Loan_File_Team__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Update Loan File Team</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/VOE_Required__c.field-meta.xml
<CustomField>
    <fullName>VOE_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VOE Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/X2nd_Payoff_Required__c.field-meta.xml
<CustomField>
    <fullName>X2nd_Payoff_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>2nd Payoff Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/tst_encompass_trigger_Loan.cls
@isTest(SeeAllData=true)
public class tst_encompass_trigger_Loan {
	@isTest 
	static void testTrigger() {
		String recordTypeId;
		List<encompass_By_EM__Data_Model__c> dataModels = [SELECT Id, encompass_By_EM__Mappings__c, encompass_By_EM__Additional_Mappings__c FROM encompass_By_EM__Data_Model__c];
		for(encompass_By_EM__Data_Model__c record : dataModels) {
			String mappingsJsonString = String.isBlank(record.encompass_By_EM__Additional_Mappings__c) ? record.encompass_By_EM__Mappings__c : record.encompass_By_EM__Mappings__c + record.encompass_By_EM__Additional_Mappings__c;
			Map<String, Object> mappings = (Map<String, Object>)JSON.deserializeUntyped(mappingsJsonString);
			String primaryObjectName = (String)mappings.get('objectName');
			if(primaryObjectName == 'Opportunity') {
				Map<String, Object> recordTypeMapping = (Map<String, Object>)(((List<Object>)mappings.get('recordTypeMappings'))[0]);
				recordTypeId = (String)recordTypeMapping.get('recordType');
				break;
			}
		}
		Test.setMock(HttpCalloutMock.class, new encompass_By_EM.mockCalloutGeneratorForTrigger());
		Test.startTest();
			Schema.SObjectType objType0 = Schema.Opportunity.getSObjectType();
			SObject obj0 = objType0.newSObject();
			obj0.put('IsPrivate', true);
			obj0.put('Name', 's');
			obj0.put('StageName', 'New');
			obj0.put('CloseDate', Date.today());
			SObject userSObject0 = Schema.User.getSObjectType().newSObject();
			userSObject0.put('Id', '0055G000005xJLNQA2');
			obj0.putSObject('Owner', userSObject0);
			obj0.put('Budget_Confirmed__c', true);
			obj0.put('Discovery_Completed__c', true);
			obj0.put('ROI_Analysis_Completed__c', true);
			obj0.put('Escrows_Waived__c', true);
			obj0.put('First_Time_Homebuyer__c', true);
			obj0.put('Appraisal_Required__c', true);
			obj0.put('RateSheet_Checkbox__c', true);
			obj0.put('Title_Required__c', true);
			obj0.put('Payoff_Required__c', true);
			obj0.put('X2nd_Payoff_Required__c', true);
			obj0.put('Credit_Supplement_Required__c', true);
			obj0.put('Evidence_of_Insurance_Required__c', true);
			obj0.put('Subordination_Required__c', true);
			obj0.put('VOE_Required__c', true);
			obj0.put('Send_Gift_Required__c', true);
			obj0.put('Update_Loan_File_Team__c', true);
			obj0.put('Override_Stage_Change__c', true);
			obj0.put('HOA_Docs_Required__c', true);
			obj0.put('encompass_By_EM__Is_Deleted__c', true);
			obj0.put('Adjustments_Other_Credits__c', true);
			obj0.put('encompass_By_EM__Encompass_Loan_Id__c', 'testval');
        
		if(recordTypeId != 'default') {
			obj0.put('RecordTypeId', recordTypeId);
		}
		Database.insert(obj0);
		Test.stopTest();
	}
}